# -*- coding: utf-8 -*-
"""Reporte_ComparativoMensual_Actualizado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nbwa_IwfacVuu5xH7UJgTlDVgOcxN0hV
"""

# -*- coding: utf-8 -*-
"""Reporte_ComparativoMensual_Actualizado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nbwa_IwfacVuu5xH7UJgTlDVgOcxN0hV
"""

# -*- coding: utf-8 -*-
"""Reporte Comparativo Mensual — Bitácora de Solicitudes MG Colima.

Compara 1 o más meses de la bitácora de solicitudes (mismo formato que el
avance preliminar) y genera un PDF con gráficas comparativas e insights
automáticos: evolución del volumen y las categorías de cierre, tasa de
conversión a FINANCIADO, panorama financiero, colocación de GAP y
desempeño de vendedores a lo largo del periodo comparado.

Cada mes se sube como un archivo Excel independiente (mismo formato que
usa el avance preliminar). El nombre del mes se toma, por default, del
nombre de la primera hoja del Excel (ej. "JULIO").

Para usarlo en Google Colab: sube este .py o pega su contenido en una
celda, corre `main()` y selecciona los archivos Excel de los meses que
quieras comparar (puedes seleccionar varios a la vez en el diálogo de
subida).
"""

import warnings
warnings.filterwarnings("ignore")

import os
import re
import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib.colors import LinearSegmentedColormap, to_rgb

try:
    from google.colab import files  # noqa
    EN_COLAB = True
except ImportError:
    EN_COLAB = False

try:
    from IPython.display import display
except ImportError:
    display = print

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)

try:
    import reportlab
except ImportError:
    import subprocess
    subprocess.run(['pip', 'install', '-q', 'reportlab'])

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import cm
from reportlab.lib import colors as rl_colors
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image,
    PageBreak, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY


# =======================================================================
# 1) PALETA DE COLORES — misma identidad de marca que el avance preliminar
#    (rojos MG para categorías de cierre, azules Inbursa para el eje
#    temporal / comparación entre meses, neutros para el resto)
# =======================================================================
MG_ROJO          = "#E4002B"
MG_ROJO_OSCURO   = "#7A0019"
INBURSA_AZUL     = "#191970"
MG_ROJO_MEDIO    = "#B3001B"
MG_ROJO_CLARO    = "#FF6B6B"
MG_ROJO_PASTEL   = "#FFB3B3"
MG_ROJO_PALIDO   = "#FBE7E9"
MG_GRIS_OSCURO   = "#2B2B2B"
MG_GRIS_CLARO    = "#EAEAEA"
BLANCO           = "#FFFFFF"

GRIS_TEXTO_SEC   = "#6B7280"
GRIS_LINEA       = "#E3E5E9"
GRIS_ZEBRA       = "#F6F7F9"
AZUL_PALIDO      = "#EEF0F8"

# gradiente de rojos: se usa para lo que ya usaba el avance preliminar
# (vendedores, modelos, montos por vendedor, etc.)
PALETA_ROJOS = ["#7A0019", "#9E001F", "#C10024", "#E4002B",
                 "#F1354D", "#FF6B6B", "#FF9B9B", "#FFC7C7"]
_CMAP_ROJOS = LinearSegmentedColormap.from_list("rojos_mg", PALETA_ROJOS)

# gradiente de azules: NUEVO para este reporte — identifica "mes" en las
# gráficas comparativas, para no confundirlo visualmente con el rojo que
# ya está reservado para las categorías de cierre (Financiado/Aprobado/...)
PALETA_AZULES = ["#0D0D3D", "#191970", "#2E2E93", "#4B4BB8",
                  "#6E6ED0", "#9797E0", "#C2C2ED", "#E4E4F7"]
_CMAP_AZULES = LinearSegmentedColormap.from_list("azules_inbursa", PALETA_AZULES)


def _gradiente(n, cmap=_CMAP_ROJOS, tope=0.82):
    if n <= 1:
        return [MG_ROJO if cmap is _CMAP_ROJOS else INBURSA_AZUL]
    valores = np.linspace(0.0, tope, n)
    return [cmap(v) for v in valores]


def _gradiente_meses(n):
    """Un color por mes, en degradado de azules Inbursa (oscuro -> claro)."""
    return _gradiente(n, cmap=_CMAP_AZULES, tope=0.85)


def _color_texto_legible(color_fondo):
    r, g, b = to_rgb(color_fondo)
    luminancia = 0.299 * r + 0.587 * g + 0.114 * b
    return "white" if luminancia < 0.6 else MG_GRIS_OSCURO


# =======================================================================
# 1B) TIPOGRAFÍA — igual que el avance preliminar; cambia solo esta línea
# =======================================================================
FUENTE_BASE = "Helvetica"

_FUENTES_DISPONIBLES = {
    "Helvetica": {"regular": "Helvetica",   "bold": "Helvetica-Bold",
                  "italica": "Helvetica-Oblique", "bold_italica": "Helvetica-BoldOblique"},
    "Times":     {"regular": "Times-Roman", "bold": "Times-Bold",
                  "italica": "Times-Italic",      "bold_italica": "Times-BoldItalic"},
    "Courier":   {"regular": "Courier",     "bold": "Courier-Bold",
                  "italica": "Courier-Oblique",    "bold_italica": "Courier-BoldOblique"},
}
_fuente_activa = _FUENTES_DISPONIBLES.get(FUENTE_BASE, _FUENTES_DISPONIBLES["Helvetica"])
FUENTE_REGULAR      = _fuente_activa["regular"]
FUENTE_BOLD         = _fuente_activa["bold"]
FUENTE_ITALICA      = _fuente_activa["italica"]
FUENTE_BOLD_ITALICA = _fuente_activa["bold_italica"]

# =======================================================================
# CATÁLOGO DE ESTATUS
# Los colores, el orden y las etiquetas de cada categoría ya NO viven aquí:
# están en herramientas/estatus.py, que es la fuente única de verdad para
# los tres reportes. Para agregar un estatus nuevo, edita ESE archivo.
# =======================================================================
try:
    from . import estatus as _est
except ImportError:  # ejecución suelta (Colab, o el .py fuera del paquete)
    import estatus as _est

ORDEN_CATEGORIAS = _est.ORDEN_CATEGORIAS
COLOR_CATEGORIA = _est.COLOR_CATEGORIA

NOMBRE_EMPRESA = "AUTOEXPRESS INBURSA"
SUBTITULO_EMPRESA = "MG Colima PYD"
NOMBRE_ANALISTA = "Christian Ramos"

_MESES_ES = ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio",
             "agosto", "septiembre", "octubre", "noviembre", "diciembre"]

plt.rcParams.update({
    "figure.facecolor":  "white",
    "axes.facecolor":    "white",
    "axes.edgecolor":    GRIS_LINEA,
    "axes.labelcolor":   GRIS_TEXTO_SEC,
    "text.color":        MG_GRIS_OSCURO,
    "xtick.color":       GRIS_TEXTO_SEC,
    "ytick.color":       GRIS_TEXTO_SEC,
    "font.size":         10,
    "axes.titlesize":    12.5,
    "axes.titleweight":  "bold",
    "axes.titlecolor":   MG_GRIS_OSCURO,
    "axes.titlepad":     14,
    "axes.labelsize":    9.5,
    "axes.linewidth":    0.8,
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "axes.spines.left":  True,
    "axes.grid":         False,
    "xtick.labelsize":   9,
    "ytick.labelsize":   9,
    "legend.fontsize":   9,
    "legend.frameon":    False,
})

CARPETA_GRAFICAS = "graficas_temp_comparativo"
os.makedirs(CARPETA_GRAFICAS, exist_ok=True)


# =======================================================================
# 2) CARGA DE ARCHIVOS — uno o más meses
# =======================================================================
def _orden_mes(etiqueta_mes):
    """Ubica el nombre del mes dentro del calendario (0=enero..11=diciembre)
    buscando el nombre del mes en español dentro de la etiqueta, sin importar
    mayúsculas/año pegado (ej. "JULIO 2026" -> julio). Si no se reconoce
    ningún mes, regresa 999 para que quede al final, en el orden en que se subió."""
    texto = str(etiqueta_mes).strip().lower()
    for i, nombre in enumerate(_MESES_ES):
        if nombre in texto:
            return i
    return 999


def cargar_multiples_archivos(rutas_locales=None, nombres_meses=None):
    """
    Sube (en Colab, puedes seleccionar varios archivos a la vez) o abre
    (fuera de Colab) los archivos Excel de la bitácora, uno por mes a
    comparar, y regresa una lista de tuplas (mes, dataframe_crudo).

    rutas_locales: lista opcional de rutas locales a los archivos Excel.
    nombres_meses: lista opcional del mismo tamaño que rutas_locales, con
        la etiqueta de mes a usar para cada archivo (ej. ["JULIO", "AGOSTO"]).
        Si no se indica, se usa el nombre de la primera hoja de cada Excel.
    """
    if rutas_locales:
        rutas = list(rutas_locales)
    elif EN_COLAB:
        print("Sube los archivos Excel de la bitácora (uno por mes; puedes "
              "seleccionar varios a la vez en el diálogo)...")
        subido = files.upload()
        rutas = list(subido.keys())
    else:
        rutas_input = input("Rutas de los archivos Excel, separadas por coma: ").strip()
        rutas = [r.strip() for r in rutas_input.split(",") if r.strip()]

    if not rutas:
        raise ValueError("No se proporcionó ningún archivo para comparar.")

    if nombres_meses and len(nombres_meses) != len(rutas):
        print("Aviso: 'nombres_meses' no coincide en longitud con los archivos "
              "subidos; se ignorará y se usará el nombre de hoja de cada Excel.")
        nombres_meses = None

    resultado = []
    for i, ruta in enumerate(rutas):
        xls = pd.ExcelFile(ruta)
        hoja = xls.sheet_names[0]
        if len(xls.sheet_names) > 1:
            print(f"'{ruta}' tiene varias hojas: {xls.sheet_names}. Se usará '{hoja}'.")
        df_crudo = pd.read_excel(ruta, sheet_name=hoja)
        mes = (nombres_meses[i].strip().upper() if nombres_meses
               else str(hoja).strip().upper())
        print(f"Archivo cargado: {ruta}  |  Mes: {mes}  |  Hoja: {hoja}  |  {len(df_crudo)} solicitudes")
        resultado.append((mes, df_crudo))
    print()
    return resultado


# =======================================================================
# 3) LIMPIEZA Y NORMALIZACIÓN — idéntico al avance preliminar
# =======================================================================
COLUMNAS_ESPERADAS = [
    "Folio CCK", "STATUS", "Nombre Completo", "Fecha de Nacimiento",
    "Teléfono Móvil", "Correo Electrónico", "Nombre del Vendedor",
    "Marca", "Vehículo", "Año Modelo", "Precio Venta (c/IVA)",
    "Enganche", "¿Tiene GAP?", "Monto GAP", "Plazo (meses)",
    "Tasa Interés Anual", "Monto Total a Financiar",
    "Mensualidad Mínima", "Mensualidad Máxima",
]

COLUMNAS_MONEDA = [
    "Precio Venta (c/IVA)", "Enganche", "Monto GAP",
    "Monto Total a Financiar", "Mensualidad Mínima", "Mensualidad Máxima",
]
COLUMNAS_PORCENTAJE = ["Tasa Interés Anual"]

# Los sinónimos de cada estatus están definidos en herramientas/estatus.py.
# Se re-exportan por compatibilidad con código que los importara de aquí.
STATUS_APROBADO   = _est.STATUS_APROBADO
STATUS_FINANCIADO = _est.STATUS_FINANCIADO
STATUS_RECHAZADOS = _est.STATUS_RECHAZADOS


def _limpiar_moneda(serie):
    return (
        serie.astype(str)
             .str.replace(r"[\$,]", "", regex=True)
             .str.strip()
             .replace({"nan": np.nan, "": np.nan, "None": np.nan})
             .astype(float)
    )


def _limpiar_porcentaje(serie):
    def _convertir(valor):
        if pd.isna(valor):
            return np.nan
        if isinstance(valor, str):
            texto = valor.strip().replace("%", "")
            if texto in ("", "nan", "None"):
                return np.nan
            try:
                return float(texto)
            except ValueError:
                return np.nan
        try:
            numero = float(valor)
        except (TypeError, ValueError):
            return np.nan
        return numero * 100 if numero <= 1 else numero
    return serie.apply(_convertir)


def clasificar_status(status):
    """Traduce el STATUS crudo del Excel a su categoría.

    Un estatus que no esté en el catálogo YA NO se mete a la fuerza en
    "CONTRAPROPUESTA": se respeta como categoría propia.
    Ver herramientas/estatus.py.
    """
    return _est.clasificar_status(status)


def limpiar_datos(df_original, mes=None):
    df = df_original.copy()
    df.columns = [str(c).strip() for c in df.columns]

    faltantes = [c for c in COLUMNAS_ESPERADAS if c not in df.columns]
    if faltantes:
        print(f"Aviso ({mes}): no se encontraron estas columnas esperadas: {faltantes}")

    for col in COLUMNAS_MONEDA:
        if col in df.columns:
            df[col] = _limpiar_moneda(df[col])

    for col in COLUMNAS_PORCENTAJE:
        if col in df.columns:
            df[col] = _limpiar_porcentaje(df[col])

    if "STATUS" in df.columns:
        df["STATUS"] = df["STATUS"].astype(str).str.strip().str.upper()
        df["Categoria"] = df["STATUS"].apply(clasificar_status)
        # Da de alta (con color y lugar en el orden) cualquier estatus de la
        # bitácora que no esté en el catálogo.
        _est.registrar_categorias(df["Categoria"].unique())

    if "Nombre del Vendedor" in df.columns:
        df["Nombre del Vendedor"] = df["Nombre del Vendedor"].astype(str).str.strip().str.title()

    if "Marca" in df.columns:
        df["Marca"] = df["Marca"].astype(str).str.strip().str.upper().replace("NAN", np.nan)

    if "Vehículo" in df.columns:
        df["Vehículo"] = df["Vehículo"].astype(str).str.strip().replace("None", np.nan)

    if "¿Tiene GAP?" in df.columns:
        df["¿Tiene GAP?"] = df["¿Tiene GAP?"].astype(str).str.strip().str.upper()

    if mes is not None:
        df["Mes"] = mes

    return df


# =======================================================================
# 4) CÁLCULOS POR MES — resumen general, por vendedor y por categoría
#    (mismas funciones que el avance preliminar, reutilizadas mes a mes)
# =======================================================================
def resumen_general(df, mes=None, silencioso=False):
    if not silencioso:
        print("-" * 72)
        print(f" RESUMEN — {mes}" if mes else " RESUMEN GENERAL")
        print("-" * 72)

    total = len(df)
    r = {"total": total, "mes": mes}

    if "Categoria" in df.columns:
        conteo_cat = df["Categoria"].value_counts()

        # Conteo de TODAS las categorías del mes, no solo de cuatro fijas.
        conteo_categorias = {
            c: int(conteo_cat.get(c, 0)) for c in _est.categorias_presentes(df)
        }

        financiados = int(conteo_cat.get("FINANCIADO", 0))
        aprobados   = int(conteo_cat.get("APROBADO", 0))
        rechazados  = int(conteo_cat.get("RECHAZADO", 0))

        # "en_tramite" agrupa todo lo que quedó sin resolver (contrapropuesta,
        # en proceso, en revisión, pendiente...), excepto lo ya aprobado.
        claves_abiertas = [c for c in _est.claves_por_grupo(_est.ABIERTA)
                           if c != "APROBADO"]
        en_tramite = sum(int(conteo_cat.get(c, 0)) for c in claves_abiertas)

        r.update({"financiados": financiados, "aprobados": aprobados,
                   "rechazados": rechazados, "en_tramite": en_tramite,
                   "conteo_categorias": conteo_categorias})
        if not silencioso:
            detalle = "  |  ".join(
                f"{_est.etiqueta(c)}: {n}" for c, n in conteo_categorias.items()
            )
            print(f"Total: {total}  |  {detalle}")
    else:
        financiados = aprobados = 0

    monto_col = "Monto Total a Financiar"
    if monto_col in df.columns:
        r["monto_total"] = df[monto_col].sum()
        if "Categoria" in df.columns:
            r["monto_financiado"] = df.loc[df["Categoria"] == "FINANCIADO", monto_col].sum()
            r["monto_aprobado"] = df.loc[df["Categoria"] == "APROBADO", monto_col].sum()
            if financiados:
                r["ticket_financiado"] = df.loc[df["Categoria"] == "FINANCIADO", monto_col].mean()
            if aprobados:
                r["ticket_aprobado"] = df.loc[df["Categoria"] == "APROBADO", monto_col].mean()

    if "Enganche" in df.columns and "Precio Venta (c/IVA)" in df.columns:
        r["pct_enganche"] = (df["Enganche"] / df["Precio Venta (c/IVA)"] * 100).mean()

    if "Plazo (meses)" in df.columns:
        r["plazo_promedio"] = df["Plazo (meses)"].mean()

    if "Tasa Interés Anual" in df.columns:
        r["tasa_promedio"] = df["Tasa Interés Anual"].mean()

    if "¿Tiene GAP?" in df.columns:
        r["pct_gap"] = (df["¿Tiene GAP?"] == "SI").mean() * 100
        r["n_gap"] = int((df["¿Tiene GAP?"] == "SI").sum())
        if "Categoria" in df.columns and financiados:
            n_gap_financiado = int(((df["Categoria"] == "FINANCIADO") & (df["¿Tiene GAP?"] == "SI")).sum())
            r["n_gap_financiado"] = n_gap_financiado
            r["pct_gap_financiado"] = n_gap_financiado / financiados * 100

    cols_clave = [c for c in ["Marca", "Vehículo", "Monto Total a Financiar"] if c in df.columns]
    if cols_clave:
        r["incompletas"] = int(df[cols_clave].isna().any(axis=1).sum())

    if not silencioso:
        print()
    return r


def analisis_por_vendedor(df):
    if "Nombre del Vendedor" not in df.columns:
        return None
    total_por_vendedor = df.groupby("Nombre del Vendedor").size().rename("Total")
    tabla = pd.DataFrame({"Total": total_por_vendedor})

    if "Categoria" in df.columns:
        pivote = pd.crosstab(df["Nombre del Vendedor"], df["Categoria"])
        presentes = _est.categorias_presentes(df)
        for col in presentes:
            if col not in pivote.columns:
                pivote[col] = 0
        tabla = tabla.join(pivote[presentes])
        tabla["% Aprobación"] = (tabla["APROBADO"] / tabla["Total"] * 100).round(1)
        tabla["% Financiado"] = (tabla["FINANCIADO"] / tabla["Total"] * 100).round(1)

    if "Monto Total a Financiar" in df.columns and "Categoria" in df.columns:
        monto_financiado = (df[df["Categoria"] == "FINANCIADO"]
                             .groupby("Nombre del Vendedor")["Monto Total a Financiar"]
                             .sum().rename("Monto Financiado ($)"))
        monto_aprobado = (df[df["Categoria"] == "APROBADO"]
                           .groupby("Nombre del Vendedor")["Monto Total a Financiar"]
                           .sum().rename("Monto Aprobado ($)"))
        tabla = tabla.join(monto_financiado).join(monto_aprobado)
        tabla[["Monto Financiado ($)", "Monto Aprobado ($)"]] = tabla[
            ["Monto Financiado ($)", "Monto Aprobado ($)"]].fillna(0)

    if "¿Tiene GAP?" in df.columns:
        gap_total_v = df[df["¿Tiene GAP?"] == "SI"].groupby("Nombre del Vendedor").size()
        tabla["GAP Total"] = gap_total_v.reindex(tabla.index).fillna(0).astype(int)
        if "Categoria" in df.columns:
            gap_fin_v = (df[(df["Categoria"] == "FINANCIADO") & (df["¿Tiene GAP?"] == "SI")]
                         .groupby("Nombre del Vendedor").size())
            tabla["GAP Financiado"] = gap_fin_v.reindex(tabla.index).fillna(0).astype(int)

    return tabla.sort_values("Total", ascending=False)


def analisis_financiero_por_categoria(df):
    if "Categoria" not in df.columns:
        return None
    columnas_interes = [c for c in [
        "Precio Venta (c/IVA)", "Enganche", "Monto Total a Financiar",
        "Plazo (meses)", "Tasa Interés Anual",
    ] if c in df.columns]
    if not columnas_interes:
        return None
    tabla = df.groupby("Categoria")[columnas_interes].mean().round(2)
    orden_presente = [c for c in ORDEN_CATEGORIAS if c in tabla.index]
    tabla = tabla.reindex(orden_presente)
    if "¿Tiene GAP?" in df.columns:
        tabla["% con GAP"] = ((df["¿Tiene GAP?"] == "SI").groupby(df["Categoria"])
                               .mean().mul(100).round(1)).reindex(orden_presente)
    return tabla


def _quienes_maximo(serie):
    if serie is None or serie.empty:
        return [], 0
    maximo = serie.max()
    if pd.isna(maximo) or maximo <= 0:
        return [], 0
    return serie[serie == maximo].index.tolist(), maximo


def _nombres_y(nombres):
    nombres = [str(n) for n in nombres]
    if not nombres:
        return ""
    if len(nombres) == 1:
        return nombres[0]
    return ", ".join(nombres[:-1]) + " y " + nombres[-1]


def _lista_vendedores_por_categoria(df, categoria, max_nombres=4):
    nombres = (df.loc[df["Categoria"] == categoria, "Nombre del Vendedor"]
               .dropna().unique().tolist())
    primeros = sorted({n.split()[0] for n in nombres if n and n != "Nan"})
    if not primeros:
        return "—"
    if len(primeros) > max_nombres:
        return ", ".join(primeros[:max_nombres]) + f" +{len(primeros) - max_nombres} más"
    return ", ".join(primeros)


# =======================================================================
# 5) TABLA COMPARATIVA MENSUAL
# =======================================================================
def construir_tabla_comparativa(datos_por_mes, orden_meses):
    """Arma una tabla (una fila por mes, en orden cronológico) con los
    indicadores clave para comparar el periodo completo de un vistazo."""
    filas = []
    for mes in orden_meses:
        r = datos_por_mes[mes]["resumen"]
        total = r.get("total", 0)
        financiados = r.get("financiados", 0)
        aprobados = r.get("aprobados", 0)
        filas.append({
            "Mes": mes.title(),
            "Total": total,
            "Financiado": financiados,
            "Aprobado": aprobados,
            # Agrupa todo lo que quedó abierto (contrapropuesta, en proceso,
            # en revisión, pendiente...). El desglose por estatus se ve en la
            # gráfica de solicitudes por mes.
            "En trámite": r.get("en_tramite", 0),
            "Rechazado": r.get("rechazados", 0),
            "% Financiado": round(financiados / total * 100, 1) if total else 0.0,
            "Monto Total": r.get("monto_total", np.nan),
            "Monto Financiado": r.get("monto_financiado", np.nan),
            "Ticket Prom. Financiado": r.get("ticket_financiado", np.nan),
            "% GAP": round(r.get("pct_gap", np.nan), 1) if "pct_gap" in r else np.nan,
            "% GAP Financiado": round(r.get("pct_gap_financiado", np.nan), 1) if "pct_gap_financiado" in r else np.nan,
        })
    return pd.DataFrame(filas).set_index("Mes")


# =======================================================================
# 6) GRÁFICAS — utilidades comunes
# =======================================================================
def _formato_miles(ax, eje="y"):
    formatter = mticker.FuncFormatter(lambda x, _: f"{x:,.0f}")
    (ax.yaxis if eje == "y" else ax.xaxis).set_major_formatter(formatter)


def _guardar_si_procede(fig, guardar_como):
    if guardar_como:
        # La carpeta de gráficas se creaba UNA sola vez, al importar el
        # módulo. En un proceso de larga vida (Streamlit) eso no basta: si
        # algo la borra entre corridas —por ejemplo la limpieza de temporales
        # de la app— la siguiente corrida truena con "No such file or
        # directory", o peor, se queda sin gráficas en silencio. Asegurarla
        # aquí la vuelve a crear cuando haga falta.
        carpeta = os.path.dirname(guardar_como)
        if carpeta:
            os.makedirs(carpeta, exist_ok=True)
        fig.savefig(guardar_como, dpi=150, bbox_inches="tight", facecolor="white")
    return guardar_como


def imagen_ajustada(ruta, ancho_cm, alto_max_cm=None):
    ancho_px, alto_px = ImageReader(ruta).getSize()
    alto_cm = ancho_cm * (alto_px / ancho_px)
    if alto_max_cm and alto_cm > alto_max_cm:
        alto_cm = alto_max_cm
        ancho_cm = alto_cm * (ancho_px / alto_px)
    return Image(ruta, width=ancho_cm * cm, height=alto_cm * cm, hAlign="CENTER")


# --- 6A) Gráficas AGREGADAS del periodo completo (mismas del avance
#         preliminar, aplicadas al DataFrame combinado de todos los meses) ---
def grafica_vendedores(df, guardar_como=None, titulo="Solicitudes por vendedor"):
    if "Nombre del Vendedor" not in df.columns:
        return None
    conteo = df["Nombre del Vendedor"].value_counts().sort_values(ascending=True)
    fig, ax = plt.subplots(figsize=(8, max(4, len(conteo) * 0.5)))
    colores = list(reversed(_gradiente(len(conteo))))
    ax.barh(conteo.index, conteo.values, color=colores, edgecolor="white")
    for i, valor in enumerate(conteo.values):
        ax.text(valor + max(conteo.values) * 0.01, i, str(valor), va="center", fontsize=9)
    ax.set_title(titulo)
    ax.set_xlabel("Número de solicitudes")
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.close(fig)
    return guardar_como


def grafica_vendedor_status(df, guardar_como=None, titulo=None):
    if "Nombre del Vendedor" not in df.columns or "Categoria" not in df.columns:
        return None
    pivote = pd.crosstab(df["Nombre del Vendedor"], df["Categoria"])
    orden_cols = [c for c in ORDEN_CATEGORIAS if c in pivote.columns]
    # El título lista las categorías que de verdad hay en el periodo.
    if titulo is None:
        # Sin enumerar categorías: la leyenda ya las muestra y, con muchos
        # estatus, el título deformaba la imagen exportada.
        titulo = "Estatus de cierre por vendedor"
    pivote = pivote[orden_cols]
    pivote["Total"] = pivote.sum(axis=1)
    pivote = pivote.sort_values("Total", ascending=True).drop(columns="Total")
    fig, ax = plt.subplots(figsize=(9, max(4, len(pivote) * 0.55) + 0.8))
    izquierda = np.zeros(len(pivote))
    for col in orden_cols:
        valores = pivote[col].values
        ax.barh(pivote.index, valores, left=izquierda,
                 color=COLOR_CATEGORIA.get(col, MG_GRIS_CLARO),
                 label=_est.etiqueta(col), edgecolor="white")
        izquierda += valores
    ax.set_title(titulo)
    ax.set_xlabel("Número de solicitudes")
    ax.legend(loc="upper center", bbox_to_anchor=(0, -0.30, 1, 0.16),
              mode="expand", frameon=False, fontsize=8,
              handlelength=1.4, columnspacing=1.2,
              ncol=min(3, max(1, len(orden_cols))))
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.close(fig)
    return guardar_como


def grafica_modelos(df, guardar_como=None, titulo_extra=""):
    if "Vehículo" not in df.columns:
        return None
    conteo_completo = df["Vehículo"].dropna().value_counts()
    if conteo_completo.empty:
        return None
    TOP_N = 10
    recortado = len(conteo_completo) > TOP_N
    conteo = conteo_completo.head(TOP_N).sort_values(ascending=True)
    fig, ax = plt.subplots(figsize=(8, max(4, len(conteo) * 0.4)))
    colores = list(reversed(_gradiente(len(conteo))))
    ax.barh(conteo.index, conteo.values, color=colores, edgecolor="white")
    for i, valor in enumerate(conteo.values):
        ax.text(valor + max(conteo.values) * 0.02, i, str(valor), va="center", fontsize=9)
    titulo = f"Modelos más solicitados {titulo_extra}".strip()
    if recortado:
        titulo += f" (top {TOP_N})"
    ax.set_title(titulo)
    ax.set_xlabel("Número de solicitudes")
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.close(fig)
    return guardar_como


    return guardar_como


def grafica_gap_por_vendedor_total(df, guardar_como=None, titulo="Cobertura de GAP por vendedor"):
    if "Nombre del Vendedor" not in df.columns or "¿Tiene GAP?" not in df.columns:
        return None
    df_gap = df[df["¿Tiene GAP?"] == "SI"].copy()
    if df_gap.empty:
        return None
    conteo_gap = df_gap["Nombre del Vendedor"].value_counts()
    conteo_total = df["Nombre del Vendedor"].value_counts()
    vendedores = conteo_total.sort_values(ascending=True).index.tolist()
    valores_total = np.array([conteo_total.get(v, 0) for v in vendedores])
    valores_gap = np.array([conteo_gap.get(v, 0) for v in vendedores])
    maximo = max(valores_total.max(), valores_gap.max(), 1)
    y = np.arange(len(vendedores))
    alto = 0.36
    fig, ax = plt.subplots(figsize=(9, max(4, len(vendedores) * 0.65)))
    ax.barh(y + alto / 2, valores_total, height=alto, color=MG_GRIS_CLARO,
             edgecolor="white", label="Total de solicitudes")
    ax.barh(y - alto / 2, valores_gap, height=alto, color=MG_ROJO,
             edgecolor="white", label="Con GAP")
    for yi, valor in zip(y + alto / 2, valores_total):
        ax.text(valor + maximo * 0.015, yi, str(valor), va="center", fontsize=8)
    for yi, valor in zip(y - alto / 2, valores_gap):
        ax.text(valor + maximo * 0.015, yi, str(valor), va="center", fontsize=8)
    ax.set_yticks(y)
    ax.set_yticklabels(vendedores)
    ax.set_xlim(0, maximo * 1.18)
    ax.set_title(titulo)
    ax.set_xlabel("Número de solicitudes")
    ax.legend(loc="lower right", frameon=False)
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.close(fig)
    return guardar_como


def grafica_gap_financiado_por_vendedor(df, guardar_como=None, titulo="GAP en créditos financiados, por vendedor"):
    if not {"Nombre del Vendedor", "Categoria", "¿Tiene GAP?"}.issubset(df.columns):
        return None
    df_fin_gap = df[(df["Categoria"] == "FINANCIADO") & (df["¿Tiene GAP?"] == "SI")].copy()
    if df_fin_gap.empty:
        return None
    conteo = df_fin_gap["Nombre del Vendedor"].value_counts().sort_values(ascending=True)
    fig, ax = plt.subplots(figsize=(8, max(4, len(conteo) * 0.5)))
    colores = list(reversed(_gradiente(len(conteo))))
    max_gap = conteo.max()
    vendedores_top = conteo[conteo == max_gap].index.tolist()
    ax.barh(conteo.index, conteo.values, color=colores, edgecolor="white")
    for i, (vendedor, valor) in enumerate(conteo.items()):
        ax.text(valor + max(conteo.values) * 0.01, i, str(valor), va="center", fontsize=9)
        if vendedor in vendedores_top and max_gap > 0:
            ax.text(valor + max(conteo.values) * 0.05, i, f"¡Felicidades, {vendedor}!",
                     va="center", fontsize=9, color=MG_ROJO_OSCURO, fontweight="bold")
    ax.set_title(titulo)
    ax.set_xlabel("Solicitudes FINANCIADAS con GAP")
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.close(fig)
    return guardar_como


# --- 6B) Gráficas COMPARATIVAS entre meses (nuevas de este reporte) ---
def grafica_comp_totales_por_mes(datos_por_mes, orden_meses, guardar_como=None):
    """Barras apiladas por mes: cuántas solicitudes cerraron en cada categoría."""
    meses_disp = [m for m in orden_meses if "Categoria" in datos_por_mes[m]["df"].columns]
    if not meses_disp:
        return None
    etiquetas = [m.title() for m in meses_disp]

    # Solo las categorías que aparecen en ALGUNO de los meses comparados,
    # para no meter series en cero a la leyenda cuando el catálogo tiene
    # muchos estatus posibles.
    cats_presentes = []
    for cat in ORDEN_CATEGORIAS:
        if any(cat in set(datos_por_mes[m]["df"]["Categoria"]) for m in meses_disp):
            cats_presentes.append(cat)

    fig, ax = plt.subplots(figsize=(max(7, len(meses_disp) * 1.3), 5.5))
    abajo = np.zeros(len(meses_disp))
    for cat in cats_presentes:
        valores = np.array([
            int(datos_por_mes[m]["df"]["Categoria"].value_counts().get(cat, 0))
            for m in meses_disp
        ])
        ax.bar(etiquetas, valores, bottom=abajo, color=COLOR_CATEGORIA.get(cat, MG_GRIS_CLARO),
               edgecolor="white", label=_est.etiqueta(cat))
        for i, (v, b) in enumerate(zip(valores, abajo)):
            if v > 0:
                ax.text(i, b + v / 2, str(int(v)), ha="center", va="center",
                         fontsize=8.5, color=_color_texto_legible(COLOR_CATEGORIA.get(cat, MG_GRIS_CLARO)))
        abajo += valores
    totales = [int(datos_por_mes[m]["resumen"].get("total", 0)) for m in meses_disp]
    for i, t in enumerate(totales):
        ax.text(i, t + max(totales) * 0.02, f"Total: {t}", ha="center", va="bottom",
                 fontsize=9, fontweight="bold", color=MG_GRIS_OSCURO)
    ax.set_ylim(0, max(totales) * 1.18 if totales else 1)
    ax.set_title("Estatus de cierre por mes")
    ax.set_ylabel("Número de solicitudes")
    ax.legend(loc="upper center", bbox_to_anchor=(0, -0.30, 1, 0.16),
              mode="expand", frameon=False, fontsize=8,
              handlelength=1.4, columnspacing=1.2,
              ncol=min(3, max(1, len(cats_presentes))))
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.close(fig)
    return guardar_como


def grafica_comp_tasa_conversion(tabla_comp, guardar_como=None):
    """Línea: % Financiado y % Aprobado por mes (tendencia de conversión)."""
    if tabla_comp.empty or "% Financiado" not in tabla_comp.columns:
        return None
    meses = tabla_comp.index.tolist()
    pct_fin = tabla_comp["% Financiado"].values
    pct_apr = ((tabla_comp["Aprobado"] / tabla_comp["Total"]).fillna(0) * 100).values

    fig, ax = plt.subplots(figsize=(max(7, len(meses) * 1.3), 5.5))
    ax.plot(meses, pct_fin, marker="o", linewidth=2.4, color=MG_ROJO_OSCURO, label="% Financiado")
    ax.plot(meses, pct_apr, marker="o", linewidth=2.0, color=INBURSA_AZUL,
             linestyle="--", label="% Aprobado")
    for i, v in enumerate(pct_fin):
        ax.text(i, v - 4, f"{v:.0f}%", ha="center", va="top", fontsize=9, fontweight="bold", color=MG_ROJO_OSCURO)
    for i, v in enumerate(pct_apr):
        ax.text(i, v + 4, f"{v:.0f}%", ha="center", va="bottom", fontsize=8.5, color=INBURSA_AZUL)
    ax.set_ylim(0, max(pct_fin.max() if len(pct_fin) else 0, pct_apr.max() if len(pct_apr) else 0) * 1.35 + 5)
    ax.set_title("Tasa de conversión por mes")
    ax.set_ylabel("% de las solicitudes del mes")
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.1), frameon=False, ncol=2)
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.close(fig)
    return guardar_como


def grafica_comp_montos_por_mes(tabla_comp, guardar_como=None):
    """Barras agrupadas: monto financiado vs monto aprobado, por mes."""
    if tabla_comp.empty or "Monto Financiado" not in tabla_comp.columns:
        return None
    meses = tabla_comp.index.tolist()
    monto_fin = tabla_comp["Monto Financiado"].fillna(0).values
    monto_tot = tabla_comp["Monto Total"].fillna(0).values
    monto_apr = np.clip(monto_tot - monto_fin, 0, None)  # aproximación: resto del monto total
    x = np.arange(len(meses))
    ancho = 0.38
    fig, ax = plt.subplots(figsize=(max(7, len(meses) * 1.4), 5.5))
    ax.bar(x - ancho / 2, monto_fin, width=ancho, color=MG_ROJO_OSCURO, edgecolor="white", label="Monto Financiado")
    ax.bar(x + ancho / 2, monto_tot, width=ancho, color=MG_GRIS_CLARO, edgecolor="white", label="Monto Total a Financiar (todas)")
    for xi, v in zip(x - ancho / 2, monto_fin):
        ax.text(xi, v + max(monto_tot.max(), 1) * 0.015, f"${v:,.0f}", ha="center", fontsize=7.5, rotation=90 if len(meses) > 4 else 0, va="bottom")
    for xi, v in zip(x + ancho / 2, monto_tot):
        ax.text(xi, v + max(monto_tot.max(), 1) * 0.015, f"${v:,.0f}", ha="center", fontsize=7.5, rotation=90 if len(meses) > 4 else 0, va="bottom")
    ax.set_xticks(x)
    ax.set_xticklabels(meses)
    _formato_miles(ax, eje="y")
    ax.set_title("Monto total vs. financiado por mes")
    ax.set_ylabel("Monto ($ MXN)")
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.1), frameon=False, ncol=2)
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.close(fig)
    return guardar_como


def grafica_comp_gap_por_mes(tabla_comp, guardar_como=None):
    """Línea: % de solicitudes con GAP, por mes (tendencia)."""
    if tabla_comp.empty or "% GAP" not in tabla_comp.columns or tabla_comp["% GAP"].isna().all():
        return None
    meses = tabla_comp.index.tolist()
    valores = tabla_comp["% GAP"].fillna(0).values
    fig, ax = plt.subplots(figsize=(max(7, len(meses) * 1.3), 5.5))
    ax.plot(meses, valores, marker="o", linewidth=2.4, markersize=7,
             color=MG_ROJO_OSCURO, markerfacecolor=MG_ROJO_OSCURO, markeredgecolor="white")
    for i, valor in enumerate(valores):
        ax.text(i, valor + 3, f"{valor:.0f}%", ha="center", va="bottom",
                 fontsize=9, fontweight="bold", color=MG_ROJO_OSCURO)
    maximo = valores.max() if len(valores) else 0
    ax.set_ylim(0, maximo * 1.3 + 10)
    ax.set_title("% con GAP por mes")
    ax.set_ylabel("% con GAP")
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.close(fig)
    return guardar_como


def grafica_comp_gap_vs_gap_financiado(tabla_comp, guardar_como=None):
    """Líneas: % GAP (todas las solicitudes) vs % GAP Financiado (solo dentro
    de los créditos ya FINANCIADOS), por mes. Compara si el GAP se está
    colocando también en las solicitudes que sí terminan dispersándose."""
    if tabla_comp.empty or "% GAP Financiado" not in tabla_comp.columns or \
       tabla_comp["% GAP Financiado"].isna().all():
        return None

    meses = tabla_comp.index.tolist()
    pct_gap = tabla_comp["% GAP"].fillna(0).values if "% GAP" in tabla_comp.columns else None
    pct_gap_fin = tabla_comp["% GAP Financiado"].fillna(0).values

    fig, ax = plt.subplots(figsize=(max(7, len(meses) * 1.3), 5.5))
    ax.plot(meses, pct_gap_fin, marker="o", linewidth=2.4, color=MG_ROJO_OSCURO,
             label="% GAP Financiado")
    for i, v in enumerate(pct_gap_fin):
        ax.text(i, v + 3, f"{v:.0f}%", ha="center", fontsize=9, fontweight="bold", color=MG_ROJO_OSCURO)

    maximo = pct_gap_fin.max() if len(pct_gap_fin) else 0
    if pct_gap is not None:
        ax.plot(meses, pct_gap, marker="o", linewidth=2.0, color=INBURSA_AZUL,
                 linestyle="--", label="% GAP (todas las solicitudes)")
        for i, v in enumerate(pct_gap):
            ax.text(i, v + 3, f"{v:.0f}%", ha="center", fontsize=8.5, color=INBURSA_AZUL)
        maximo = max(maximo, pct_gap.max() if len(pct_gap) else 0)

    ax.set_ylim(0, maximo * 1.35 + 8)
    ax.set_title("GAP total vs. GAP financiado por mes")
    ax.set_ylabel("% de solicitudes")
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.1), frameon=False, ncol=2)
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.close(fig)
    return guardar_como


def generar_graficas_comparativas(datos_por_mes, orden_meses, tabla_comp, df_combinado):
    print("=" * 72)
    print(" GENERANDO GRÁFICAS PARA EL REPORTE COMPARATIVO")
    print("=" * 72)
    especificaciones = [
        ("totales_mes",        lambda ruta: grafica_comp_totales_por_mes(datos_por_mes, orden_meses, ruta), "c01_totales_mes.png"),
        ("tasa_conversion",    lambda ruta: grafica_comp_tasa_conversion(tabla_comp, ruta),                   "c02_tasa_conversion.png"),
        ("montos_mes",         lambda ruta: grafica_comp_montos_por_mes(tabla_comp, ruta),                    "c03_montos_mes.png"),
        ("gap_mes",            lambda ruta: grafica_comp_gap_por_mes(tabla_comp, ruta),                       "c04_gap_mes.png"),
        ("gap_vs_gap_fin_mes", lambda ruta: grafica_comp_gap_vs_gap_financiado(tabla_comp, ruta),              "c04b_gap_vs_gap_fin_mes.png"),
        ("vendedores",         lambda ruta: grafica_vendedores(df_combinado, ruta),                           "c06_vendedores.png"),
        ("vendedor_status",    lambda ruta: grafica_vendedor_status(df_combinado, ruta),                      "c07_vendedor_status.png"),
        ("gap_por_vendedor",   lambda ruta: grafica_gap_por_vendedor_total(df_combinado, ruta),               "c09_gap_vendedor.png"),
        ("gap_financiado_vend", lambda ruta: grafica_gap_financiado_por_vendedor(df_combinado, ruta),         "c10_gap_financiado_vendedor.png"),
        ("modelos",            lambda ruta: grafica_modelos(df_combinado, ruta),                              "c11_modelos.png"),
    ]
    rutas = {}
    for clave, funcion, nombre_png in especificaciones:
        ruta = os.path.join(CARPETA_GRAFICAS, nombre_png)
        try:
            resultado = funcion(ruta)
        except Exception as e:
            print(f"  Aviso: no se pudo generar la gráfica '{clave}' ({e}).")
            resultado = None
        if resultado:
            rutas[clave] = resultado
            print(f"  OK  {clave}")
        else:
            print(f"  --  {clave} (sin datos suficientes, se omite)")
    print()

    # Guarda de seguridad: si NINGUNA gráfica se pudo generar, algo está mal
    # de fondo (carpeta borrada, permisos, columnas faltantes). Antes el
    # reporte se armaba igual y salía un PDF entero sin una sola gráfica, sin
    # ningún error visible. Es mejor fallar fuerte y decir por qué.
    if not rutas:
        raise RuntimeError(
            "No se pudo generar ninguna gráfica. Revisa que el archivo traiga "
            "las columnas esperadas (STATUS, Nombre del Vendedor, etc.) y que "
            f"la carpeta '{CARPETA_GRAFICAS}' se pueda escribir."
        )

    return rutas


# =======================================================================
# 7) INSIGHTS AUTOMÁTICOS
# =======================================================================
def generar_insights_automaticos(tabla_comp, orden_meses, datos_por_mes, df_combinado):
    insights = []
    n_meses = len(orden_meses)
    meses_fmt = [m.title() for m in orden_meses]

    if n_meses == 1:
        insights.append(
            f"<b>Un solo mes cargado:</b> este reporte solo incluye {meses_fmt[0]}, por lo que "
            f"no hay todavía una tendencia mes a mes que comparar. Sube uno o más meses "
            f"adicionales para ver la evolución del volumen, la conversión y el GAP en el tiempo."
        )

    if n_meses >= 2 and "Total" in tabla_comp.columns:
        totales = tabla_comp["Total"]
        mes_max_total = totales.idxmax()
        mes_min_total = totales.idxmin()
        if mes_max_total == mes_min_total:
            insights.append(
                f"<b>Volumen de solicitudes:</b> los {n_meses} meses comparados tuvieron el mismo "
                f"número de solicitudes registradas ({int(totales.max())})."
            )
        else:
            insights.append(
                f"<b>Volumen de solicitudes:</b> {mes_max_total} fue el mes con más solicitudes "
                f"registradas ({int(totales.max())}), mientras que {mes_min_total} tuvo el menor "
                f"volumen ({int(totales.min())})."
            )
        primero, ultimo = totales.iloc[0], totales.iloc[-1]
        if primero > 0:
            cambio = (ultimo - primero) / primero * 100
            if abs(cambio) < 1:
                insights.append(
                    f"<b>Tendencia del periodo:</b> del primer mes comparado ({meses_fmt[0]}) al "
                    f"último ({meses_fmt[-1]}), el volumen de solicitudes se mantuvo estable."
                )
            else:
                direccion = "creció" if cambio > 0 else "cayó"
                insights.append(
                    f"<b>Tendencia del periodo:</b> del primer mes comparado ({meses_fmt[0]}) al "
                    f"último ({meses_fmt[-1]}), el volumen de solicitudes {direccion} "
                    f"{abs(cambio):.0f}%."
                )

    if n_meses >= 1 and "% Financiado" in tabla_comp.columns:
        conv = tabla_comp["% Financiado"]
        mes_mejor_conv = conv.idxmax()
        insights.append(
            f"<b>Mejor conversión a FINANCIADO:</b> {mes_mejor_conv} tuvo la tasa de conversión "
            f"más alta del periodo, con {conv.max():.1f}% de sus solicitudes convertidas en "
            f"crédito FINANCIADO."
        )
        if n_meses >= 2:
            mes_peor_conv = conv.idxmin()
            if mes_peor_conv != mes_mejor_conv:
                insights.append(
                    f"En contraste, {mes_peor_conv} registró la conversión más baja "
                    f"({conv.min():.1f}%); conviene revisar si se debió al seguimiento de "
                    f"solicitudes APROBADAS/CONTRAPROPUESTA o por menor calidad de las "
                    f"solicitudes entrantes ese mes."
                )

    if "% GAP" in tabla_comp.columns and tabla_comp["% GAP"].notna().any():
        gap = tabla_comp["% GAP"].dropna()
        if not gap.empty:
            mes_mejor_gap = gap.idxmax()
            insights.append(
                f"<b>Venta cruzada de GAP:</b> {mes_mejor_gap} tuvo la mayor proporción de "
                f"solicitudes con GAP colocado, con {gap.max():.1f}%."
            )
            if n_meses >= 2:
                mes_peor_gap = gap.idxmin()
                if mes_peor_gap != mes_mejor_gap:
                    insights.append(
                        f"{mes_peor_gap} fue el mes con menor colocación de GAP ({gap.min():.1f}%); "
                        f"reforzar esta venta cruzada ahí podría representar ingresos adicionales "
                        f"sin necesidad de más solicitudes."
                    )

    if "% GAP Financiado" in tabla_comp.columns and tabla_comp["% GAP Financiado"].notna().any():
        gap_fin = tabla_comp["% GAP Financiado"].dropna()
        if not gap_fin.empty:
            mes_mejor_gap_fin = gap_fin.idxmax()
            insights.append(
                f"<b>GAP dentro de créditos FINANCIADOS:</b> {mes_mejor_gap_fin} tuvo la mayor "
                f"proporción de créditos ya FINANCIADOS con GAP colocado, con "
                f"{gap_fin.max():.1f}% — el indicador más relevante, porque ese GAP ya está "
                f"efectivamente vendido."
            )
            if "% GAP" in tabla_comp.columns:
                brecha = (tabla_comp["% GAP"] - tabla_comp["% GAP Financiado"]).dropna()
                if not brecha.empty:
                    mes_mayor_brecha = brecha.idxmax()
                    if brecha.loc[mes_mayor_brecha] > 5:
                        insights.append(
                            f"En {mes_mayor_brecha}, el % de GAP general ({tabla_comp.loc[mes_mayor_brecha, '% GAP']:.1f}%) "
                            f"superó por {brecha.loc[mes_mayor_brecha]:.0f} puntos al % de GAP dentro de "
                            f"FINANCIADOS ({tabla_comp.loc[mes_mayor_brecha, '% GAP Financiado']:.1f}%); es decir, "
                            f"parte del GAP colocado ese mes fue en solicitudes que no llegaron a dispersarse."
                        )

    if "Nombre del Vendedor" in df_combinado.columns:
        top_vend = df_combinado["Nombre del Vendedor"].value_counts()
        if not top_vend.empty:
            nombres_top, val_top = _quienes_maximo(top_vend)
            insights.append(
                f"<b>Vendedor con más actividad en el periodo:</b> {_nombres_y(nombres_top)} "
                f"{'concentran' if len(nombres_top) > 1 else 'concentra'} el mayor número de "
                f"solicitudes generadas en total ({int(val_top)}), sumando todos los meses comparados."
            )
        if "Categoria" in df_combinado.columns:
            top_fin = (df_combinado[df_combinado["Categoria"] == "FINANCIADO"]
                       .groupby("Nombre del Vendedor").size())
            nombres_fin, val_fin = _quienes_maximo(top_fin)
            if nombres_fin:
                insights.append(
                    f"<b>Mejor conversión acumulada:</b> {_nombres_y(nombres_fin)} "
                    f"{'lideran' if len(nombres_fin) > 1 else 'lidera'} en créditos FINANCIADOS "
                    f"a lo largo del periodo, con {int(val_fin)}."
                )

    if "Monto Financiado" in tabla_comp.columns and tabla_comp["Monto Financiado"].notna().any():
        monto_total_periodo = tabla_comp["Monto Financiado"].fillna(0).sum()
        insights.append(
            f"<b>Monto financiado acumulado:</b> en el periodo comparado se dispersaron "
            f"${monto_total_periodo:,.2f} en créditos FINANCIADOS."
        )

    if not insights:
        insights.append(
            "No se generaron insights automáticos adicionales: revisa que los archivos fuente "
            "incluyan las columnas STATUS, Nombre del Vendedor y Monto Total a Financiar."
        )
    return insights


# =======================================================================
# 8) GENERACIÓN DEL PDF
# =======================================================================
def generar_reporte_pdf_comparativo(datos_por_mes, orden_meses, tabla_comp,
                                     df_combinado, nombre_archivo=None,
                                     recolectar_elementos=None):
    if nombre_archivo is None:
        fecha_archivo = datetime.datetime.now().strftime("%Y%m%d_%H%M")
        rango = f"{orden_meses[0].title()}" if len(orden_meses) == 1 else \
                f"{orden_meses[0].title()}_a_{orden_meses[-1].title()}"
        nombre_archivo = f"Reporte_Comparativo_{rango}_{fecha_archivo}.pdf"

    print("=" * 72)
    print(" GENERANDO REPORTE PDF COMPARATIVO")
    print("=" * 72)

    rutas_graficas = generar_graficas_comparativas(datos_por_mes, orden_meses, tabla_comp, df_combinado)
    insights = generar_insights_automaticos(tabla_comp, orden_meses, datos_por_mes, df_combinado)

    # --- Estilos (idénticos al avance preliminar) ---
    styles = getSampleStyleSheet()
    estilo_kicker_portada = ParagraphStyle(
        "KickerPortada", parent=styles["Normal"], fontName=FUENTE_BOLD, fontSize=9.5,
        textColor=rl_colors.HexColor(MG_ROJO), alignment=TA_LEFT, spaceAfter=6, leading=12)
    estilo_titulo_portada = ParagraphStyle(
        "TituloPortada", parent=styles["Title"], fontName=FUENTE_BOLD, fontSize=25,
        textColor=rl_colors.HexColor(INBURSA_AZUL), alignment=TA_LEFT, spaceAfter=4, leading=29)
    estilo_subtitulo_portada = ParagraphStyle(
        "SubtituloPortada", parent=styles["Normal"], fontName=FUENTE_REGULAR, fontSize=12,
        textColor=rl_colors.HexColor(GRIS_TEXTO_SEC), alignment=TA_LEFT, spaceAfter=4)
    estilo_meta_portada = ParagraphStyle(
        "MetaPortada", parent=styles["Normal"], fontName=FUENTE_REGULAR, fontSize=9.5,
        textColor=rl_colors.HexColor(GRIS_TEXTO_SEC), alignment=TA_LEFT, leading=13)
    estilo_h1 = ParagraphStyle(
        "H1MG", parent=styles["Heading1"], fontName=FUENTE_BOLD, fontSize=15.5,
        textColor=rl_colors.HexColor(INBURSA_AZUL), spaceBefore=16, spaceAfter=8)
    estilo_h2 = ParagraphStyle(
        "H2MG", parent=styles["Heading2"], fontName=FUENTE_BOLD, fontSize=12.5,
        textColor=rl_colors.HexColor(MG_ROJO_OSCURO), spaceBefore=10, spaceAfter=6)
    estilo_cuerpo = ParagraphStyle(
        "CuerpoMG", parent=styles["Normal"], fontName=FUENTE_REGULAR, fontSize=10,
        textColor=rl_colors.HexColor(MG_GRIS_OSCURO), leading=15, alignment=TA_JUSTIFY, spaceAfter=6)
    estilo_nota = ParagraphStyle(
        "NotaMG", parent=styles["Normal"], fontSize=8.5,
        textColor=rl_colors.HexColor(GRIS_TEXTO_SEC), leading=11, alignment=TA_LEFT,
        spaceAfter=4, fontName=FUENTE_ITALICA)
    estilo_kpi_valor = ParagraphStyle(
        "KPIValor", parent=styles["Normal"], fontSize=20,
        textColor=rl_colors.HexColor(MG_GRIS_OSCURO), alignment=TA_CENTER,
        fontName=FUENTE_BOLD, leading=23)
    estilo_kpi_label = ParagraphStyle(
        "KPILabel", parent=styles["Normal"], fontName=FUENTE_BOLD, fontSize=7.8,
        textColor=rl_colors.HexColor(GRIS_TEXTO_SEC), alignment=TA_CENTER, leading=9.5)
    estilo_encabezado_tabla = ParagraphStyle(
        "EncabezadoTabla", parent=styles["Normal"], fontSize=8.3, leading=10,
        textColor=rl_colors.white, fontName=FUENTE_BOLD, alignment=TA_CENTER)

    FECHA_REPORTE = datetime.date.today().strftime("%d/%m/%Y")
    PERIODO_TXT = orden_meses[0].title() if len(orden_meses) == 1 else \
        f"{orden_meses[0].title()} – {orden_meses[-1].title()}"

    def encabezado_pie_pagina(canvas_obj, doc):
        canvas_obj.saveState()
        ancho, alto = letter
        canvas_obj.setFillColor(rl_colors.HexColor(INBURSA_AZUL))
        canvas_obj.rect(0, alto - 0.14 * cm, ancho, 0.14 * cm, fill=1, stroke=0)
        canvas_obj.setFillColor(rl_colors.HexColor(MG_ROJO))
        canvas_obj.rect(1.5 * cm, alto - 1.05 * cm, 0.24 * cm, 0.24 * cm, fill=1, stroke=0)
        canvas_obj.setFillColor(rl_colors.HexColor(INBURSA_AZUL))
        canvas_obj.setFont(FUENTE_BOLD, 10.5)
        canvas_obj.drawString(1.95 * cm, alto - 1.0 * cm, NOMBRE_EMPRESA)
        canvas_obj.setFillColor(rl_colors.HexColor(GRIS_TEXTO_SEC))
        canvas_obj.setFont(FUENTE_REGULAR, 8)
        canvas_obj.drawString(1.95 * cm, alto - 1.32 * cm,
                               f"Reporte Comparativo Mensual · {SUBTITULO_EMPRESA}")
        canvas_obj.setFillColor(rl_colors.HexColor(GRIS_TEXTO_SEC))
        canvas_obj.setFont(FUENTE_REGULAR, 8.5)
        canvas_obj.drawRightString(ancho - 1.5 * cm, alto - 1.05 * cm, FECHA_REPORTE)
        canvas_obj.setStrokeColor(rl_colors.HexColor(GRIS_LINEA))
        canvas_obj.setLineWidth(0.8)
        canvas_obj.line(1.5 * cm, alto - 1.55 * cm, ancho - 1.5 * cm, alto - 1.55 * cm)
        canvas_obj.setStrokeColor(rl_colors.HexColor(GRIS_LINEA))
        canvas_obj.line(1.5 * cm, 1.05 * cm, ancho - 1.5 * cm, 1.05 * cm)
        canvas_obj.setFillColor(rl_colors.HexColor(MG_ROJO))
        canvas_obj.rect(1.5 * cm, 0.66 * cm, 0.16 * cm, 0.16 * cm, fill=1, stroke=0)
        canvas_obj.setFillColor(rl_colors.HexColor(GRIS_TEXTO_SEC))
        canvas_obj.setFont(FUENTE_REGULAR, 8)
        canvas_obj.drawString(1.85 * cm, 0.65 * cm, NOMBRE_ANALISTA)
        canvas_obj.drawCentredString(ancho / 2, 0.65 * cm, f"Página {doc.page}")
        canvas_obj.drawRightString(ancho - 1.5 * cm, 0.65 * cm, NOMBRE_EMPRESA)
        canvas_obj.restoreState()

    def tabla_estilo_mg(data, col_widths=None, alinear_derecha_desde=1):
        encabezado = [Paragraph(str(c), estilo_encabezado_tabla) for c in data[0]]
        data = [encabezado] + data[1:]
        tabla = Table(data, colWidths=col_widths, repeatRows=1)
        n_filas = len(data)
        estilo = [
            ("BACKGROUND", (0, 0), (-1, 0), rl_colors.HexColor(INBURSA_AZUL)),
            ("TEXTCOLOR", (0, 0), (-1, 0), rl_colors.white),
            ("FONTNAME", (0, 0), (-1, 0), FUENTE_BOLD),
            ("FONTNAME", (0, 1), (-1, -1), FUENTE_REGULAR),
            ("FONTSIZE", (0, 1), (-1, -1), 8.5),
            ("TEXTCOLOR", (0, 1), (-1, -1), rl_colors.HexColor(MG_GRIS_OSCURO)),
            ("ALIGN", (alinear_derecha_desde, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LINEBELOW", (0, 0), (-1, 0), 1.6, rl_colors.HexColor(MG_ROJO)),
            ("LINEBELOW", (0, 1), (-1, max(n_filas - 2, 1)), 0.5, rl_colors.HexColor(GRIS_LINEA)),
            ("BOX", (0, 0), (-1, -1), 0.75, rl_colors.HexColor(GRIS_LINEA)),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [rl_colors.white, rl_colors.HexColor(GRIS_ZEBRA)]),
            ("TOPPADDING", (0, 0), (-1, 0), 7),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 7),
            ("TOPPADDING", (0, 1), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]
        tabla.setStyle(TableStyle(estilo))
        return tabla

    def tarjeta_kpi(valor, etiqueta, color_acento):
        estilo_valor_acento = estilo_kpi_valor.clone("KPIValorAcento" + etiqueta[:6], textColor=rl_colors.HexColor(color_acento))
        t = Table(
            [[""], [Paragraph(str(valor), estilo_valor_acento)], [Paragraph(etiqueta, estilo_kpi_label)]],
            colWidths=[4.0 * cm], rowHeights=[0.11 * cm, None, None]
        )
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), rl_colors.HexColor(color_acento)),
            ("BACKGROUND", (0, 1), (-1, -1), rl_colors.white),
            ("BOX", (0, 0), (-1, -1), 0.75, rl_colors.HexColor(GRIS_LINEA)),
            ("TOPPADDING", (0, 1), (-1, 1), 10),
            ("BOTTOMPADDING", (0, 1), (-1, 1), 1),
            ("TOPPADDING", (0, 2), (-1, 2), 0),
            ("BOTTOMPADDING", (0, 2), (-1, 2), 10),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ]))
        return t

    # --- Datos clave para portada/KPIs ---
    total_periodo = int(tabla_comp["Total"].sum()) if "Total" in tabla_comp.columns else len(df_combinado)
    financiado_periodo = int(tabla_comp["Financiado"].sum()) if "Financiado" in tabla_comp.columns else 0
    n_meses = len(orden_meses)
    n_vendedores = int(df_combinado["Nombre del Vendedor"].nunique()) if "Nombre del Vendedor" in df_combinado.columns else 0
    conv_prom = tabla_comp["% Financiado"].mean() if "% Financiado" in tabla_comp.columns and not tabla_comp.empty else 0

    elementos = []

    # --- Portada ---
    elementos.append(Spacer(1, 0.2 * cm))
    elementos.append(Paragraph("REPORTE&nbsp;&nbsp;·&nbsp;&nbsp;COMPARATIVO MENSUAL DE BITÁCORA",
                                estilo_kicker_portada))
    elementos.append(Paragraph("Reporte Comparativo Mensual", estilo_titulo_portada))
    elementos.append(Paragraph(f"{NOMBRE_EMPRESA} · {SUBTITULO_EMPRESA}", estilo_subtitulo_portada))
    elementos.append(Spacer(1, 0.12 * cm))
    elementos.append(HRFlowable(width="100%", thickness=1, color=rl_colors.HexColor(GRIS_LINEA),
                                 spaceBefore=6, spaceAfter=10, hAlign="LEFT"))
    elementos.append(Paragraph(
        f"Periodo comparado: <b>{PERIODO_TXT}</b> &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"{n_meses} mes{'es' if n_meses != 1 else ''} &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"Generado: {FECHA_REPORTE}",
        estilo_meta_portada
    ))
    elementos.append(Spacer(1, 0.5 * cm))

    intro_portada = Table(
        [[Paragraph(
            f"Este reporte compara <b>{n_meses} mes{'es' if n_meses != 1 else ''}</b> de la bitácora "
            f"de solicitudes de crédito automotriz ({PERIODO_TXT}), con un total de "
            f"<b>{total_periodo} solicitudes</b> en el periodo. Incluye la evolución del volumen y "
            f"las categorías de cierre, la tasa "
            f"de conversión mes a mes, el panorama financiero, la colocación del seguro GAP y el "
            f"desempeño acumulado por vendedor a lo largo del periodo.",
            estilo_cuerpo
        )]],
        colWidths=[18 * cm]
    )
    intro_portada.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), rl_colors.HexColor(AZUL_PALIDO)),
        ("LINEBEFORE", (0, 0), (0, 0), 3, rl_colors.HexColor(INBURSA_AZUL)),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
    ]))
    elementos.append(intro_portada)
    elementos.append(Spacer(1, 0.45 * cm))

    _kpi_gap = ""
    fila_kpis = [
        tarjeta_kpi(total_periodo, "Total del\nPeriodo", MG_ROJO_OSCURO), _kpi_gap,
        tarjeta_kpi(financiado_periodo, "Financiadas", MG_ROJO_MEDIO), _kpi_gap,
        tarjeta_kpi(f"{conv_prom:.0f}%", "Conversión\nPromedio", MG_ROJO), _kpi_gap,
        tarjeta_kpi(n_vendedores, "Vendedores\nInvolucrados", INBURSA_AZUL),
    ]
    anchos_kpis = [4.0 * cm, 0.35 * cm, 4.0 * cm, 0.35 * cm, 4.0 * cm, 0.35 * cm, 4.0 * cm]
    tabla_kpis = Table([fila_kpis], colWidths=anchos_kpis)
    tabla_kpis.setStyle(TableStyle([("ALIGN", (0, 0), (-1, -1), "CENTER"), ("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
    elementos.append(tabla_kpis)
    elementos.append(Spacer(1, 0.5 * cm))

    # --- Resumen ejecutivo: tabla comparativa mensual ---
    elementos.append(Paragraph("Resumen Ejecutivo — Comparativo por Mes", estilo_h1))
    elementos.append(HRFlowable(width="100%", thickness=1, color=rl_colors.HexColor(MG_ROJO), spaceAfter=8))

    if not tabla_comp.empty:
        encabezados_vol = ["Mes", "Total", "Financiado", "Aprobado", "En<br/>trámite", "Rechazado", "%<br/>Financiado"]
        filas_vol = []
        for mes, fila in tabla_comp.iterrows():
            filas_vol.append([
                mes, int(fila["Total"]), int(fila["Financiado"]), int(fila["Aprobado"]),
                int(fila["En trámite"]), int(fila["Rechazado"]), f"{fila['% Financiado']:.1f}%",
            ])
        anchos_vol = [3.0 * cm] + [2.5 * cm] * 6
        elementos.append(tabla_estilo_mg([encabezados_vol] + filas_vol, col_widths=anchos_vol))
        elementos.append(Spacer(1, 0.35 * cm))

        encabezados_fin = ["Mes", "Monto Total", "Monto<br/>Financiado", "Ticket Prom.<br/>Financiado", "% GAP", "% GAP<br/>Financiado"]
        filas_fin = []
        for mes, fila in tabla_comp.iterrows():
            filas_fin.append([
                mes,
                f"${fila['Monto Total']:,.0f}" if pd.notna(fila.get('Monto Total')) else "—",
                f"${fila['Monto Financiado']:,.0f}" if pd.notna(fila.get('Monto Financiado')) else "—",
                f"${fila['Ticket Prom. Financiado']:,.0f}" if pd.notna(fila.get('Ticket Prom. Financiado')) else "—",
                f"{fila['% GAP']:.1f}%" if pd.notna(fila.get('% GAP')) else "—",
                f"{fila['% GAP Financiado']:.1f}%" if pd.notna(fila.get('% GAP Financiado')) else "—",
            ])
        anchos_fin = [2.7 * cm] + [3.2 * cm] * 5
        elementos.append(tabla_estilo_mg([encabezados_fin] + filas_fin, col_widths=anchos_fin))
    else:
        elementos.append(Paragraph("No se pudo construir la tabla comparativa mensual.", estilo_nota))
    elementos.append(Spacer(1, 0.4 * cm))

    elementos.append(Paragraph("Lectura del periodo", estilo_h2))
    for texto in insights:
        elementos.append(Paragraph("•  " + texto, estilo_cuerpo))
    elementos.append(PageBreak())

    # ===============================================================
    # REPORTE DETALLADO
    # ===============================================================
    elementos.append(Paragraph("Reporte Detallado", estilo_h1))
    elementos.append(HRFlowable(width="100%", thickness=1, color=rl_colors.HexColor(MG_ROJO), spaceAfter=8))

    if "totales_mes" in rutas_graficas:
        elementos.append(Paragraph("1. Volumen y Categorías de Cierre por Mes", estilo_h2))
        elementos.append(Paragraph(
            "La siguiente gráfica apila, para cada mes comparado, cuántas solicitudes cerraron en "
            f"cada estatus, para comparar de un "
            "vistazo tanto el volumen total como la calidad del cierre mes a mes.",
            estilo_cuerpo
        ))
        elementos.append(imagen_ajustada(rutas_graficas["totales_mes"], ancho_cm=16, alto_max_cm=11))
        elementos.append(Spacer(1, 0.4 * cm))

    if "tasa_conversion" in rutas_graficas:
        elementos.append(Paragraph("2. Tasa de Conversión por Mes", estilo_h2))
        elementos.append(Paragraph(
            "Evolución del % de solicitudes que terminaron FINANCIADAS y del % que quedó APROBADO "
            "(pendiente de dispersar) en cada mes. Una caída en el % Financiado sin caída en el % "
            "Aprobado suele indicar un problema de seguimiento a cierre más que de calidad de la "
            "solicitud entrante.",
            estilo_cuerpo
        ))
        elementos.append(imagen_ajustada(rutas_graficas["tasa_conversion"], ancho_cm=16, alto_max_cm=11))
        elementos.append(Spacer(1, 0.4 * cm))

    if "montos_mes" in rutas_graficas:
        elementos.append(Paragraph("3. Panorama Financiero por Mes", estilo_h2))
        elementos.append(Paragraph(
            "Comparación, mes a mes, del monto total a financiar de todas las solicitudes contra el "
            "monto que efectivamente se convirtió en crédito FINANCIADO (dispersado).",
            estilo_cuerpo
        ))
        elementos.append(imagen_ajustada(rutas_graficas["montos_mes"], ancho_cm=16, alto_max_cm=11))
        elementos.append(Spacer(1, 0.4 * cm))

    if "gap_mes" in rutas_graficas or "gap_vs_gap_fin_mes" in rutas_graficas or \
       "gap_categoria_mes" in rutas_graficas or \
       "gap_por_categoria" in rutas_graficas or "gap_por_vendedor" in rutas_graficas or \
       "gap_financiado_vend" in rutas_graficas:
        elementos.append(Paragraph("4. Seguro GAP", estilo_h2))
        elementos.append(Paragraph(
            "El seguro GAP cubre la diferencia entre el valor asegurado del vehículo y el saldo "
            "insoluto del crédito en caso de pérdida total, por lo que su colocación es un indicador "
            "de venta cruzada relevante. Esta sección compara su colocación entre meses y, para el "
            "periodo completo, por categoría de cierre y por vendedor.",
            estilo_cuerpo
        ))
        if "gap_mes" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["gap_mes"], ancho_cm=15, alto_max_cm=10))
            elementos.append(Spacer(1, 0.2 * cm))
        if "gap_vs_gap_fin_mes" in rutas_graficas:
            elementos.append(Paragraph(
                "La siguiente gráfica compara, mes a mes, el % de GAP sobre TODAS las solicitudes "
                "contra el % de GAP dentro de los créditos que sí llegaron a FINANCIARSE. Si la línea "
                "de GAP Financiado va por debajo de la línea general, se está colocando GAP en "
                "solicitudes que después no se dispersan; si van parejas, el GAP se está vendiendo "
                "bien justo donde más cuenta.",
                estilo_cuerpo
            ))
            elementos.append(imagen_ajustada(rutas_graficas["gap_vs_gap_fin_mes"], ancho_cm=15, alto_max_cm=10))
            elementos.append(Spacer(1, 0.2 * cm))
        if "gap_categoria_mes" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["gap_categoria_mes"], ancho_cm=16, alto_max_cm=11))
            elementos.append(Spacer(1, 0.2 * cm))
        if "gap_por_categoria" in rutas_graficas:
            elementos.append(Paragraph(
                "Colocación de GAP por categoría de cierre, sumando todos los meses comparados:",
                estilo_cuerpo
            ))
            elementos.append(imagen_ajustada(rutas_graficas["gap_por_categoria"], ancho_cm=13, alto_max_cm=10))
            elementos.append(Spacer(1, 0.2 * cm))
        if "gap_por_vendedor" in rutas_graficas:
            elementos.append(Paragraph(
                "Solicitudes con GAP por vendedor, comparadas contra el total de solicitudes de cada "
                "quien en todo el periodo:",
                estilo_cuerpo
            ))
            elementos.append(imagen_ajustada(rutas_graficas["gap_por_vendedor"], ancho_cm=16, alto_max_cm=13))
            elementos.append(Spacer(1, 0.2 * cm))
        if "gap_financiado_vend" in rutas_graficas:
            elementos.append(Paragraph(
                "Por último, la colocación de GAP dentro de los créditos ya <b>FINANCIADOS</b> "
                "en todo el periodo: es el indicador más relevante, porque ese GAP ya está vendido.",
                estilo_cuerpo
            ))
            elementos.append(imagen_ajustada(rutas_graficas["gap_financiado_vend"], ancho_cm=16, alto_max_cm=13))
        elementos.append(Spacer(1, 0.4 * cm))

    if "vendedores" in rutas_graficas or "vendedor_status" in rutas_graficas:
        elementos.append(Paragraph("5. Desempeño por Vendedor (Periodo Completo)", estilo_h2))
        elementos.append(Paragraph(
            f"Participan {n_vendedores} vendedores a lo largo de "
            f"{PERIODO_TXT}. Las siguientes gráficas muestran el total de solicitudes por vendedor y "
            f"su desglose por categoría de cierre, acumulando todos los meses comparados.",
            estilo_cuerpo
        ))
        if "vendedores" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["vendedores"], ancho_cm=16, alto_max_cm=13))
            elementos.append(Spacer(1, 0.2 * cm))
        if "vendedor_status" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["vendedor_status"], ancho_cm=16, alto_max_cm=13))
        elementos.append(Spacer(1, 0.4 * cm))

    if "modelos" in rutas_graficas:
        elementos.append(Paragraph("6. Modelos de Vehículo Más Solicitados (Periodo)", estilo_h2))
        elementos.append(Paragraph(
            "Modelos con mayor número de solicitudes sumando todos los meses comparados.",
            estilo_cuerpo
        ))
        elementos.append(imagen_ajustada(rutas_graficas["modelos"], ancho_cm=16, alto_max_cm=13))
        elementos.append(Spacer(1, 0.4 * cm))

    # ===============================================================
    # CONCLUSIONES
    # ===============================================================
    elementos.append(Paragraph("Conclusiones y Factores Importantes", estilo_h1))
    elementos.append(HRFlowable(width="100%", thickness=1, color=rl_colors.HexColor(MG_ROJO), spaceAfter=8))
    for texto in insights:
        elementos.append(Paragraph("•  " + texto, estilo_cuerpo))

    # -------------------------------------------------------------
    doc = SimpleDocTemplate(
        nombre_archivo, pagesize=letter,
        topMargin=1.8 * cm, bottomMargin=1.3 * cm, leftMargin=1.5 * cm, rightMargin=1.5 * cm
    )
    # `recolectar_elementos`: si el llamador pasa una lista, aquí se le
    # deja una copia de todos los flowables del PDF. Es lo que usa
    # docx_reportes.py para generar el Word a partir de ESTE mismo
    # contenido, en vez de volver a redactarlo por su cuenta.
    # Se copia ANTES de doc.build() porque ReportLab va vaciando la lista
    # que recibe conforme la maqueta.
    if recolectar_elementos is not None:
        try:
            from . import flowables_a_docx as _fd
        except ImportError:
            import flowables_a_docx as _fd
        recolectar_elementos.extend(_fd.capturar_guion(elementos))

    doc.build(elementos, onFirstPage=encabezado_pie_pagina, onLaterPages=encabezado_pie_pagina)

    print(f"\nReporte PDF generado: {nombre_archivo}")
    if EN_COLAB:
        files.download(nombre_archivo)
    else:
        print(f"Archivo guardado en: {nombre_archivo}")
    return nombre_archivo


# =======================================================================
# 9) FLUJO PRINCIPAL
# =======================================================================
def main(rutas_locales=None, nombres_meses=None):
    """
    rutas_locales: lista opcional de rutas a los archivos Excel a comparar
        (uno por mes). Si no se indica, en Colab se abre el selector de
        archivos (puedes elegir varios a la vez).
    nombres_meses: lista opcional (mismo orden y tamaño que rutas_locales)
        con la etiqueta de mes de cada archivo, ej. ["JULIO", "AGOSTO"].
        Si no se indica, se usa el nombre de la primera hoja de cada Excel.
    """
    archivos = cargar_multiples_archivos(rutas_locales, nombres_meses)

    datos_por_mes = {}
    for mes, df_crudo in archivos:
        df = limpiar_datos(df_crudo, mes=mes)
        resumen = resumen_general(df, mes=mes)
        tabla_vendedor = analisis_por_vendedor(df)
        tabla_categoria = analisis_financiero_por_categoria(df)
        datos_por_mes[mes] = {
            "df": df, "resumen": resumen,
            "tabla_vendedor": tabla_vendedor, "tabla_categoria": tabla_categoria,
        }

    orden_meses = sorted(datos_por_mes.keys(), key=lambda m: (_orden_mes(m), list(datos_por_mes.keys()).index(m)))

    tabla_comp = construir_tabla_comparativa(datos_por_mes, orden_meses)
    print("=" * 72)
    print(" TABLA COMPARATIVA MENSUAL")
    print("=" * 72)
    display(tabla_comp)
    print()

    df_combinado = pd.concat([datos_por_mes[m]["df"] for m in orden_meses], ignore_index=True)

    generar_reporte_pdf_comparativo(datos_por_mes, orden_meses, tabla_comp, df_combinado)

    print("=" * 72)
    print(" Reporte comparativo completo. Se generó un PDF con la tabla mensual,")
    print(" gráficas comparativas de volumen, conversión, panorama financiero y")
    print(" GAP, desempeño acumulado por vendedor, y una sección de insights")
    print(" automáticos con la lectura del periodo.")
    print("=" * 72)

    return datos_por_mes, tabla_comp


if __name__ == "__main__":
    main()