# -*- coding: utf-8 -*-
"""
BASE COMPARTIDA DE LOS REPORTES DE BITÁCORA

===========================================================================
 ¿POR QUÉ EXISTE ESTE ARCHIVO?
===========================================================================
El avance preliminar y el resumen mensual eran dos archivos de ~1,900 líneas
cada uno... con el 90% del contenido idéntico: 28 de sus 29 funciones hacían
exactamente lo mismo (las pocas diferencias eran comentarios y textos de
consola, no comportamiento).

Eso significaba que cada arreglo había que aplicarlo dos veces, y en la
práctica varias veces se aplicó solo en uno: la tabla que partía palabras a
la mitad, la gráfica de GAP con la escala fija en 120%, las leyendas
amontonadas. El reporte mensual quedaba "peor" que el otro sin razón
aparente.

Ahora esa lógica común vive AQUÍ, una sola vez:

  · carga y limpieza del Excel de la bitácora
  · clasificación de estatus (delegada a estatus.py)
  · cálculos: resumen general, tabla por vendedor, comparativo financiero
  · las 10 gráficas y la paleta de marca
  · imagen_ajustada(), el helper que mete los PNG en el PDF

Cada reporte conserva solo lo que de verdad lo distingue: su portada, su
narrativa, el orden de sus secciones y sus conclusiones.

===========================================================================
 REGLA PARA MANTENERLO
===========================================================================
Si un arreglo aplica "a los dos reportes", va aquí. Si al corregir algo te
descubres copiando el mismo bloque a otro archivo, ese bloque pertenece a
este módulo.

Después de tocar este archivo corre SIEMPRE las pruebas: cubren los tres
reportes de punta a punta y tardan medio minuto.

    python -m pytest
"""

# -*- coding: utf-8 -*-
"""Avance Preeliminar_ Mensual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jItHiZ1MSX7fvzh7RRDEAAsEdva8rUMw
"""

# -*- coding: utf-8 -*-

import warnings
warnings.filterwarnings("ignore")

import os
import calendar
import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib.colors import LinearSegmentedColormap, to_rgb

try:
    from google.colab import files  # noqa
    EN_COLAB = True
except ImportError:
    EN_COLAB = False

try:
    from IPython.display import display
except ImportError:
    display = print

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)

# Librería para generar el PDF (se instala si no está disponible en el entorno)
# reportlab va fijado en requirements.txt; ya no se instala en tiempo de
# ejecución (eso era herencia de Colab y en un servidor puede colgarse).
import reportlab  # noqa: F401

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import cm
from reportlab.lib import colors as rl_colors
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image,
    PageBreak, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY


# =======================================================================
# 1) PALETA DE COLORES — ROJOS MG + AZUL INBURSA (misma paleta de marca
#    del script original; se agregan tonos neutros para el rediseño
#    "corporativo moderno": grises fríos para texto/reglas secundarias
#    y un azul muy pálido para acentos discretos de tabla)
# =======================================================================
MG_ROJO          = "#E4002B"   # rojo principal de marca
MG_ROJO_OSCURO   = "#7A0019"
INBURSA_AZUL     = "#191970"
MG_ROJO_MEDIO    = "#B3001B"
MG_ROJO_CLARO    = "#FF6B6B"
MG_ROJO_PASTEL   = "#FFB3B3"
MG_ROJO_PALIDO   = "#FBE7E9"   # fondo muy claro — usado con moderación en acentos
MG_GRIS_OSCURO   = "#2B2B2B"
MG_GRIS_CLARO    = "#EAEAEA"
BLANCO           = "#FFFFFF"

# --- Tonos neutros nuevos, propios del rediseño corporativo/moderno ---
GRIS_TEXTO_SEC   = "#6B7280"   # texto secundario (labels, notas, pie)
GRIS_LINEA       = "#E3E5E9"   # reglas y bordes discretos
GRIS_ZEBRA       = "#F6F7F9"   # fondo de fila alterna en tablas (casi blanco)
AZUL_PALIDO      = "#EEF0F8"   # fondo muy sutil para acentos en azul Inbursa

# gradiente de rojos usado en la mayoría de las gráficas (oscuro -> claro)
PALETA_ROJOS = ["#7A0019", "#9E001F", "#C10024", "#E4002B",
                 "#F1354D", "#FF6B6B", "#FF9B9B", "#FFC7C7"]

_CMAP_ROJOS = LinearSegmentedColormap.from_list("rojos_mg", PALETA_ROJOS)


# =======================================================================
# 1B) FUENTE (TIPOGRAFÍA) DEL REPORTE — para cambiarla, edita SOLO la
#     línea de FUENTE_BASE. Todo el PDF (títulos, tablas, tarjetas KPI,
#     encabezado y pie de página) la toma de aquí, así que ya no hay que
#     buscar "Helvetica" por todo el archivo cada vez que se quiera
#     cambiar la tipografía.
#     Opciones ya listas, sin instalar nada extra:
#       "Helvetica"  -> paloseco (la que traía el reporte original)
#       "Times"      -> con serifas, look más editorial/formal
#       "Courier"    -> monoespaciada
#     Si más adelante quieres una fuente propia de la marca (un .ttf),
#     regístrala con pdfmetrics.registerFont(TTFont(...)) y agrega su
#     nombre a _FUENTES_DISPONIBLES.
# =======================================================================
FUENTE_BASE = "Helvetica"   # <-- CAMBIA AQUÍ LA FUENTE DE TODO EL PDF

_FUENTES_DISPONIBLES = {
    "Helvetica": {"regular": "Helvetica",   "bold": "Helvetica-Bold",
                  "italica": "Helvetica-Oblique", "bold_italica": "Helvetica-BoldOblique"},
    "Times":     {"regular": "Times-Roman", "bold": "Times-Bold",
                  "italica": "Times-Italic",      "bold_italica": "Times-BoldItalic"},
    "Courier":   {"regular": "Courier",     "bold": "Courier-Bold",
                  "italica": "Courier-Oblique",    "bold_italica": "Courier-BoldOblique"},
}
_fuente_activa = _FUENTES_DISPONIBLES.get(FUENTE_BASE, _FUENTES_DISPONIBLES["Helvetica"])
FUENTE_REGULAR      = _fuente_activa["regular"]
FUENTE_BOLD         = _fuente_activa["bold"]
FUENTE_ITALICA      = _fuente_activa["italica"]
FUENTE_BOLD_ITALICA = _fuente_activa["bold_italica"]


# =======================================================================
# CATÁLOGO DE ESTATUS
# Los colores, el orden y las etiquetas de cada categoría ya NO viven aquí:
# están en herramientas/estatus.py, que es la fuente única de verdad para
# los tres reportes. Para agregar un estatus nuevo, edita ESE archivo.
#
# ORDEN_CATEGORIAS y COLOR_CATEGORIA se siguen usando igual que antes en
# todo este script; solo que ahora se importan (son los mismos objetos
# compartidos, así que si la bitácora trae un estatus no catalogado,
# registrar_categorias() lo agrega y aparece aquí automáticamente).
# =======================================================================
try:
    from . import estatus as _est
except ImportError:  # ejecución suelta (Colab, o el .py fuera del paquete)
    import estatus as _est

ORDEN_CATEGORIAS = _est.ORDEN_CATEGORIAS
COLOR_CATEGORIA = _est.COLOR_CATEGORIA

NOMBRE_EMPRESA = "AUTOEXPRESS INBURSA"
SUBTITULO_EMPRESA = "MG Colima PYD"
NOMBRE_ANALISTA = "Christian Ramos"

_MESES_ES = ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio",
             "agosto", "septiembre", "octubre", "noviembre", "diciembre"]


__all__ = [
    "filas_tabla_vendedor", "recortar_nombre",
    "secciones_detalladas",
    "crear_estilos",
    "crear_maquetadores",
    "CARPETA_GRAFICAS",
    "COLUMNAS_ESPERADAS",
    "COLUMNAS_MONEDA",
    "COLUMNAS_PORCENTAJE",
    "EN_COLAB",
    "STATUS_APROBADO",
    "STATUS_FINANCIADO",
    "STATUS_RECHAZADOS",
    "TA_CENTER",
    "TA_JUSTIFY",
    "TA_LEFT",
    "TA_RIGHT",
    "AZUL_PALIDO",
    "BLANCO",
    "COLOR_CATEGORIA",
    "FUENTE_BASE",
    "FUENTE_BOLD",
    "FUENTE_BOLD_ITALICA",
    "FUENTE_ITALICA",
    "FUENTE_REGULAR",
    "GRIS_LINEA",
    "GRIS_TEXTO_SEC",
    "GRIS_ZEBRA",
    "INBURSA_AZUL",
    "MG_GRIS_CLARO",
    "MG_GRIS_OSCURO",
    "MG_ROJO",
    "MG_ROJO_CLARO",
    "MG_ROJO_MEDIO",
    "MG_ROJO_OSCURO",
    "MG_ROJO_PALIDO",
    "MG_ROJO_PASTEL",
    "NOMBRE_ANALISTA",
    "NOMBRE_EMPRESA",
    "ORDEN_CATEGORIAS",
    "PALETA_ROJOS",
    "SUBTITULO_EMPRESA",
    "_CMAP_ROJOS",
    "_FUENTES_DISPONIBLES",
    "_MESES_ES",
    "_limpiar_moneda",
    "_limpiar_porcentaje",
    "_formato_miles",
    "_gradiente",
    "_color_texto_legible",
    "_guardar_si_procede",
    "_nombres_y",
    "_quienes_maximo",
    "_lista_vendedores_por_categoria",
    "cargar_archivo",
    "clasificar_status",
    "limpiar_datos",
    "contexto_de_corte",
    "resumen_general",
    "analisis_por_vendedor",
    "analisis_financiero_por_categoria",
    "grafica_status",
    "grafica_dona_categoria",
    "grafica_vendedores",
    "grafica_vendedor_status",
    "grafica_monto_por_vendedor",
    "grafica_modelos",
    "grafica_gap_por_categoria",
    "grafica_gap_por_vendedor_total",
    "grafica_gap_por_vendedor_y_status",
    "grafica_gap_financiado_por_vendedor",
    "generar_todas_las_graficas",
    "generar_graficas_para_pdf",
    "imagen_ajustada",
]


def _limpiar_moneda(serie):
    return (
        serie.astype(str)
             .str.replace(r"[\$,]", "", regex=True)
             .str.strip()
             .replace({"nan": np.nan, "": np.nan, "None": np.nan})
             .astype(float)
    )

def _limpiar_porcentaje(serie):
    """Convierte la columna de tasa de interés a número (ej. "14.99%" -> 14.99).

    OJO — esto es lo que estaba descuadrando la tasa de FINANCIADOS:
    en Excel una celda puede guardar "14.99%" como TEXTO, o como NÚMERO
    con formato de celda "0.00%" (en ese caso Excel guarda por dentro la
    fracción 0.1499, sin el símbolo %). Si sólo se le quita el "%" al
    texto, esas celdas numéricas se quedan en 0.1499 en vez de 14.99 y
    arruinan cualquier promedio. Por eso aquí se revisa el valor
    ORIGINAL de cada celda (no su versión ya convertida a texto) y, si
    es un número <= 1, se asume que viene en formato fracción de Excel
    y se multiplica x100.
    """
    def _convertir(valor):
        if pd.isna(valor):
            return np.nan
        if isinstance(valor, str):
            texto = valor.strip().replace("%", "")
            if texto in ("", "nan", "None"):
                return np.nan
            try:
                return float(texto)
            except ValueError:
                return np.nan
        try:
            numero = float(valor)
        except (TypeError, ValueError):
            return np.nan
        return numero * 100 if numero <= 1 else numero

    return serie.apply(_convertir)

def _formato_miles(ax, eje="y"):
    formatter = mticker.FuncFormatter(lambda x, _: f"{x:,.0f}")
    if eje == "y":
        ax.yaxis.set_major_formatter(formatter)
    else:
        ax.xaxis.set_major_formatter(formatter)

def _gradiente(n):
    """Genera n colores en degradado continuo (oscuro -> claro) sin repetirse,
    sin importar cuántas barras haya."""
    if n <= 1:
        return [MG_ROJO]
    valores = np.linspace(0.0, 0.82, n)
    return [_CMAP_ROJOS(v) for v in valores]

def _color_texto_legible(color_fondo):
    """Devuelve blanco o gris oscuro según qué tan claro sea el color de fondo,
    para que el texto siempre se pueda leer."""
    r, g, b = to_rgb(color_fondo)
    luminancia = 0.299 * r + 0.587 * g + 0.114 * b
    return "white" if luminancia < 0.6 else MG_GRIS_OSCURO


plt.rcParams.update({
    "figure.facecolor":  "white",
    "axes.facecolor":    "white",
    "axes.edgecolor":    GRIS_LINEA,
    "axes.labelcolor":   GRIS_TEXTO_SEC,
    "text.color":        MG_GRIS_OSCURO,
    "xtick.color":       GRIS_TEXTO_SEC,
    "ytick.color":       GRIS_TEXTO_SEC,
    "font.size":         10,
    "axes.titlesize":    12.5,
    "axes.titleweight":  "bold",
    "axes.titlecolor":   MG_GRIS_OSCURO,
    "axes.titlepad":     14,
    "axes.labelsize":    9.5,
    "axes.linewidth":    0.8,
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "axes.spines.left":  True,
    "axes.grid":         False,
    "xtick.labelsize":   9,
    "ytick.labelsize":   9,
    "legend.fontsize":   9,
    "legend.frameon":    False,
})

# Carpeta temporal para las imágenes de las gráficas que se insertarán en el PDF
CARPETA_GRAFICAS = "graficas_temp_bitacora"
os.makedirs(CARPETA_GRAFICAS, exist_ok=True)


# =======================================================================
# 2) CARGA DEL ARCHIVO
# =======================================================================

def _guardar_si_procede(fig, guardar_como):
    if guardar_como:
        # La carpeta de gráficas se creaba UNA sola vez, al importar el
        # módulo. En un proceso de larga vida (Streamlit) eso no basta: si
        # algo la borra entre corridas —por ejemplo la limpieza de temporales
        # de la app— la siguiente corrida truena con "No such file or
        # directory", o peor, se queda sin gráficas en silencio. Asegurarla
        # aquí la vuelve a crear cuando haga falta.
        carpeta = os.path.dirname(guardar_como)
        if carpeta:
            os.makedirs(carpeta, exist_ok=True)
        fig.savefig(guardar_como, dpi=150, bbox_inches="tight", facecolor="white")
    return guardar_como

def _nombres_y(nombres):
    """Une una lista de nombres en texto natural: 'A', 'A y B', 'A, B y C'."""
    nombres = [str(n) for n in nombres]
    if not nombres:
        return ""
    if len(nombres) == 1:
        return nombres[0]
    return ", ".join(nombres[:-1]) + " y " + nombres[-1]

def _quienes_maximo(serie):
    """Devuelve (lista_de_nombres, valor_maximo) para una Series indexada por
    vendedor. Si hay empate en el máximo, regresa a TODOS los empatados.
    Si la serie está vacía o el máximo es 0/():  regresa ([], 0)."""
    if serie is None or serie.empty:
        return [], 0
    maximo = serie.max()
    if pd.isna(maximo) or maximo <= 0:
        return [], 0
    nombres = serie[serie == maximo].index.tolist()
    return nombres, maximo

def _lista_vendedores_por_categoria(df, categoria, max_nombres=4):
    """Devuelve un string compacto con los primeros nombres de los
    vendedores que tienen solicitudes en esa categoría (para no saturar
    la leyenda con nombres completos)."""
    nombres = (
        df.loc[df["Categoria"] == categoria, "Nombre del Vendedor"]
        .dropna().unique().tolist()
    )
    primeros_nombres = sorted({n.split()[0] for n in nombres if n and n != "Nan"})
    if not primeros_nombres:
        return "—"
    if len(primeros_nombres) > max_nombres:
        extra = len(primeros_nombres) - max_nombres
        return ", ".join(primeros_nombres[:max_nombres]) + f" +{extra} más"
    return ", ".join(primeros_nombres)

def cargar_archivo(ruta_local=None):
    """
    Sube (en Colab) o abre (fuera de Colab) el archivo Excel de la
    bitácora y devuelve un DataFrame de pandas con la hoja elegida.
    """
    if ruta_local:
        nombre_archivo = ruta_local
    elif EN_COLAB:
        print("Sube el archivo Excel de la bitácora de solicitudes...")
        subido = files.upload()
        nombre_archivo = list(subido.keys())[0]
    else:
        nombre_archivo = input("Ruta del archivo Excel: ").strip()

    xls = pd.ExcelFile(nombre_archivo)
    hoja = xls.sheet_names[0]
    if len(xls.sheet_names) > 1:
        print(f"El archivo tiene varias hojas: {xls.sheet_names}")
        elegida = input(f"¿Cuál analizar? (Enter = '{hoja}'): ").strip()
        hoja = elegida if elegida else hoja

    df = pd.read_excel(nombre_archivo, sheet_name=hoja)
    print(f"Archivo cargado: {nombre_archivo}  |  Hoja: {hoja}  |  {len(df)} solicitudes\n")
    return df


# =======================================================================
# 3) LIMPIEZA Y NORMALIZACIÓN DE DATOS
# =======================================================================
COLUMNAS_ESPERADAS = [
    "Folio CCK", "STATUS", "Nombre Completo", "Fecha de Nacimiento",
    "Teléfono Móvil", "Correo Electrónico", "Nombre del Vendedor",
    "Marca", "Vehículo", "Año Modelo", "Precio Venta (c/IVA)",
    "Enganche", "¿Tiene GAP?", "Monto GAP", "Plazo (meses)",
    "Tasa Interés Anual", "Monto Total a Financiar",
    "Mensualidad Mínima", "Mensualidad Máxima",
]

COLUMNAS_MONEDA = [
    "Precio Venta (c/IVA)", "Enganche", "Monto GAP",
    "Monto Total a Financiar", "Mensualidad Mínima", "Mensualidad Máxima",
]

COLUMNAS_PORCENTAJE = ["Tasa Interés Anual"]

# Los sinónimos de cada estatus (APROBADO/APROBADOS/AUTORIZADO, etc.) están
# definidos en herramientas/estatus.py. Se re-exportan aquí solo por si algún
# código viejo los importaba de este módulo.
STATUS_APROBADO   = _est.STATUS_APROBADO
STATUS_FINANCIADO = _est.STATUS_FINANCIADO
STATUS_RECHAZADOS = _est.STATUS_RECHAZADOS

def clasificar_status(status):
    """Traduce el STATUS crudo del Excel a su categoría.

    Un estatus que no esté en el catálogo YA NO se mete a la fuerza en
    "CONTRAPROPUESTA" (que era lo que inflaba esa categoría): se respeta
    como categoría propia. Ver herramientas/estatus.py.
    """
    return _est.clasificar_status(status)

def limpiar_datos(df_original):
    df = df_original.copy()
    df.columns = [str(c).strip() for c in df.columns]

    faltantes = [c for c in COLUMNAS_ESPERADAS if c not in df.columns]
    if faltantes:
        print(f"Aviso: no se encontraron estas columnas esperadas: {faltantes}")
        print("El script seguirá, pero los análisis que dependan de ellas se omitirán.\n")

    for col in COLUMNAS_MONEDA:
        if col in df.columns:
            df[col] = _limpiar_moneda(df[col])

    for col in COLUMNAS_PORCENTAJE:
        if col in df.columns:
            crudo = df[col]
            df[col] = _limpiar_porcentaje(crudo)
            # Aviso de calidad de datos: celdas numéricas guardadas con
            # formato de porcentaje de Excel (fracción, ej. 0.1499) en vez
            # de texto "14.99%". El script ya las corrige automáticamente,
            # pero conviene saber cuáles filas venían así en el archivo fuente.
            es_formato_distinto = crudo.apply(
                lambda v: not isinstance(v, str) and pd.notna(v) and float(v) <= 1
            )
            if es_formato_distinto.any():
                idx = crudo[es_formato_distinto].index
                folios = (
                    df.loc[idx, "Folio CCK"].tolist() if "Folio CCK" in df.columns else list(idx)
                )
                print(
                    f"Aviso: {len(folios)} fila(s) en '{col}' tenían formato de celda "
                    f"distinto (número en vez de texto, ej. 0.1499 en vez de \"14.99%\") "
                    f"y se corrigieron automáticamente. Folios: {folios}"
                )

    if "STATUS" in df.columns:
        df["STATUS"] = df["STATUS"].astype(str).str.strip().str.upper()
        df["Categoria"] = df["STATUS"].apply(clasificar_status)
        # Da de alta (con color y lugar en el orden) cualquier estatus que
        # venga en la bitácora y no esté en el catálogo, para que no se
        # quede fuera de las gráficas que recorren ORDEN_CATEGORIAS.
        _est.registrar_categorias(df["Categoria"].unique())

    if "Nombre del Vendedor" in df.columns:
        df["Nombre del Vendedor"] = (
            df["Nombre del Vendedor"].astype(str).str.strip().str.title()
        )

    if "Marca" in df.columns:
        df["Marca"] = df["Marca"].astype(str).str.strip().str.upper().replace("NAN", np.nan)

    if "Vehículo" in df.columns:
        df["Vehículo"] = df["Vehículo"].astype(str).str.strip().replace("None", np.nan)

    if "Fecha de Nacimiento" in df.columns:
        df["Fecha de Nacimiento"] = pd.to_datetime(
            df["Fecha de Nacimiento"], dayfirst=True, errors="coerce"
        )
        hoy = pd.Timestamp.today()
        df["Edad"] = ((hoy - df["Fecha de Nacimiento"]).dt.days // 365.25)

    if "¿Tiene GAP?" in df.columns:
        df["¿Tiene GAP?"] = df["¿Tiene GAP?"].astype(str).str.strip().str.upper()

    return df


# =======================================================================
# 4) CÁLCULOS — RESUMEN GENERAL / KPIs DEL PERIODO
#    (imprime en consola igual que antes, y además devuelve un
#    diccionario con los datos clave para redactar el reporte narrativo)
# =======================================================================

def contexto_de_corte(fecha_corte=None):
    """
    Ubica la fecha de corte del avance dentro del calendario del mes:
    en qué día se está cortando, cuántos días tiene el mes y qué % del
    mes ya transcurrió. Es solo contexto de calendario -no una meta ni
    una proyección de cierre-, para que el reporte deje claro qué tan
    "preliminares" son los resultados que muestra.

    Si no se indica fecha_corte, usa la fecha de hoy. También acepta un
    string ("15/08/2026") o un date/datetime ya construido.
    """
    if fecha_corte is None:
        fecha_corte = datetime.date.today()
    elif isinstance(fecha_corte, str):
        fecha_corte = pd.to_datetime(fecha_corte, dayfirst=True).date()
    elif isinstance(fecha_corte, datetime.datetime):
        fecha_corte = fecha_corte.date()

    dias_en_mes = calendar.monthrange(fecha_corte.year, fecha_corte.month)[1]
    dia_actual = fecha_corte.day
    dias_restantes = dias_en_mes - dia_actual

    return {
        "fecha_corte": fecha_corte,
        "nombre_mes": _MESES_ES[fecha_corte.month - 1],
        "dia_actual": dia_actual,
        "dias_en_mes": dias_en_mes,
        "pct_transcurrido": dia_actual / dias_en_mes * 100,
        "dias_restantes": dias_restantes,
    }

def resumen_general(df):
    print("=" * 72)
    print(" RESUMEN GENERAL DEL PERIODO")
    print("=" * 72)

    total = len(df)
    r = {"total": total}
    print(f"Total de solicitudes ingresadas: {total}\n")

    if "Categoria" in df.columns:
        conteo_cat = df["Categoria"].value_counts()

        # Conteo de TODAS las categorías presentes, no solo de las cuatro
        # que antes estaban escritas a mano.
        conteo_categorias = {
            c: int(conteo_cat.get(c, 0)) for c in _est.categorias_presentes(df)
        }

        financiados = int(conteo_cat.get("FINANCIADO", 0))
        aprobados   = int(conteo_cat.get("APROBADO", 0))
        rechazados  = int(conteo_cat.get("RECHAZADO", 0))

        # "en_tramite" = todo lo que sigue vivo y todavía puede convertirse
        # en financiado, EXCEPTO lo ya aprobado (que se reporta aparte):
        # contrapropuesta, en proceso, en revisión, pendiente, etc.
        claves_abiertas = [c for c in _est.claves_por_grupo(_est.ABIERTA)
                           if c != "APROBADO"]
        en_tramite = sum(int(conteo_cat.get(c, 0)) for c in claves_abiertas)

        for clave, cnt in conteo_categorias.items():
            print(f"  {_est.etiqueta(clave):<24}: {cnt:>3}  ({cnt/total*100:5.1f}%)")

        print("\nDesglose detallado por ESTATUS (texto tal cual del Excel):")
        for status, cnt in df["STATUS"].value_counts().items():
            print(f"    - {status:<20}: {cnt:>3}  ({cnt/total*100:5.1f}%) ")

        r.update({
            "financiados": financiados, "aprobados": aprobados,
            "rechazados": rechazados, "en_tramite": en_tramite,
            "conteo_categorias": conteo_categorias,
            "claves_abiertas": claves_abiertas,
            "desglose_status": df["STATUS"].value_counts(),
        })
    else:
        financiados = aprobados = rechazados = en_tramite = 0

    monto_col = "Monto Total a Financiar"
    if monto_col in df.columns:
        monto_total = df[monto_col].sum()
        r["monto_total"] = monto_total
        print(f"\nMonto total a financiar (TODAS las solicitudes)  : ${monto_total:,.2f}")

        if "Categoria" in df.columns:
            monto_financiado = df.loc[df["Categoria"] == "FINANCIADO", monto_col].sum()
            monto_aprobado   = df.loc[df["Categoria"] == "APROBADO", monto_col].sum()
            r["monto_financiado"] = monto_financiado
            r["monto_aprobado"] = monto_aprobado

            print(f"Monto FINANCIADO (crédito ya dispersado)          : ${monto_financiado:,.2f}")
            if financiados:
                ticket_financiado = df.loc[df["Categoria"] == "FINANCIADO", monto_col].mean()
                r["ticket_financiado"] = ticket_financiado
                print(f"  Ticket promedio financiadas                     : ${ticket_financiado:,.2f}")

            print(f"Monto APROBADO (aún sin dispersar)                : ${monto_aprobado:,.2f}")
            if aprobados:
                ticket_aprobado = df.loc[df["Categoria"] == "APROBADO", monto_col].mean()
                r["ticket_aprobado"] = ticket_aprobado
                print(f"  Ticket promedio aprobadas                       : ${ticket_aprobado:,.2f}")

            print(f"Monto conjunto (Aprobado + Financiado)            : ${monto_financiado + monto_aprobado:,.2f}")

    if "Enganche" in df.columns and "Precio Venta (c/IVA)" in df.columns:
        pct_enganche = (df["Enganche"] / df["Precio Venta (c/IVA)"] * 100).mean()
        r["pct_enganche"] = pct_enganche
        print(f"\n% de enganche promedio sobre precio de venta      : {pct_enganche:.1f}%")

    if "Plazo (meses)" in df.columns:
        r["plazo_promedio"] = df["Plazo (meses)"].mean()
        print(f"Plazo promedio solicitado                         : {df['Plazo (meses)'].mean():.0f} meses")

    if "Tasa Interés Anual" in df.columns:
        r["tasa_promedio"] = df["Tasa Interés Anual"].mean()
        print(f"Tasa de interés anual promedio                    : {df['Tasa Interés Anual'].mean():.2f}%")

    if "¿Tiene GAP?" in df.columns:
        pct_gap = (df["¿Tiene GAP?"] == "SI").mean() * 100
        r["pct_gap"] = pct_gap
        r["n_gap"] = int((df["¿Tiene GAP?"] == "SI").sum())
        print(f"% de solicitudes con GAP                          : {pct_gap:.1f}%")

    if "Edad" in df.columns and df["Edad"].notna().any():
        r["edad_promedio"] = df["Edad"].mean()

    # filas con datos incompletos (p.ej. folio sin vehículo asignado aún)
    cols_clave = [c for c in ["Marca", "Vehículo", "Monto Total a Financiar"] if c in df.columns]
    if cols_clave:
        incompletas = df[cols_clave].isna().any(axis=1).sum()
        r["incompletas"] = int(incompletas)
        if incompletas:
            print(f"\nSolicitudes con datos incompletos (vehículo/monto sin capturar): {incompletas}")

    print()
    return r


# =======================================================================
# 5) CÁLCULOS — ANÁLISIS POR VENDEDOR
# =======================================================================

def recortar_nombre(nombre, maximo=22):
    """Acorta un nombre largo para que no descuadre una tabla.

    Conserva el nombre de pila y abrevia los apellidos, en vez de cortar a
    lo bruto: "Luis Valentin Salvidar De La Mora" queda como
    "Luis Valentin S. D. L. M." y sigue siendo identificable.
    """
    nombre = str(nombre)
    if len(nombre) <= maximo:
        return nombre
    partes = nombre.split()
    if len(partes) <= 2:
        return nombre[:maximo - 1] + "…"
    resultado = " ".join(partes[:2] + [f"{p[0]}." for p in partes[2:]])
    return resultado if len(resultado) <= maximo else resultado[:maximo - 1] + "…"


def filas_tabla_vendedor(tabla_vendedor):
    """Arma las filas de la tabla por vendedor para el PDF.

    Vive aquí y no en cada reporte porque el Avance Preliminar y el Resumen
    Mensual comparten esta maquinaria: una sola definición evita que las dos
    tablas se vayan separando con el tiempo.

    Las columnas se incluyen solo si existen, porque no todas las bitácoras
    traen monto ni GAP. El % de GAP se calcula sobre créditos FINANCIADOS
    —el GAP efectivamente vendido— y no sobre todas las solicitudes.
    """
    if tabla_vendedor is None or tabla_vendedor.empty:
        return None, None, None

    hay_monto = "Monto Financiado ($)" in tabla_vendedor.columns
    hay_gap = "GAP Financiado" in tabla_vendedor.columns

    # Encabezado y ancho van juntos: repartir 16 cm por igual dejaba las
    # columnas tan angostas que "Solicitudes" se partía como "Solicitude s".
    # Cada encabezado lleva su salto de línea explícito y su ancho medido.
    cabecera = ["Vendedor", "Solicitudes", "Créditos<br/>financiados",
                "%<br/>Financiado"]
    anchos = [3.6, 2.2, 2.3, 2.2]
    if hay_monto:
        cabecera.append("Monto<br/>financiado")
        anchos.append(2.7)
    if hay_gap:
        cabecera += ["GAP en<br/>financiados", "%<br/>GAP"]
        anchos += [2.3, 1.4]

    filas = [cabecera]
    for vendedor, fila in tabla_vendedor.iterrows():
        financiado = int(fila.get("FINANCIADO", 0))
        celdas = [
            recortar_nombre(vendedor),
            str(int(fila["Total"])),
            str(financiado),
            f"{fila.get('% Financiado', 0):.1f}%",
        ]
        if hay_monto:
            celdas.append(f"${fila['Monto Financiado ($)']:,.0f}")
        if hay_gap:
            gap_fin = int(fila["GAP Financiado"])
            celdas.append(str(gap_fin))
            # Sin créditos financiados el porcentaje no existe: se marca con
            # una raya en vez de un 0% que se leería como mal desempeño.
            celdas.append(f"{gap_fin / financiado * 100:.0f}%" if financiado else "—")
        filas.append(celdas)

    total_sol = int(tabla_vendedor["Total"].sum())
    total_fin = int(tabla_vendedor["FINANCIADO"].sum()) if "FINANCIADO" in tabla_vendedor else 0
    totales = ["TOTAL EQUIPO", str(total_sol), str(total_fin),
               f"{total_fin / total_sol * 100:.1f}%" if total_sol else "—"]
    if hay_monto:
        totales.append(f"${tabla_vendedor['Monto Financiado ($)'].sum():,.0f}")
    if hay_gap:
        total_gap = int(tabla_vendedor["GAP Financiado"].sum())
        totales.append(str(total_gap))
        totales.append(f"{total_gap / total_fin * 100:.0f}%" if total_fin else "—")
    filas.append(totales)

    nota = ("El % de GAP se calcula sobre créditos FINANCIADOS: es el GAP "
            "efectivamente vendido." if hay_gap else None)

    # Si sobran columnas, el ancho restante se le da al nombre, que es el que
    # más lo aprovecha.
    anchos[0] += max(0.0, 16.0 - sum(anchos))
    return filas, nota, anchos


def analisis_por_vendedor(df):
    if "Nombre del Vendedor" not in df.columns:
        return None

    print("=" * 72)
    print(" ANÁLISIS POR VENDEDOR")
    print("=" * 72)

    total_por_vendedor = df.groupby("Nombre del Vendedor").size().rename("Total")

    tabla = pd.DataFrame({"Total": total_por_vendedor})

    if "Categoria" in df.columns:
        pivote = pd.crosstab(df["Nombre del Vendedor"], df["Categoria"])
        # Solo las categorías que realmente aparecen este mes: así la tabla
        # no se llena de columnas en cero cuando el catálogo tiene muchos
        # estatus posibles.
        presentes = _est.categorias_presentes(df)
        for col in presentes:
            if col not in pivote.columns:
                pivote[col] = 0
        tabla = tabla.join(pivote[presentes])
        # Si un mes no hubo ninguna APROBADA (o ninguna FINANCIADA), esa
        # columna no existe: se toma como 0 en vez de tronar.
        aprobado_v = tabla["APROBADO"] if "APROBADO" in tabla.columns else 0
        financiado_v = tabla["FINANCIADO"] if "FINANCIADO" in tabla.columns else 0
        tabla["% Aprobación"] = (aprobado_v / tabla["Total"] * 100).round(1)
        tabla["% Financiado"] = (financiado_v / tabla["Total"] * 100).round(1)

    if "Monto Total a Financiar" in df.columns and "Categoria" in df.columns:
        monto_financiado = (
            df[df["Categoria"] == "FINANCIADO"]
            .groupby("Nombre del Vendedor")["Monto Total a Financiar"]
            .sum()
            .rename("Monto Financiado ($)")
        )
        monto_aprobado = (
            df[df["Categoria"] == "APROBADO"]
            .groupby("Nombre del Vendedor")["Monto Total a Financiar"]
            .sum()
            .rename("Monto Aprobado ($)")
        )
        tabla = tabla.join(monto_financiado).join(monto_aprobado)
        tabla[["Monto Financiado ($)", "Monto Aprobado ($)"]] = tabla[
            ["Monto Financiado ($)", "Monto Aprobado ($)"]
        ].fillna(0)

    if "¿Tiene GAP?" in df.columns:
        gap_total_v = df[df["¿Tiene GAP?"] == "SI"].groupby("Nombre del Vendedor").size()
        tabla["GAP Total"] = gap_total_v.reindex(tabla.index).fillna(0).astype(int)
        if "Categoria" in df.columns:
            gap_fin_v = (
                df[(df["Categoria"] == "FINANCIADO") & (df["¿Tiene GAP?"] == "SI")]
                .groupby("Nombre del Vendedor").size()
            )
            tabla["GAP Financiado"] = gap_fin_v.reindex(tabla.index).fillna(0).astype(int)

    tabla = tabla.sort_values("Total", ascending=False)
    display(tabla)
    print()
    return tabla


# =======================================================================
# 6) CÁLCULOS — ANÁLISIS FINANCIERO COMPARATIVO POR CATEGORÍA
# =======================================================================

def analisis_financiero_por_categoria(df):
    if "Categoria" not in df.columns:
        return None

    print("=" * 72)
    print(" COMPARATIVO FINANCIERO POR CATEGORÍA: "
          + " vs ".join(_est.categorias_presentes(df)))
    print("=" * 72)

    columnas_interes = [c for c in [
        "Precio Venta (c/IVA)", "Enganche", "Monto Total a Financiar",
        "Plazo (meses)", "Tasa Interés Anual",
    ] if c in df.columns]

    if not columnas_interes:
        return None

    tabla = df.groupby("Categoria")[columnas_interes].mean().round(2)
    orden_presente = [c for c in ORDEN_CATEGORIAS if c in tabla.index]
    tabla = tabla.reindex(orden_presente)

    if "Enganche" in df.columns and "Precio Venta (c/IVA)" in df.columns:
        tabla["% Enganche prom."] = (
            (df["Enganche"] / df["Precio Venta (c/IVA)"] * 100)
            .groupby(df["Categoria"]).mean().round(1)
        ).reindex(orden_presente)

    if "¿Tiene GAP?" in df.columns:
        tabla["% con GAP"] = (
            (df["¿Tiene GAP?"] == "SI")
            .groupby(df["Categoria"]).mean().mul(100).round(1)
        ).reindex(orden_presente)

    display(tabla)
    print("\nEsta tabla ayuda a identificar focos de atención: por ejemplo, si las")
    print("solicitudes RECHAZADAS piden un % de enganche más bajo, un monto a")
    print("financiar más alto, o llevan menos GAP que las APROBADAS o FINANCIADAS,")
    print("ese es un patrón a vigilar.\n")
    return tabla


# =======================================================================
# 7) GRÁFICAS
#    Mismas gráficas que el script original y con el mismo estilo visual.
#    Cada función ahora acepta guardar_como=<ruta.png>: si se indica,
#    guarda la imagen en disco (para incrustarla en el PDF) además de
#    mostrarla en pantalla como antes. Devuelve la ruta guardada (o None).
# =======================================================================

def grafica_status(df, guardar_como=None):
    """Barras: número de solicitudes por ESTATUS."""
    if "STATUS" not in df.columns:
        return None
    conteo = df["STATUS"].value_counts().sort_values(ascending=False)

    fig, ax = plt.subplots(figsize=(8, 5))
    # Cada barra toma el color de SU categoría (no un degradado de rojos por
    # posición): así esta gráfica se lee junto con la dona y las barras
    # apiladas, donde el color significa lo mismo.
    colores = [COLOR_CATEGORIA.get(clasificar_status(s), MG_GRIS_CLARO)
               for s in conteo.index]
    barras = ax.bar(conteo.index, conteo.values, color=colores, edgecolor="white")

    for barra, valor in zip(barras, conteo.values):
        ax.text(barra.get_x() + barra.get_width() / 2, valor + max(conteo.values) * 0.01,
                 f"{valor}\n({valor/conteo.sum()*100:.0f}%)", ha="center", va="bottom", fontsize=9)

    ax.set_title("Solicitudes por estatus")
    ax.set_ylabel("Número de solicitudes")
    ax.set_ylim(0, max(conteo.values) * 1.2)
    plt.xticks(rotation=15)
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como

def grafica_dona_categoria(df, guardar_como=None):
    """Dona: proporción Financiado vs Aprobado vs CONTRAPROPUESTA vs Rechazado,
    con los nombres (primer nombre) de los vendedores que aportan a cada
    categoría dentro de la leyenda."""
    if "Categoria" not in df.columns:
        return None
    conteo_bruto = df["Categoria"].value_counts()
    orden_presente = [c for c in ORDEN_CATEGORIAS if c in conteo_bruto.index]
    conteo = conteo_bruto.reindex(orden_presente)
    colores = [COLOR_CATEGORIA.get(c, MG_GRIS_CLARO) for c in conteo.index]

    fig, ax = plt.subplots(figsize=(8, 7))
    wedges, _, autotextos = ax.pie(
        conteo.values, labels=None, autopct="%1.0f%%", pctdistance=0.8,
        colors=colores, startangle=90, wedgeprops=dict(width=0.42, edgecolor="white"),
        textprops=dict(fontweight="bold"),
    )
    for autotexto, color_rebanada in zip(autotextos, colores):
        autotexto.set_color(_color_texto_legible(color_rebanada))

    etiquetas = []
    for cat, valor in zip(conteo.index, conteo.values):
        etiqueta = f"{_est.etiqueta(cat).upper()} ({valor})"
        if "Nombre del Vendedor" in df.columns:
            etiqueta += f"\n   {_lista_vendedores_por_categoria(df, cat)}"
        etiquetas.append(etiqueta)

    # Con muchos estatus, una leyenda de una sola columna crecía tanto hacia
    # abajo que al exportar (bbox "tight") la imagen quedaba altísima y, al
    # escalarla al ancho del PDF, la dona se encogía hasta casi desaparecer.
    # A partir de 7 entradas se reparte en dos columnas.
    n_cat = len(etiquetas)
    ax.legend(wedges, etiquetas, loc="upper center", bbox_to_anchor=(0.5, -0.02),
               frameon=False, fontsize=8.5 if n_cat > 9 else 9,
               ncol=2 if n_cat > 6 else 1,
               labelspacing=0.9 if n_cat > 6 else 1.2,
               columnspacing=1.5)
    ax.set_title("Proporción por estatus")
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como

def grafica_vendedores(df, guardar_como=None):
    """Barras horizontales: total de solicitudes por vendedor."""
    if "Nombre del Vendedor" not in df.columns:
        return None
    conteo = df["Nombre del Vendedor"].value_counts().sort_values(ascending=True)

    fig, ax = plt.subplots(figsize=(8, max(4, len(conteo) * 0.5)))
    colores = list(reversed(_gradiente(len(conteo))))
    ax.barh(conteo.index, conteo.values, color=colores, edgecolor="white")

    for i, valor in enumerate(conteo.values):
        ax.text(valor + max(conteo.values) * 0.01, i, str(valor), va="center", fontsize=9)

    ax.set_title("Solicitudes por vendedor")
    ax.set_xlabel("Número de solicitudes")
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como

def grafica_vendedor_status(df, guardar_como=None):
    """Barras horizontales apiladas: desempeño de cada vendedor por categoría."""
    if "Nombre del Vendedor" not in df.columns or "Categoria" not in df.columns:
        return None

    pivote = pd.crosstab(df["Nombre del Vendedor"], df["Categoria"])
    orden_cols = [c for c in ORDEN_CATEGORIAS if c in pivote.columns]
    pivote = pivote[orden_cols]
    pivote["Total"] = pivote.sum(axis=1)
    pivote = pivote.sort_values("Total", ascending=True).drop(columns="Total")

    fig, ax = plt.subplots(figsize=(9, max(4, len(pivote) * 0.55) + 0.8))
    izquierda = np.zeros(len(pivote))
    for col in orden_cols:
        valores = pivote[col].values
        ax.barh(pivote.index, valores, left=izquierda,
                 color=COLOR_CATEGORIA.get(col, MG_GRIS_CLARO),
                 label=_est.etiqueta(col), edgecolor="white")
        izquierda += valores

    # El título NO enumera las categorías (la leyenda de abajo ya lo hace):
    # con muchos estatus esa línea salía más ancha que la gráfica y deformaba
    # la imagen al exportarla.
    ax.set_title("Estatus de cierre por vendedor")
    ax.set_xlabel("Número de solicitudes")
    # ncol se ajusta al número de categorías para que la leyenda no se
    # amontone cuando hay más de cuatro.
    ax.legend(loc="upper center", bbox_to_anchor=(0, -0.30, 1, 0.16),
              mode="expand", frameon=False, fontsize=8,
              handlelength=1.4, columnspacing=1.2,
              ncol=min(3, max(1, len(orden_cols))))
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como

def grafica_monto_por_vendedor(df, guardar_como=None):
    """Barras horizontales agrupadas: monto colocado por vendedor,
    separando APROBADO (aún sin dispersar) de FINANCIADO (ya dispersado)."""
    if not {"Nombre del Vendedor", "Categoria", "Monto Total a Financiar"}.issubset(df.columns):
        return None

    monto_aprobado = (
        df[df["Categoria"] == "APROBADO"]
        .groupby("Nombre del Vendedor")["Monto Total a Financiar"].sum()
    )
    monto_financiado = (
        df[df["Categoria"] == "FINANCIADO"]
        .groupby("Nombre del Vendedor")["Monto Total a Financiar"].sum()
    )

    vendedores = sorted(
        set(monto_aprobado.index) | set(monto_financiado.index),
        key=lambda v: monto_aprobado.get(v, 0) + monto_financiado.get(v, 0),
    )
    if not vendedores:
        return None

    valores_aprobado = np.array([monto_aprobado.get(v, 0) for v in vendedores])
    valores_financiado = np.array([monto_financiado.get(v, 0) for v in vendedores])
    maximo = max(valores_aprobado.max(), valores_financiado.max(), 1)

    y = np.arange(len(vendedores))
    alto = 0.36

    fig, ax = plt.subplots(figsize=(9, max(4, len(vendedores) * 0.65)))
    ax.barh(y + alto / 2, valores_aprobado, height=alto, color=MG_ROJO,
             edgecolor="white", label="Aprobado (sin dispersar)")
    ax.barh(y - alto / 2, valores_financiado, height=alto, color=MG_ROJO_OSCURO,
             edgecolor="white", label="Financiado (dispersado)")

    for yi, valor in zip(y + alto / 2, valores_aprobado):
        if valor > 0:
            ax.text(valor + maximo * 0.015, yi, f"${valor:,.0f}", va="center", fontsize=8)
    for yi, valor in zip(y - alto / 2, valores_financiado):
        if valor > 0:
            ax.text(valor + maximo * 0.015, yi, f"${valor:,.0f}", va="center", fontsize=8)

    ax.set_yticks(y)
    ax.set_yticklabels(vendedores)
    ax.set_xlim(0, maximo * 1.18)
    _formato_miles(ax, eje="x")

    ax.set_title("Monto por vendedor: aprobado vs. financiado")
    ax.set_xlabel("Monto a financiar ($ MXN)")
    ax.legend(loc="lower right", frameon=False)
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como

def grafica_modelos(df, guardar_como=None):
    """Barras horizontales: modelos de vehículo más solicitados."""
    if "Vehículo" not in df.columns:
        return None
    conteo_completo = df["Vehículo"].dropna().value_counts()
    if conteo_completo.empty:
        return None

    TOP_N = 10
    recortado = len(conteo_completo) > TOP_N
    conteo = conteo_completo.head(TOP_N).sort_values(ascending=True)

    fig, ax = plt.subplots(figsize=(8, max(4, len(conteo) * 0.4)))
    colores = list(reversed(_gradiente(len(conteo))))
    ax.barh(conteo.index, conteo.values, color=colores, edgecolor="white")

    for i, valor in enumerate(conteo.values):
        ax.text(valor + max(conteo.values) * 0.02, i, str(valor), va="center", fontsize=9)

    titulo = "Modelos más solicitados"
    if recortado:
        titulo += f" (top {TOP_N})"
    ax.set_title(titulo)
    ax.set_xlabel("Número de solicitudes")
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como

def grafica_gap_por_categoria(df, guardar_como=None):
    """Barras: % de solicitudes que llevan GAP, por categoría de status."""
    if "Categoria" not in df.columns or "¿Tiene GAP?" not in df.columns:
        return None

    pct_gap = (
        (df["¿Tiene GAP?"] == "SI").groupby(df["Categoria"]).mean().mul(100)
    )
    orden_presente = [c for c in ORDEN_CATEGORIAS if c in pct_gap.index]
    pct_gap = pct_gap.reindex(orden_presente)
    if pct_gap.empty:
        return None

    colores = [COLOR_CATEGORIA.get(c, MG_GRIS_CLARO) for c in pct_gap.index]

    fig, ax = plt.subplots(figsize=(7, 5))
    barras = ax.bar(pct_gap.index, pct_gap.values, color=colores, edgecolor="white")

    for barra, valor in zip(barras, pct_gap.values):
        ax.text(barra.get_x() + barra.get_width() / 2, valor + 2,
                 f"{valor:.0f}%", ha="center", va="bottom", fontsize=9, fontweight="bold")

    ax.set_title("% con GAP por estatus", pad=14)
    ax.set_ylabel("% con GAP")
    # El tope se ajusta al dato real (antes estaba fijo en 120% y dejaba
    # media gráfica vacía). Las etiquetas se inclinan más porque con muchas
    # categorías los nombres se encimaban unos con otros.
    ax.set_ylim(0, min(100, max(pct_gap.values) * 1.25))
    plt.xticks(rotation=30, ha="right")
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como

def grafica_gap_por_vendedor_total(df, guardar_como=None):
    """Barras horizontales agrupadas: solicitudes con GAP por vendedor,
    comparadas contra el total de solicitudes de cada vendedor (para ver
    de un vistazo qué proporción de las solicitudes de cada quien llevó GAP)."""
    if "Nombre del Vendedor" not in df.columns or "¿Tiene GAP?" not in df.columns:
        print("Las columnas 'Nombre del Vendedor' o '¿Tiene GAP?' no están presentes.")
        return None

    df_gap = df[df["¿Tiene GAP?"] == "SI"].copy()
    if df_gap.empty:
        print("No hay solicitudes con GAP para graficar.")
        return None

    conteo_gap = df_gap["Nombre del Vendedor"].value_counts()
    conteo_total = df["Nombre del Vendedor"].value_counts()

    # Se usa el total de solicitudes (no solo las que tienen GAP) para que
    # aparezcan TODOS los vendedores, incluso los que tuvieron 0 GAP.
    vendedores = conteo_total.sort_values(ascending=True).index.tolist()
    valores_total = np.array([conteo_total.get(v, 0) for v in vendedores])
    valores_gap = np.array([conteo_gap.get(v, 0) for v in vendedores])
    maximo = max(valores_total.max(), valores_gap.max(), 1)

    y = np.arange(len(vendedores))
    alto = 0.36

    fig, ax = plt.subplots(figsize=(9, max(4, len(vendedores) * 0.65)))
    ax.barh(y + alto / 2, valores_total, height=alto, color=MG_GRIS_CLARO,
             edgecolor="white", label="Total de solicitudes")
    ax.barh(y - alto / 2, valores_gap, height=alto, color=MG_ROJO,
             edgecolor="white", label="Con GAP")

    for yi, valor in zip(y + alto / 2, valores_total):
        ax.text(valor + maximo * 0.015, yi, str(valor), va="center", fontsize=8)
    for yi, valor in zip(y - alto / 2, valores_gap):
        ax.text(valor + maximo * 0.015, yi, str(valor), va="center", fontsize=8)

    ax.set_yticks(y)
    ax.set_yticklabels(vendedores)
    ax.set_xlim(0, maximo * 1.18)

    ax.set_title("Cobertura de GAP por vendedor")
    ax.set_xlabel("Número de solicitudes")
    ax.legend(loc="lower right", frameon=False)
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como

def grafica_gap_por_vendedor_y_status(df, guardar_como=None):
    """Barras horizontales apiladas: solicitudes con GAP por vendedor, desglosado por categoría de status."""
    if not {"Nombre del Vendedor", "Categoria", "¿Tiene GAP?"}.issubset(df.columns):
        print("Las columnas 'Nombre del Vendedor', 'Categoria' o '¿Tiene GAP?' no están presentes.")
        return None

    df_gap = df[df["¿Tiene GAP?"] == "SI"].copy()
    if df_gap.empty:
        print("No hay solicitudes con GAP para graficar.")
        return None

    pivote = pd.crosstab(df_gap["Nombre del Vendedor"], df_gap["Categoria"])
    orden_cols = [c for c in ORDEN_CATEGORIAS if c in pivote.columns]
    pivote = pivote[orden_cols]
    pivote["Total"] = pivote.sum(axis=1)
    pivote = pivote.sort_values("Total", ascending=True).drop(columns="Total")

    if pivote.empty:
        print("No hay datos de GAP por vendedor y status para graficar.")
        return None

    fig, ax = plt.subplots(figsize=(9, max(4, len(pivote) * 0.55) + 0.8))
    izquierda = np.zeros(len(pivote))
    for col in orden_cols:
        valores = pivote[col].values
        ax.barh(pivote.index, valores, left=izquierda,
                 color=COLOR_CATEGORIA.get(col, MG_GRIS_CLARO),
                 label=_est.etiqueta(col), edgecolor="white")
        izquierda += valores

    ax.set_title("GAP por vendedor y estatus")
    ax.set_xlabel("Número de solicitudes con GAP")
    ax.legend(loc="upper center", bbox_to_anchor=(0, -0.30, 1, 0.16),
              mode="expand", frameon=False, fontsize=8,
              handlelength=1.4, columnspacing=1.2,
              ncol=min(3, max(1, len(orden_cols))))
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como

def grafica_gap_financiado_por_vendedor(df, guardar_como=None):
    """Barras horizontales: solicitudes FINANCIADAS con GAP por vendedor,
    con felicitación a todos los que tengan la máxima colocación (maneja empates)."""
    if not {"Nombre del Vendedor", "Categoria", "¿Tiene GAP?"}.issubset(df.columns):
        print("Las columnas 'Nombre del Vendedor', 'Categoria' o '¿Tiene GAP?' no están presentes.")
        return None

    df_fin_gap = df[(df["Categoria"] == "FINANCIADO") & (df["¿Tiene GAP?"] == "SI")].copy()
    if df_fin_gap.empty:
        print("No hay solicitudes FINANCIADAS con GAP para graficar.")
        return None

    conteo = df_fin_gap["Nombre del Vendedor"].value_counts().sort_values(ascending=True)

    fig, ax = plt.subplots(figsize=(8, max(4, len(conteo) * 0.5)))
    colores = list(reversed(_gradiente(len(conteo))))

    if not conteo.empty:
        max_gap = conteo.max()
        vendedores_top = conteo[conteo == max_gap].index.tolist()

        ax.barh(conteo.index, conteo.values, color=colores, edgecolor="white")
        for i, (vendedor, valor) in enumerate(conteo.items()):
            ax.text(valor + max(conteo.values) * 0.01, i, str(valor), va="center", fontsize=9)
            if vendedor in vendedores_top and max_gap > 0:
                ax.text(valor + max(conteo.values) * 0.05, i,
                        f"¡Felicidades, {vendedor}!", va="center", fontsize=9,
                        color=MG_ROJO_OSCURO, fontweight="bold")

    ax.set_title("GAP en créditos financiados, por vendedor")
    ax.set_xlabel("Solicitudes FINANCIADAS con GAP")
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como

def generar_todas_las_graficas(df):
    """Genera y muestra en pantalla todas las gráficas (uso interactivo en Colab,
    sin guardarlas en disco). Se conserva igual que en el script original."""
    print("=" * 72)
    print(" GRÁFICAS")
    print("=" * 72)
    grafica_status(df)
    grafica_dona_categoria(df)
    grafica_vendedores(df)
    grafica_vendedor_status(df)
    grafica_monto_por_vendedor(df)
    grafica_modelos(df)
    grafica_gap_por_categoria(df)
    grafica_gap_por_vendedor_total(df)
    grafica_gap_por_vendedor_y_status(df)
    grafica_gap_financiado_por_vendedor(df)

def generar_graficas_para_pdf(df):
    """Genera todas las gráficas guardándolas como PNG en CARPETA_GRAFICAS,
    listas para incrustarse en el reporte narrativo. Devuelve un diccionario
    {clave: ruta_png} solo con las gráficas que sí se pudieron generar
    (si falta una columna o no hay datos, esa clave simplemente no aparece)."""
    print("=" * 72)
    print(" GENERANDO GRÁFICAS PARA EL REPORTE")
    print("=" * 72)
    especificaciones = [
        ("status",               grafica_status,                    "g01_status.png"),
        ("dona_categoria",       grafica_dona_categoria,             "g02_dona_categoria.png"),
        ("vendedores",           grafica_vendedores,                 "g03_vendedores.png"),
        ("vendedor_status",      grafica_vendedor_status,            "g04_vendedor_status.png"),
        ("monto_por_vendedor",   grafica_monto_por_vendedor,         "g05_monto_vendedor.png"),
        ("modelos",              grafica_modelos,                    "g06_modelos.png"),
        ("gap_por_categoria",    grafica_gap_por_categoria,          "g08_gap_categoria.png"),
        ("gap_por_vendedor",     grafica_gap_por_vendedor_total,     "g09_gap_vendedor.png"),
        ("gap_vendedor_status",  grafica_gap_por_vendedor_y_status,  "g10_gap_vendedor_status.png"),
        ("gap_financiado_vend",  grafica_gap_financiado_por_vendedor, "g11_gap_financiado_vendedor.png"),
    ]
    rutas = {}
    for clave, funcion, nombre_archivo in especificaciones:
        ruta = os.path.join(CARPETA_GRAFICAS, nombre_archivo)
        resultado = funcion(df, guardar_como=ruta)
        plt.close("all")
        if resultado:
            rutas[clave] = resultado
    print(f"\n{len(rutas)} gráficas generadas correctamente.\n")

    # Guarda de seguridad: si NINGUNA gráfica se pudo generar, algo está mal
    # de fondo (carpeta borrada, permisos, columnas faltantes). Antes el
    # reporte se armaba igual y salía un PDF entero sin una sola gráfica, sin
    # ningún error visible. Es mejor fallar fuerte y decir por qué.
    if not rutas:
        raise RuntimeError(
            "No se pudo generar ninguna gráfica. Revisa que el archivo traiga "
            "las columnas esperadas (STATUS, Nombre del Vendedor, etc.) y que "
            f"la carpeta '{CARPETA_GRAFICAS}' se pueda escribir."
        )

    return rutas


# =======================================================================
# 8) REPORTE NARRATIVO EN PDF (ReportLab)
#    Resumen ejecutivo redactado + tarjetas KPI + tablas con estilo +
#    gráficas incrustadas, con explicación de cada una. Mismo espíritu
#    que "Reporte de Expedientes Faltantes", adaptado a la bitácora.
# =======================================================================

def imagen_ajustada(ruta, ancho_cm, alto_max_cm=None):
    """Crea un flowable Image respetando la proporción real del PNG, para
    que las gráficas horizontales (con alturas variables según el número
    de vendedores o modelos) siempre se vean bien en el PDF."""
    ancho_px, alto_px = ImageReader(ruta).getSize()
    alto_cm = ancho_cm * (alto_px / ancho_px)
    if alto_max_cm and alto_cm > alto_max_cm:
        alto_cm = alto_max_cm
        ancho_cm = alto_cm * (ancho_px / alto_px)
    return Image(ruta, width=ancho_cm * cm, height=alto_cm * cm, hAlign="CENTER")


# ===========================================================================
#  MAQUETACIÓN DEL PDF — estilos, encabezado/pie, tablas y tarjetas KPI
# ===========================================================================
# Este bloque estaba copiado casi igual (88%) en el avance y en el resumen:
# los mismos trece ParagraphStyle, el mismo encabezado/pie de página y las
# mismas funciones de tabla y tarjeta KPI. Cualquier ajuste de estilo había
# que hacerlo dos veces.
#
# Se devuelven en diccionarios porque los reportes los siguen usando como
# variables locales, igual que cuando estaban definidos dentro de
# generar_reporte_pdf_*: así la narrativa de cada reporte no tuvo que
# cambiar ni una línea.
def crear_estilos():
    """Los ParagraphStyle del reporte. Iguales para los tres."""
    styles = getSampleStyleSheet()
    estilo_kicker_portada = ParagraphStyle(
        "KickerPortada", parent=styles["Normal"], fontName=FUENTE_BOLD, fontSize=9.5,
        textColor=rl_colors.HexColor(MG_ROJO), alignment=TA_LEFT, spaceAfter=6, leading=12)
    estilo_titulo_portada = ParagraphStyle(
        "TituloPortada", parent=styles["Title"], fontName=FUENTE_BOLD, fontSize=25,
        textColor=rl_colors.HexColor(INBURSA_AZUL), alignment=TA_LEFT,
        spaceAfter=4, leading=29)
    estilo_subtitulo_portada = ParagraphStyle(
        "SubtituloPortada", parent=styles["Normal"], fontName=FUENTE_REGULAR, fontSize=12,
        textColor=rl_colors.HexColor(GRIS_TEXTO_SEC), alignment=TA_LEFT, spaceAfter=4)
    estilo_meta_portada = ParagraphStyle(
        "MetaPortada", parent=styles["Normal"], fontName=FUENTE_REGULAR, fontSize=9.5,
        textColor=rl_colors.HexColor(GRIS_TEXTO_SEC), alignment=TA_LEFT, leading=13)
    estilo_h1 = ParagraphStyle(
        "H1MG", parent=styles["Heading1"], fontName=FUENTE_BOLD, fontSize=15.5,
        textColor=rl_colors.HexColor(INBURSA_AZUL), spaceBefore=16, spaceAfter=8)
    estilo_h2 = ParagraphStyle(
        "H2MG", parent=styles["Heading2"], fontName=FUENTE_BOLD, fontSize=12.5,
        textColor=rl_colors.HexColor(MG_ROJO_OSCURO), spaceBefore=10, spaceAfter=6)
    estilo_cuerpo = ParagraphStyle(
        "CuerpoMG", parent=styles["Normal"], fontName=FUENTE_REGULAR, fontSize=10,
        textColor=rl_colors.HexColor(MG_GRIS_OSCURO), leading=15, alignment=TA_JUSTIFY, spaceAfter=6)
    estilo_nota = ParagraphStyle(
        "NotaMG", parent=styles["Normal"], fontSize=8.5,
        textColor=rl_colors.HexColor(GRIS_TEXTO_SEC), leading=11, alignment=TA_LEFT,
        spaceAfter=4, fontName=FUENTE_ITALICA)
    estilo_kpi_valor = ParagraphStyle(
        "KPIValor", parent=styles["Normal"], fontSize=20,
        textColor=rl_colors.HexColor(MG_GRIS_OSCURO), alignment=TA_CENTER,
        fontName=FUENTE_BOLD, leading=23)
    estilo_kpi_label = ParagraphStyle(
        "KPILabel", parent=styles["Normal"], fontName=FUENTE_BOLD, fontSize=7.8,
        textColor=rl_colors.HexColor(GRIS_TEXTO_SEC), alignment=TA_CENTER, leading=9.5)
    estilo_encabezado_tabla = ParagraphStyle(
        "EncabezadoTabla", parent=styles["Normal"], fontSize=8.3, leading=10,
        textColor=rl_colors.white, fontName=FUENTE_BOLD, alignment=TA_CENTER)

    # Versión reducida, para tablas con muchas columnas (muchos estatus)
    estilo_encabezado_tabla_compacto = ParagraphStyle(
        "EncabezadoTablaCompacto", parent=styles["Normal"], fontSize=6.6,
        leading=7.8, textColor=rl_colors.white, fontName=FUENTE_BOLD,
        alignment=TA_CENTER)
    return {
        "styles": styles,
        "kicker_portada": estilo_kicker_portada,
        "titulo_portada": estilo_titulo_portada,
        "subtitulo_portada": estilo_subtitulo_portada,
        "meta_portada": estilo_meta_portada,
        "h1": estilo_h1,
        "h2": estilo_h2,
        "cuerpo": estilo_cuerpo,
        "nota": estilo_nota,
        "kpi_valor": estilo_kpi_valor,
        "kpi_label": estilo_kpi_label,
        "encabezado_tabla": estilo_encabezado_tabla,
        "encabezado_tabla_compacto": estilo_encabezado_tabla_compacto,
    }


def crear_maquetadores(e, subtitulo, empresa, analista, fecha):
    """Encabezado/pie, tablas y tarjetas KPI, ya atados a los estilos y a
    los datos del PDV.

    `subtitulo`, `empresa` y `analista` van por parámetro (no como
    constantes del módulo) porque la app los cambia por punto de venta
    antes de generar cada reporte.
    """
    def encabezado_pie_pagina(canvas_obj, doc):
        """Encabezado y pie 'corporativo moderno': fondo blanco, una franja
        de marca delgada (azul Inbursa) en el borde superior, un pequeño
        tick rojo MG como acento y una regla fina en vez de los bloques de
        color sólido de la versión anterior."""
        canvas_obj.saveState()
        ancho, alto = letter

        # --- Encabezado ---
        canvas_obj.setFillColor(rl_colors.HexColor(INBURSA_AZUL))
        canvas_obj.rect(0, alto - 0.14 * cm, ancho, 0.14 * cm, fill=1, stroke=0)
        canvas_obj.setFillColor(rl_colors.HexColor(MG_ROJO))
        canvas_obj.rect(1.5 * cm, alto - 1.05 * cm, 0.24 * cm, 0.24 * cm, fill=1, stroke=0)

        canvas_obj.setFillColor(rl_colors.HexColor(INBURSA_AZUL))
        canvas_obj.setFont(FUENTE_BOLD, 10.5)
        canvas_obj.drawString(1.95 * cm, alto - 1.0 * cm, empresa)
        canvas_obj.setFillColor(rl_colors.HexColor(GRIS_TEXTO_SEC))
        canvas_obj.setFont(FUENTE_REGULAR, 8)
        canvas_obj.drawString(1.95 * cm, alto - 1.32 * cm,
                               subtitulo)

        canvas_obj.setFillColor(rl_colors.HexColor(GRIS_TEXTO_SEC))
        canvas_obj.setFont(FUENTE_REGULAR, 8.5)
        canvas_obj.drawRightString(ancho - 1.5 * cm, alto - 1.05 * cm, fecha)

        canvas_obj.setStrokeColor(rl_colors.HexColor(GRIS_LINEA))
        canvas_obj.setLineWidth(0.8)
        canvas_obj.line(1.5 * cm, alto - 1.55 * cm, ancho - 1.5 * cm, alto - 1.55 * cm)

        # --- Pie de página ---
        canvas_obj.setStrokeColor(rl_colors.HexColor(GRIS_LINEA))
        canvas_obj.setLineWidth(0.8)
        canvas_obj.line(1.5 * cm, 1.05 * cm, ancho - 1.5 * cm, 1.05 * cm)

        canvas_obj.setFillColor(rl_colors.HexColor(MG_ROJO))
        canvas_obj.rect(1.5 * cm, 0.66 * cm, 0.16 * cm, 0.16 * cm, fill=1, stroke=0)
        canvas_obj.setFillColor(rl_colors.HexColor(GRIS_TEXTO_SEC))
        canvas_obj.setFont(FUENTE_REGULAR, 8)
        canvas_obj.drawString(1.85 * cm, 0.65 * cm, analista)
        canvas_obj.drawCentredString(ancho / 2, 0.65 * cm, f"Página {doc.page}")
        canvas_obj.drawRightString(ancho - 1.5 * cm, 0.65 * cm, empresa)
        canvas_obj.restoreState()

    def tabla_estilo_mg(data, col_widths=None, alinear_derecha_desde=1,
                        compacta=False, fila_total=False):
        """Tabla 'corporativa moderna': encabezado azul Inbursa, sin líneas
        verticales (solo reglas horizontales finas entre filas), zebrado en
        gris casi blanco y un filete rojo MG bajo el encabezado como único
        acento de color fuerte.

        compacta=True baja el tamaño de letra y los márgenes internos: se usa
        cuando la tabla tiene muchas columnas (por ejemplo, cuando el mes trae
        muchos estatus distintos) para que los encabezados no se partan a
        media palabra.

        fila_total=True trata el último renglón como el resumen de la tabla:
        lo separa con un filete rojo, le pone fondo propio, negritas y algo
        más de aire. Es el renglón que más se consulta y con el zebrado
        normal se perdía entre los demás.
        """
        # Entre más columnas, más chico el encabezado, para que etiquetas
        # como "Financiado" o "Rechazado" quepan en una sola línea.
        if compacta:
            _n_cols = len(data[0])
            estilo_enc = e["encabezado_tabla_compacto"].clone(
                "EncabezadoTablaAuto",
                fontSize=6.6 if _n_cols <= 9 else 5.7,
                leading=7.8 if _n_cols <= 9 else 6.8,
            )
        else:
            estilo_enc = e["encabezado_tabla"]
        encabezado = [Paragraph(str(c), estilo_enc) for c in data[0]]
        data = [encabezado] + data[1:]
        tabla = Table(data, colWidths=col_widths, repeatRows=1)
        n_filas = len(data)
        estilo = [
            ("BACKGROUND", (0, 0), (-1, 0), rl_colors.HexColor(INBURSA_AZUL)),
            ("TEXTCOLOR", (0, 0), (-1, 0), rl_colors.white),
            ("FONTNAME", (0, 0), (-1, 0), FUENTE_BOLD),
            ("FONTNAME", (0, 1), (-1, -1), FUENTE_REGULAR),
            ("FONTSIZE", (0, 1), (-1, -1), 7.0 if compacta else 8.5),
            ("TEXTCOLOR", (0, 1), (-1, -1), rl_colors.HexColor(MG_GRIS_OSCURO)),
            ("ALIGN", (alinear_derecha_desde, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LINEBELOW", (0, 0), (-1, 0), 1.6, rl_colors.HexColor(MG_ROJO)),
            ("LINEBELOW", (0, 1), (-1, max(n_filas - 2, 1)), 0.5, rl_colors.HexColor(GRIS_LINEA)),
            ("BOX", (0, 0), (-1, -1), 0.75, rl_colors.HexColor(GRIS_LINEA)),
            ("ROWBACKGROUNDS", (0, 1), (-1, -2 if fila_total else -1),
             [rl_colors.white, rl_colors.HexColor(GRIS_ZEBRA)]),
            ("TOPPADDING", (0, 0), (-1, 0), 7),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 7),
            ("TOPPADDING", (0, 1), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 2 if compacta else 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 2 if compacta else 6),
        ]
        if fila_total and n_filas >= 2:
            f = n_filas - 1
            estilo += [
                # Filete rojo arriba: separa el resumen del detalle con el
                # mismo acento que va bajo el encabezado, para que la tabla
                # quede "cerrada" por los dos extremos.
                ("LINEABOVE", (0, f), (-1, f), 1.4, rl_colors.HexColor(MG_ROJO)),
                ("BACKGROUND", (0, f), (-1, f), rl_colors.HexColor("#EAEEF4")),
                ("FONTNAME", (0, f), (-1, f), FUENTE_BOLD),
                ("FONTSIZE", (0, f), (-1, f), 7.4 if compacta else 9.0),
                ("TEXTCOLOR", (0, f), (-1, f), rl_colors.HexColor(INBURSA_AZUL)),
                ("TOPPADDING", (0, f), (-1, f), 7),
                ("BOTTOMPADDING", (0, f), (-1, f), 7),
                ("LINEBELOW", (0, f - 1), (-1, f - 1), 0, rl_colors.white),
            ]

        tabla.setStyle(TableStyle(estilo))
        return tabla

    def tarjeta_kpi(valor, etiqueta, color_acento):
        """Tarjeta KPI 'plana' corporativa: fondo blanco, barra de acento
        delgada arriba (en vez del bloque de color sólido anterior) y el
        número protagonizando en el color de acento, con borde muy sutil."""
        estilo_valor_acento = e["kpi_valor"].clone("KPIValorAcento", textColor=rl_colors.HexColor(color_acento))
        t = Table(
            [[""], [Paragraph(str(valor), estilo_valor_acento)], [Paragraph(etiqueta, e["kpi_label"])]],
            colWidths=[4.0 * cm], rowHeights=[0.11 * cm, None, None]
        )
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), rl_colors.HexColor(color_acento)),
            ("BACKGROUND", (0, 1), (-1, -1), rl_colors.white),
            ("BOX", (0, 0), (-1, -1), 0.75, rl_colors.HexColor(GRIS_LINEA)),
            ("TOPPADDING", (0, 1), (-1, 1), 10),
            ("BOTTOMPADDING", (0, 1), (-1, 1), 1),
            ("TOPPADDING", (0, 2), (-1, 2), 0),
            ("BOTTOMPADDING", (0, 2), (-1, 2), 10),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ]))
        return t

    return {
        "encabezado_pie_pagina": encabezado_pie_pagina,
        "tabla_estilo_mg": tabla_estilo_mg,
        "tarjeta_kpi": tarjeta_kpi,
    }


# ===========================================================================
#  SECCIÓN "REPORTE DETALLADO" (secciones 1 a 6)
# ===========================================================================
# Era el bloque más duplicado que quedaba: 189 líneas con un 97% idéntico
# entre el avance y el resumen. Las únicas diferencias reales eran tres
# frases, que ahora entran por el parámetro `textos`.
def secciones_detalladas(elementos, e, textos, df, rutas_graficas, tabla_vendedor,
                          tabla_categoria, tabla_estilo_mg, n_vendedores,
                          modelo_top, modelo_top_val):
    """Agrega a `elementos` las secciones 1 a 6 del reporte detallado.

    e:       diccionario de estilos (crear_estilos)
    textos:  {"estatus": ..., "vendedores": ..., "modelos": ...} — las tres
             frases que cambian entre el avance preliminar y el cierre de mes.
    """
    # ===============================================================
    # REPORTE DETALLADO
    # ===============================================================
    elementos.append(Paragraph("Reporte Detallado", e["h1"]))
    elementos.append(HRFlowable(width="100%", thickness=1, color=rl_colors.HexColor(MG_ROJO), spaceAfter=8))

    # --- 1. Distribución de solicitudes por status ---
    if "status" in rutas_graficas or "dona_categoria" in rutas_graficas:
        elementos.append(Paragraph("1. Distribución de Solicitudes por Estatus", e["h2"]))
        elementos.append(Paragraph(
            textos["estatus"],
            e["cuerpo"]
        ))
        if "status" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["status"], ancho_cm=16, alto_max_cm=9))
            elementos.append(Spacer(1, 0.2 * cm))
        if "dona_categoria" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["dona_categoria"], ancho_cm=12, alto_max_cm=12))
        elementos.append(Spacer(1, 0.4 * cm))

    # --- 2. Desempeño por vendedor ---
    if tabla_vendedor is not None and not tabla_vendedor.empty:
        elementos.append(Paragraph("2. Desempeño por Vendedor", e["h2"]))
        elementos.append(Paragraph(
            textos["vendedores"],
            e["cuerpo"]
        ))

        claves_v = [c for c in ORDEN_CATEGORIAS if c in tabla_vendedor.columns]
        tiene_pct = "% Financiado" in tabla_vendedor.columns

        # Con muchos estatus la tabla no cabe a lo ancho: una columna por
        # estatus deja menos de 1 cm por columna y los encabezados se parten
        # a media palabra. A partir de 8 estatus se voltea la tabla —los
        # estatus pasan a las filas y los vendedores a las columnas—, que es
        # la orientación natural cuando hay más estatus que vendedores.
        VOLTEAR_DESDE = 8
        if len(claves_v) >= VOLTEAR_DESDE:
            vendedores_v = list(tabla_vendedor.index)
            encabezados_v = ["Estatus"] + list(vendedores_v) + ["Total"]
            filas_v = []
            for c in claves_v:
                valores = [int(tabla_vendedor.loc[v].get(c, 0)) for v in vendedores_v]
                filas_v.append([_est.etiqueta(c)] + valores + [sum(valores)])
            filas_v.append(["Total"]
                           + [int(tabla_vendedor.loc[v].get("Total", 0)) for v in vendedores_v]
                           + [int(tabla_vendedor["Total"].sum())])
            if tiene_pct:
                filas_v.append(["% Financiado"]
                               + [f"{tabla_vendedor.loc[v].get('% Financiado', 0):.1f}%"
                                  for v in vendedores_v] + [""])

            ancho_nombre_v = 4.6 * cm
            ancho_col_v = (18.3 * cm - ancho_nombre_v) / max(len(encabezados_v) - 1, 1)
            anchos_v = [ancho_nombre_v] + [ancho_col_v] * (len(encabezados_v) - 1)
            elementos.append(tabla_estilo_mg([encabezados_v] + filas_v,
                                             col_widths=anchos_v,
                                             compacta=len(encabezados_v) > 7))
        else:
            # Las etiquetas cortas de encabezado (con los saltos de línea para
            # que no se partan a media palabra) vienen del catálogo.
            encabezados_v = ["Vendedor", "Total"] + [_est.etiqueta_corta(c) for c in claves_v]
            if tiene_pct:
                encabezados_v.append("%<br/>Financiado" if len(encabezados_v) <= 6
                                     else "%<br/>Fin.")

            filas_v = []
            for vendedor, fila in tabla_vendedor.iterrows():
                f = [vendedor, int(fila.get("Total", 0))]
                for c in claves_v:
                    f.append(int(fila.get(c, 0)))
                if tiene_pct:
                    f.append(f"{fila.get('% Financiado', 0):.1f}%")
                filas_v.append(f)

            ancho_nombre_v = 4.2 * cm if len(encabezados_v) <= 7 else 3.4 * cm
            ancho_col_v = (18.3 * cm - ancho_nombre_v) / max(len(encabezados_v) - 1, 1)
            anchos_v = [ancho_nombre_v] + [ancho_col_v] * (len(encabezados_v) - 1)
            elementos.append(tabla_estilo_mg([encabezados_v] + filas_v,
                                             col_widths=anchos_v,
                                             compacta=len(encabezados_v) > 7))
        elementos.append(Spacer(1, 0.3 * cm))

        if "vendedores" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["vendedores"], ancho_cm=16, alto_max_cm=13))
            elementos.append(Spacer(1, 0.2 * cm))
        if "vendedor_status" in rutas_graficas:
            elementos.append(Paragraph(
                "La gráfica apila las solicitudes de cada vendedor por estatus, para comparar "
                "de un vistazo no solo el volumen sino la calidad del cierre.",
                e["cuerpo"]
            ))
            elementos.append(imagen_ajustada(rutas_graficas["vendedor_status"], ancho_cm=16, alto_max_cm=13))
        elementos.append(Spacer(1, 0.4 * cm))

    # --- 3. Monto colocado por vendedor ---
    if "monto_por_vendedor" in rutas_graficas:
        elementos.append(Paragraph("3. Monto Colocado por Vendedor", e["h2"]))
        elementos.append(Paragraph(
            "Compara, por vendedor, el monto en créditos <b>APROBADOS</b> (aún sin dispersar) "
            "contra el ya <b>FINANCIADO</b>. La diferencia separa el volumen de solicitudes "
            "del cierre efectivo de negocio.",
            e["cuerpo"]
        ))
        elementos.append(imagen_ajustada(rutas_graficas["monto_por_vendedor"], ancho_cm=16, alto_max_cm=15))
        elementos.append(Spacer(1, 0.4 * cm))

    # --- 4. Comparativo financiero por categoría ---
    if tabla_categoria is not None and not tabla_categoria.empty:
        elementos.append(Paragraph("4. Comparativo Financiero por Categoría", e["h2"]))
        elementos.append(Paragraph(
            "Esta tabla compara, para cada categoría de cierre, el precio de venta, enganche, monto "
            "a financiar, plazo y tasa promedio. Sirve para detectar focos de atención: por ejemplo, "
            "si las solicitudes RECHAZADAS piden un % de enganche más bajo, un monto más alto, o "
            "llevan menos GAP que las APROBADAS o FINANCIADAS, ese es un patrón a vigilar.",
            e["cuerpo"]
        ))

        columnas_disp = list(tabla_categoria.columns)
        encabezados_cat = ["Categoría"] + columnas_disp
        filas_cat = []
        for cat, fila in tabla_categoria.iterrows():
            f = [cat]
            for col in columnas_disp:
                valor = fila[col]
                if pd.isna(valor):
                    f.append("—")
                elif "%" in col:
                    f.append(f"{valor:.1f}%")
                elif "Monto" in col or "Precio" in col or "Enganche" in col:
                    f.append(f"${valor:,.0f}")
                else:
                    f.append(f"{valor:.1f}")
            filas_cat.append(f)

        ancho_disp = min(2.6 * cm, (18 * cm - 3.2 * cm) / max(len(columnas_disp), 1))
        anchos_cat = [3.2 * cm] + [ancho_disp] * len(columnas_disp)
        elementos.append(tabla_estilo_mg([encabezados_cat] + filas_cat, col_widths=anchos_cat))
        elementos.append(Spacer(1, 0.4 * cm))

    # --- 5. Seguro GAP ---
    tiene_gap_col = "¿Tiene GAP?" in df.columns
    if tiene_gap_col:
        elementos.append(Paragraph("5. Seguro GAP", e["h2"]))
        elementos.append(Paragraph(
            "El seguro GAP cubre la diferencia entre el valor asegurado del vehículo y el saldo "
            "insoluto del crédito en caso de pérdida total, por lo que su colocación es un indicador "
            "de venta cruzada relevante para la operación. A continuación se muestra qué proporción "
            "de solicitudes lo incluye, primero por categoría de cierre y después por vendedor.",
            e["cuerpo"]
        ))
        if "gap_por_categoria" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["gap_por_categoria"], ancho_cm=13, alto_max_cm=10))
            elementos.append(Spacer(1, 0.2 * cm))
        if "gap_por_vendedor" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["gap_por_vendedor"], ancho_cm=16, alto_max_cm=13))
            elementos.append(Spacer(1, 0.2 * cm))
        if "gap_vendedor_status" in rutas_graficas:
            elementos.append(Paragraph(
                "Las mismas solicitudes con GAP, desglosadas por vendedor y por el estatus "
                "en el que cerraron.",
                e["cuerpo"]
            ))
            elementos.append(imagen_ajustada(rutas_graficas["gap_vendedor_status"], ancho_cm=16, alto_max_cm=13))
            elementos.append(Spacer(1, 0.2 * cm))
        if "gap_financiado_vend" in rutas_graficas:
            elementos.append(Paragraph(
                "Por último, la colocación de GAP dentro de los créditos ya <b>FINANCIADOS</b>: "
                "es el indicador más relevante, porque ese GAP ya está vendido.",
                e["cuerpo"]
            ))
            elementos.append(imagen_ajustada(rutas_graficas["gap_financiado_vend"], ancho_cm=16, alto_max_cm=13))
        elementos.append(Spacer(1, 0.4 * cm))

    # --- 6. Modelos de vehículo más solicitados ---
    if "modelos" in rutas_graficas:
        elementos.append(Paragraph("6. Modelos de Vehículo Más Solicitados", e["h2"]))
        texto_modelos = textos["modelos"]
        if modelo_top:
            texto_modelos += f" <b>{modelo_top}</b> encabeza la lista con {modelo_top_val} solicitudes."
        elementos.append(Paragraph(texto_modelos, e["cuerpo"]))
        elementos.append(imagen_ajustada(rutas_graficas["modelos"], ancho_cm=16, alto_max_cm=13))
        elementos.append(Spacer(1, 0.4 * cm))
    return elementos
