# -*- coding: utf-8 -*-
"""Resumen del Reporte_Mensual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1To43cx4YeV2A6RIMvRixg9tMQOHBrnvo
"""

# -*- coding: utf-8 -*-
"""Resumen del Reporte_Mensual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1To43cx4YeV2A6RIMvRixg9tMQOHBrnvo
"""

# -*- coding: utf-8 -*-
"""Resumen del Reporte_Mensual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1To43cx4YeV2A6RIMvRixg9tMQOHBrnvo
"""

# -*- coding: utf-8 -*-
"""Bitacora_Diaria_O_Mensual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1To43cx4YeV2A6RIMvRixg9tMQOHBrnvo
"""

# -*- coding: utf-8 -*-
"""Analisis_Bitacora_Verbal.ipynb

Reporte NARRATIVO de la Bitácora de Solicitudes (AUTOEXPRESS INBURSA · MG Motor)

Esta es la versión "verbal" del reporte: conserva exactamente el mismo
análisis de datos y las mismas gráficas del script original
(ANALISIS_BITACORA_DIARIA_V2_COMPLETO), pero en vez de un PDF con páginas
de texto monoespaciado, arma un reporte redactado -con resumen ejecutivo,
tarjetas KPI, tablas con estilo y las gráficas incrustadas junto a su
explicación- igual que el "Reporte de Expedientes Faltantes".

Corre en Google Colab (sube el archivo) o localmente (pide la ruta).
"""

import warnings
warnings.filterwarnings("ignore")

import os
import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib.colors import LinearSegmentedColormap, to_rgb

try:
    from google.colab import files  # noqa
    EN_COLAB = True
except ImportError:
    EN_COLAB = False

try:
    from IPython.display import display
except ImportError:
    display = print

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)

# Librería para generar el PDF (se instala si no está disponible en el entorno)
try:
    import reportlab
except ImportError:
    import subprocess
    subprocess.run(['pip', 'install', '-q', 'reportlab'])

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import cm
from reportlab.lib import colors as rl_colors
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image,
    PageBreak, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY


# =======================================================================
# 1) PALETA DE COLORES — ROJOS MG (misma paleta que el script original,
#    con una tonalidad pálida adicional para el zebrado de tablas)
# =======================================================================
MG_ROJO          = "#E4002B"   # rojo principal de marca
MG_ROJO_OSCURO   = "#7A0019"
INBURSA_AZUL     = "#191970"
MG_ROJO_MEDIO    = "#B3001B"
MG_ROJO_CLARO    = "#FF6B6B"
MG_ROJO_PASTEL   = "#FFB3B3"
MG_ROJO_PALIDO   = "#FBE7E9"   # fondo muy claro — usado con moderación en acentos
MG_GRIS_OSCURO   = "#2B2B2B"
MG_GRIS_CLARO    = "#EAEAEA"
BLANCO           = "#FFFFFF"

# --- Tonos neutros del rediseño corporativo/moderno (misma familia que
#     el reporte de Avance Preliminar) ---
GRIS_TEXTO_SEC   = "#6B7280"   # texto secundario (labels, notas, pie)
GRIS_LINEA       = "#E3E5E9"   # reglas y bordes discretos
GRIS_ZEBRA       = "#F6F7F9"   # fondo de fila alterna en tablas (casi blanco)
AZUL_PALIDO      = "#EEF0F8"   # fondo muy sutil para acentos en azul Inbursa

# gradiente de rojos usado en la mayoría de las gráficas (oscuro -> claro)
PALETA_ROJOS = ["#7A0019", "#9E001F", "#C10024", "#E4002B",
                 "#F1354D", "#FF6B6B", "#FF9B9B", "#FFC7C7"]

_CMAP_ROJOS = LinearSegmentedColormap.from_list("rojos_mg", PALETA_ROJOS)


# =======================================================================
# 1B) FUENTE (TIPOGRAFÍA) DEL REPORTE — para cambiarla, edita SOLO la
#     línea de FUENTE_BASE. Todo el PDF (títulos, tablas, tarjetas KPI,
#     encabezado y pie de página) la toma de aquí, así que ya no hay que
#     buscar "Helvetica" por todo el archivo cada vez que se quiera
#     cambiar la tipografía.
#     Opciones ya listas, sin instalar nada extra:
#       "Helvetica"  -> paloseco (la que traía el reporte original)
#       "Times"      -> con serifas, look más editorial/formal
#       "Courier"    -> monoespaciada
#     Si más adelante quieres una fuente propia de la marca (un .ttf),
#     regístrala con pdfmetrics.registerFont(TTFont(...)) y agrega su
#     nombre a _FUENTES_DISPONIBLES.
# =======================================================================
FUENTE_BASE = "Helvetica"   # <-- CAMBIA AQUÍ LA FUENTE DE TODO EL PDF

_FUENTES_DISPONIBLES = {
    "Helvetica": {"regular": "Helvetica",   "bold": "Helvetica-Bold",
                  "italica": "Helvetica-Oblique", "bold_italica": "Helvetica-BoldOblique"},
    "Times":     {"regular": "Times-Roman", "bold": "Times-Bold",
                  "italica": "Times-Italic",      "bold_italica": "Times-BoldItalic"},
    "Courier":   {"regular": "Courier",     "bold": "Courier-Bold",
                  "italica": "Courier-Oblique",    "bold_italica": "Courier-BoldOblique"},
}
_fuente_activa = _FUENTES_DISPONIBLES.get(FUENTE_BASE, _FUENTES_DISPONIBLES["Helvetica"])
FUENTE_REGULAR      = _fuente_activa["regular"]
FUENTE_BOLD         = _fuente_activa["bold"]
FUENTE_ITALICA      = _fuente_activa["italica"]
FUENTE_BOLD_ITALICA = _fuente_activa["bold_italica"]


# colores fijos por categoría de status (para que siempre se vea igual)
# FINANCIADO = crédito ya formalizado y dispersado (el cierre "más fuerte").
# APROBADO   = crédito aprobado, aún no formalizado/dispersado.
COLOR_CATEGORIA = {
    "FINANCIADO":  MG_ROJO_OSCURO,
    "APROBADO":    MG_ROJO,
    "CONTRAPROPUESTA":  MG_GRIS_OSCURO,
    "RECHAZADO":   MG_ROJO_PASTEL,
}

# orden consistente en tablas y gráficas: del cierre más fuerte al más débil
ORDEN_CATEGORIAS = ["FINANCIADO", "APROBADO", "CONTRAPROPUESTA", "RECHAZADO"]

NOMBRE_EMPRESA = "AUTOEXPRESS INBURSA"
SUBTITULO_EMPRESA = "MG Colima PYD"
NOMBRE_ANALISTA = "Christian Ramos"


def _gradiente(n):
    """Genera n colores en degradado continuo (oscuro -> claro) sin repetirse,
    sin importar cuántas barras haya."""
    if n <= 1:
        return [MG_ROJO]
    valores = np.linspace(0.0, 0.82, n)
    return [_CMAP_ROJOS(v) for v in valores]


def _color_texto_legible(color_fondo):
    """Devuelve blanco o gris oscuro según qué tan claro sea el color de fondo,
    para que el texto siempre se pueda leer."""
    r, g, b = to_rgb(color_fondo)
    luminancia = 0.299 * r + 0.587 * g + 0.114 * b
    return "white" if luminancia < 0.6 else MG_GRIS_OSCURO


plt.rcParams.update({
    "figure.facecolor":  "white",
    "axes.facecolor":    "white",
    "axes.edgecolor":    GRIS_LINEA,
    "axes.labelcolor":   GRIS_TEXTO_SEC,
    "text.color":        MG_GRIS_OSCURO,
    "xtick.color":       GRIS_TEXTO_SEC,
    "ytick.color":       GRIS_TEXTO_SEC,
    "font.size":         10,
    "axes.titlesize":    12.5,
    "axes.titleweight":  "bold",
    "axes.titlecolor":   MG_GRIS_OSCURO,
    "axes.titlepad":     14,
    "axes.labelsize":    9.5,
    "axes.linewidth":    0.8,
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "axes.spines.left":  True,
    "axes.grid":         False,
    "xtick.labelsize":   9,
    "ytick.labelsize":   9,
    "legend.fontsize":   9,
    "legend.frameon":    False,
})

# Carpeta temporal para las imágenes de las gráficas que se insertarán en el PDF
CARPETA_GRAFICAS = "graficas_temp_bitacora"
os.makedirs(CARPETA_GRAFICAS, exist_ok=True)


# =======================================================================
# 2) CARGA DEL ARCHIVO
# =======================================================================
def cargar_archivo(ruta_local=None):
    """
    Sube (en Colab) o abre (fuera de Colab) el archivo Excel de la
    bitácora y devuelve un DataFrame de pandas con la hoja elegida.
    """
    if ruta_local:
        nombre_archivo = ruta_local
    elif EN_COLAB:
        print("Sube el archivo Excel de la bitácora de solicitudes...")
        subido = files.upload()
        nombre_archivo = list(subido.keys())[0]
    else:
        nombre_archivo = input("Ruta del archivo Excel: ").strip()

    xls = pd.ExcelFile(nombre_archivo)
    hoja = xls.sheet_names[0]
    if len(xls.sheet_names) > 1:
        print(f"El archivo tiene varias hojas: {xls.sheet_names}")
        elegida = input(f"¿Cuál analizar? (Enter = '{hoja}'): ").strip()
        hoja = elegida if elegida else hoja

    df = pd.read_excel(nombre_archivo, sheet_name=hoja)
    print(f"Archivo cargado: {nombre_archivo}  |  Hoja: {hoja}  |  {len(df)} solicitudes\n")
    return df


# =======================================================================
# 3) LIMPIEZA Y NORMALIZACIÓN DE DATOS
# =======================================================================
COLUMNAS_ESPERADAS = [
    "Folio CCK", "STATUS", "Nombre Completo", "Fecha de Nacimiento",
    "Teléfono Móvil", "Correo Electrónico", "Nombre del Vendedor",
    "Marca", "Vehículo", "Año Modelo", "Precio Venta (c/IVA)",
    "Enganche", "¿Tiene GAP?", "Monto GAP", "Plazo (meses)",
    "Tasa Interés Anual", "Monto Total a Financiar",
    "Mensualidad Mínima", "Mensualidad Máxima",
]

COLUMNAS_MONEDA = [
    "Precio Venta (c/IVA)", "Enganche", "Monto GAP",
    "Monto Total a Financiar", "Mensualidad Mínima", "Mensualidad Máxima",
]

COLUMNAS_PORCENTAJE = ["Tasa Interés Anual"]

# Status que se consideran APROBADO, FINANCIADO y RECHAZADO se manejan cada
# uno por separado (no se combinan). Cualquier otro status (CONTRAPROPUESTA,
# EN PROCESO, PENDIENTE, etc.) se agrupa como "CONTRAPROPUESTA". Ajusta estas
# listas si tu operación usa otras palabras para lo mismo.
STATUS_APROBADO   = ["APROBADO"]
STATUS_FINANCIADO = ["FINANCIADOS", "FINANCIADO"]
STATUS_RECHAZADOS = ["RECHAZADO", "RECHAZADOS", "CANCELADO", "CANCELADOS"]


def _limpiar_moneda(serie):
    return (
        serie.astype(str)
             .str.replace(r"[\$,]", "", regex=True)
             .str.strip()
             .replace({"nan": np.nan, "": np.nan, "None": np.nan})
             .astype(float)
    )


def _limpiar_porcentaje(serie):
    """Convierte la columna de tasa de interés a número (ej. "14.99%" -> 14.99).

    OJO — esto es lo que estaba descuadrando la tasa de FINANCIADOS:
    en Excel una celda puede guardar "14.99%" como TEXTO, o como NÚMERO
    con formato de celda "0.00%" (en ese caso Excel guarda por dentro la
    fracción 0.1499, sin el símbolo %). Si sólo se le quita el "%" al
    texto, esas celdas numéricas se quedan en 0.1499 en vez de 14.99 y
    arruinan cualquier promedio. Por eso aquí se revisa el valor
    ORIGINAL de cada celda (no su versión ya convertida a texto) y, si
    es un número <= 1, se asume que viene en formato fracción de Excel
    y se multiplica x100.
    """
    def _convertir(valor):
        if pd.isna(valor):
            return np.nan
        if isinstance(valor, str):
            texto = valor.strip().replace("%", "")
            if texto in ("", "nan", "None"):
                return np.nan
            try:
                return float(texto)
            except ValueError:
                return np.nan
        try:
            numero = float(valor)
        except (TypeError, ValueError):
            return np.nan
        return numero * 100 if numero <= 1 else numero

    return serie.apply(_convertir)


def clasificar_status(status):
    s = str(status).strip().upper()
    if s in STATUS_FINANCIADO:
        return "FINANCIADO"
    if s in STATUS_APROBADO:
        return "APROBADO"
    if s in STATUS_RECHAZADOS:
        return "RECHAZADO"
    return "CONTRAPROPUESTA"


def limpiar_datos(df_original):
    df = df_original.copy()
    df.columns = [str(c).strip() for c in df.columns]

    faltantes = [c for c in COLUMNAS_ESPERADAS if c not in df.columns]
    if faltantes:
        print(f"Aviso: no se encontraron estas columnas esperadas: {faltantes}")
        print("El script seguirá, pero los análisis que dependan de ellas se omitirán.\n")

    for col in COLUMNAS_MONEDA:
        if col in df.columns:
            df[col] = _limpiar_moneda(df[col])

    for col in COLUMNAS_PORCENTAJE:
        if col in df.columns:
            crudo = df[col]
            df[col] = _limpiar_porcentaje(crudo)
            # Aviso de calidad de datos: celdas numéricas guardadas con
            # formato de porcentaje de Excel (fracción, ej. 0.1499) en vez
            # de texto "14.99%". El script ya las corrige automáticamente,
            # pero conviene saber cuáles filas venían así en el archivo fuente.
            es_formato_distinto = crudo.apply(
                lambda v: not isinstance(v, str) and pd.notna(v) and float(v) <= 1
            )
            if es_formato_distinto.any():
                idx = crudo[es_formato_distinto].index
                folios = (
                    df.loc[idx, "Folio CCK"].tolist() if "Folio CCK" in df.columns else list(idx)
                )
                print(
                    f"Aviso: {len(folios)} fila(s) en '{col}' tenían formato de celda "
                    f"distinto (número en vez de texto, ej. 0.1499 en vez de \"14.99%\") "
                    f"y se corrigieron automáticamente. Folios: {folios}"
                )

    if "STATUS" in df.columns:
        df["STATUS"] = df["STATUS"].astype(str).str.strip().str.upper()
        df["Categoria"] = df["STATUS"].apply(clasificar_status)

    if "Nombre del Vendedor" in df.columns:
        df["Nombre del Vendedor"] = (
            df["Nombre del Vendedor"].astype(str).str.strip().str.title()
        )

    if "Marca" in df.columns:
        df["Marca"] = df["Marca"].astype(str).str.strip().str.upper().replace("NAN", np.nan)

    if "Vehículo" in df.columns:
        df["Vehículo"] = df["Vehículo"].astype(str).str.strip().replace("None", np.nan)

    if "Fecha de Nacimiento" in df.columns:
        df["Fecha de Nacimiento"] = pd.to_datetime(
            df["Fecha de Nacimiento"], dayfirst=True, errors="coerce"
        )
        hoy = pd.Timestamp.today()
        df["Edad"] = ((hoy - df["Fecha de Nacimiento"]).dt.days // 365.25)

    if "¿Tiene GAP?" in df.columns:
        df["¿Tiene GAP?"] = df["¿Tiene GAP?"].astype(str).str.strip().str.upper()

    return df


# =======================================================================
# 4) CÁLCULOS — RESUMEN GENERAL / KPIs DEL PERIODO
#    (imprime en consola igual que antes, y además devuelve un
#    diccionario con los datos clave para redactar el reporte narrativo)
# =======================================================================
def resumen_general(df):
    print("=" * 72)
    print(" RESUMEN GENERAL DEL PERIODO")
    print("=" * 72)

    total = len(df)
    r = {"total": total}
    print(f"Total de solicitudes ingresadas: {total}\n")

    if "Categoria" in df.columns:
        conteo_cat  = df["Categoria"].value_counts()
        financiados = int(conteo_cat.get("FINANCIADO", 0))
        aprobados   = int(conteo_cat.get("APROBADO", 0))
        rechazados  = int(conteo_cat.get("RECHAZADO", 0))
        en_tramite  = int(conteo_cat.get("CONTRAPROPUESTA", 0))

        print(f"  Financiadas (crédito dispersado) : {financiados:>3}  ({financiados/total*100:5.1f}%)")
        print(f"  Aprobadas (aún sin dispersar)    : {aprobados:>3}  ({aprobados/total*100:5.1f}%)")
        print(f"  Rechazadas                       : {rechazados:>3}  ({rechazados/total*100:5.1f}%)")
        print(f"  CONTRAPROPUESTA / negociación         : {en_tramite:>3}  ({en_tramite/total*100:5.1f}%) ")

        print("\nDesglose detallado por Estatus:")
        for status, cnt in df["STATUS"].value_counts().items():
            print(f"    - {status:<20}: {cnt:>3}  ({cnt/total*100:5.1f}%) ")

        r.update({
            "financiados": financiados, "aprobados": aprobados,
            "rechazados": rechazados, "en_tramite": en_tramite,
            "desglose_status": df["STATUS"].value_counts(),
        })
    else:
        financiados = aprobados = rechazados = en_tramite = 0

    monto_col = "Monto Total a Financiar"
    if monto_col in df.columns:
        monto_total = df[monto_col].sum()
        r["monto_total"] = monto_total
        print(f"\nMonto total a financiar (TODAS las solicitudes)  : ${monto_total:,.2f}")

        if "Categoria" in df.columns:
            monto_financiado = df.loc[df["Categoria"] == "FINANCIADO", monto_col].sum()
            monto_aprobado   = df.loc[df["Categoria"] == "APROBADO", monto_col].sum()
            r["monto_financiado"] = monto_financiado
            r["monto_aprobado"] = monto_aprobado

            print(f"Monto FINANCIADO (crédito ya dispersado)          : ${monto_financiado:,.2f}")
            if financiados:
                ticket_financiado = df.loc[df["Categoria"] == "FINANCIADO", monto_col].mean()
                r["ticket_financiado"] = ticket_financiado
                print(f"  Ticket promedio financiadas                     : ${ticket_financiado:,.2f}")

            print(f"Monto APROBADO (aún sin dispersar)                : ${monto_aprobado:,.2f}")
            if aprobados:
                ticket_aprobado = df.loc[df["Categoria"] == "APROBADO", monto_col].mean()
                r["ticket_aprobado"] = ticket_aprobado
                print(f"  Ticket promedio aprobadas                       : ${ticket_aprobado:,.2f}")

            print(f"Monto conjunto (Aprobado + Financiado)            : ${monto_financiado + monto_aprobado:,.2f}")

    if "Enganche" in df.columns and "Precio Venta (c/IVA)" in df.columns:
        pct_enganche = (df["Enganche"] / df["Precio Venta (c/IVA)"] * 100).mean()
        r["pct_enganche"] = pct_enganche
        print(f"\n% de enganche promedio sobre precio de venta      : {pct_enganche:.1f}%")

    if "Plazo (meses)" in df.columns:
        r["plazo_promedio"] = df["Plazo (meses)"].mean()
        print(f"Plazo promedio solicitado                         : {df['Plazo (meses)'].mean():.0f} meses")

    if "Tasa Interés Anual" in df.columns:
        r["tasa_promedio"] = df["Tasa Interés Anual"].mean()
        print(f"Tasa de interés anual promedio                    : {df['Tasa Interés Anual'].mean():.2f}%")

    if "¿Tiene GAP?" in df.columns:
        pct_gap = (df["¿Tiene GAP?"] == "SI").mean() * 100
        r["pct_gap"] = pct_gap
        r["n_gap"] = int((df["¿Tiene GAP?"] == "SI").sum())
        print(f"% de solicitudes con GAP                          : {pct_gap:.1f}%")

    if "Edad" in df.columns and df["Edad"].notna().any():
        r["edad_promedio"] = df["Edad"].mean()

    # filas con datos incompletos (p.ej. folio sin vehículo asignado aún)
    cols_clave = [c for c in ["Marca", "Vehículo", "Monto Total a Financiar"] if c in df.columns]
    if cols_clave:
        incompletas = df[cols_clave].isna().any(axis=1).sum()
        r["incompletas"] = int(incompletas)
        if incompletas:
            print(f"\nSolicitudes con datos incompletos (vehículo/monto sin capturar): {incompletas}")

    print()
    return r


# =======================================================================
# 5) CÁLCULOS — ANÁLISIS POR VENDEDOR
# =======================================================================
def analisis_por_vendedor(df):
    if "Nombre del Vendedor" not in df.columns:
        return None

    print("=" * 72)
    print(" ANÁLISIS POR VENDEDOR")
    print("=" * 72)

    total_por_vendedor = df.groupby("Nombre del Vendedor").size().rename("Total")

    tabla = pd.DataFrame({"Total": total_por_vendedor})

    if "Categoria" in df.columns:
        pivote = pd.crosstab(df["Nombre del Vendedor"], df["Categoria"])
        for col in ORDEN_CATEGORIAS:
            if col not in pivote.columns:
                pivote[col] = 0
        tabla = tabla.join(pivote[ORDEN_CATEGORIAS])
        tabla["% Aprobación"] = (tabla["APROBADO"] / tabla["Total"] * 100).round(1)
        tabla["% Financiado"] = (tabla["FINANCIADO"] / tabla["Total"] * 100).round(1)

    if "Monto Total a Financiar" in df.columns and "Categoria" in df.columns:
        monto_financiado = (
            df[df["Categoria"] == "FINANCIADO"]
            .groupby("Nombre del Vendedor")["Monto Total a Financiar"]
            .sum()
            .rename("Monto Financiado ($)")
        )
        monto_aprobado = (
            df[df["Categoria"] == "APROBADO"]
            .groupby("Nombre del Vendedor")["Monto Total a Financiar"]
            .sum()
            .rename("Monto Aprobado ($)")
        )
        tabla = tabla.join(monto_financiado).join(monto_aprobado)
        tabla[["Monto Financiado ($)", "Monto Aprobado ($)"]] = tabla[
            ["Monto Financiado ($)", "Monto Aprobado ($)"]
        ].fillna(0)

    if "¿Tiene GAP?" in df.columns:
        gap_total_v = df[df["¿Tiene GAP?"] == "SI"].groupby("Nombre del Vendedor").size()
        tabla["GAP Total"] = gap_total_v.reindex(tabla.index).fillna(0).astype(int)
        if "Categoria" in df.columns:
            gap_fin_v = (
                df[(df["Categoria"] == "FINANCIADO") & (df["¿Tiene GAP?"] == "SI")]
                .groupby("Nombre del Vendedor").size()
            )
            tabla["GAP Financiado"] = gap_fin_v.reindex(tabla.index).fillna(0).astype(int)

    tabla = tabla.sort_values("Total", ascending=False)
    display(tabla)
    print()
    return tabla


# =======================================================================
# 6) CÁLCULOS — ANÁLISIS FINANCIERO COMPARATIVO POR CATEGORÍA
# =======================================================================
def analisis_financiero_por_categoria(df):
    if "Categoria" not in df.columns:
        return None

    print("=" * 72)
    print(" COMPARATIVO FINANCIERO: FINANCIADO vs APROBADO vs CONTRAPROPUESTA vs RECHAZADO")
    print("=" * 72)

    columnas_interes = [c for c in [
        "Precio Venta (c/IVA)", "Enganche", "Monto Total a Financiar",
        "Plazo (meses)", "Tasa Interés Anual",
    ] if c in df.columns]

    if not columnas_interes:
        return None

    tabla = df.groupby("Categoria")[columnas_interes].mean().round(2)
    orden_presente = [c for c in ORDEN_CATEGORIAS if c in tabla.index]
    tabla = tabla.reindex(orden_presente)

    if "Enganche" in df.columns and "Precio Venta (c/IVA)" in df.columns:
        tabla["% Enganche prom."] = (
            (df["Enganche"] / df["Precio Venta (c/IVA)"] * 100)
            .groupby(df["Categoria"]).mean().round(1)
        ).reindex(orden_presente)

    if "¿Tiene GAP?" in df.columns:
        tabla["% con GAP"] = (
            (df["¿Tiene GAP?"] == "SI")
            .groupby(df["Categoria"]).mean().mul(100).round(1)
        ).reindex(orden_presente)

    display(tabla)
    print("\nEsta tabla ayuda a identificar focos de atención: por ejemplo, si las")
    print("solicitudes RECHAZADAS piden un % de enganche más bajo, un monto a")
    print("financiar más alto, o llevan menos GAP que las APROBADAS o FINANCIADAS,")
    print("ese es un patrón a vigilar.\n")
    return tabla


# =======================================================================
# 7) GRÁFICAS
#    Mismas gráficas que el script original y con el mismo estilo visual.
#    Cada función ahora acepta guardar_como=<ruta.png>: si se indica,
#    guarda la imagen en disco (para incrustarla en el PDF) además de
#    mostrarla en pantalla como antes. Devuelve la ruta guardada (o None).
# =======================================================================
def _formato_miles(ax, eje="y"):
    formatter = mticker.FuncFormatter(lambda x, _: f"{x:,.0f}")
    if eje == "y":
        ax.yaxis.set_major_formatter(formatter)
    else:
        ax.xaxis.set_major_formatter(formatter)


def _lista_vendedores_por_categoria(df, categoria, max_nombres=4):
    """Devuelve un string compacto con los primeros nombres de los
    vendedores que tienen solicitudes en esa categoría (para no saturar
    la leyenda con nombres completos)."""
    nombres = (
        df.loc[df["Categoria"] == categoria, "Nombre del Vendedor"]
        .dropna().unique().tolist()
    )
    primeros_nombres = sorted({n.split()[0] for n in nombres if n and n != "Nan"})
    if not primeros_nombres:
        return "—"
    if len(primeros_nombres) > max_nombres:
        extra = len(primeros_nombres) - max_nombres
        return ", ".join(primeros_nombres[:max_nombres]) + f" +{extra} más"
    return ", ".join(primeros_nombres)


def _guardar_si_procede(fig, guardar_como):
    if guardar_como:
        fig.savefig(guardar_como, dpi=150, bbox_inches="tight", facecolor="white")
    return guardar_como


def grafica_status(df, guardar_como=None):
    """Barras: número de solicitudes por STATUS."""
    if "STATUS" not in df.columns:
        return None
    conteo = df["STATUS"].value_counts().sort_values(ascending=False)

    fig, ax = plt.subplots(figsize=(8, 5))
    colores = _gradiente(len(conteo))
    barras = ax.bar(conteo.index, conteo.values, color=colores, edgecolor="white")

    for barra, valor in zip(barras, conteo.values):
        ax.text(barra.get_x() + barra.get_width() / 2, valor + max(conteo.values) * 0.01,
                 f"{valor}\n({valor/conteo.sum()*100:.0f}%)", ha="center", va="bottom", fontsize=9)

    ax.set_title("Solicitudes por Estatus")
    ax.set_ylabel("Número de solicitudes")
    ax.set_ylim(0, max(conteo.values) * 1.2)
    plt.xticks(rotation=15)
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como


def grafica_dona_categoria(df, guardar_como=None):
    """Dona: proporción Financiado vs Aprobado vs CONTRAPROPUESTA vs Rechazado,
    con los nombres (primer nombre) de los vendedores que aportan a cada
    categoría dentro de la leyenda."""
    if "Categoria" not in df.columns:
        return None
    conteo_bruto = df["Categoria"].value_counts()
    orden_presente = [c for c in ORDEN_CATEGORIAS if c in conteo_bruto.index]
    conteo = conteo_bruto.reindex(orden_presente)
    colores = [COLOR_CATEGORIA.get(c, MG_GRIS_CLARO) for c in conteo.index]

    fig, ax = plt.subplots(figsize=(8, 7))
    wedges, _, autotextos = ax.pie(
        conteo.values, labels=None, autopct="%1.0f%%", pctdistance=0.8,
        colors=colores, startangle=90, wedgeprops=dict(width=0.42, edgecolor="white"),
        textprops=dict(fontweight="bold"),
    )
    for autotexto, color_rebanada in zip(autotextos, colores):
        autotexto.set_color(_color_texto_legible(color_rebanada))

    etiquetas = []
    for cat, valor in zip(conteo.index, conteo.values):
        etiqueta = f"{cat} ({valor})"
        if "Nombre del Vendedor" in df.columns:
            etiqueta += f"\n   {_lista_vendedores_por_categoria(df, cat)}"
        etiquetas.append(etiqueta)

    ax.legend(wedges, etiquetas, loc="upper center", bbox_to_anchor=(0.5, -0.02),
               frameon=False, fontsize=9, ncol=1, labelspacing=1.2)
    ax.set_title("Distribución General de Solicitudes")
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como


def grafica_vendedores(df, guardar_como=None):
    """Barras horizontales: total de solicitudes por vendedor."""
    if "Nombre del Vendedor" not in df.columns:
        return None
    conteo = df["Nombre del Vendedor"].value_counts().sort_values(ascending=True)

    fig, ax = plt.subplots(figsize=(8, max(4, len(conteo) * 0.5)))
    colores = list(reversed(_gradiente(len(conteo))))
    ax.barh(conteo.index, conteo.values, color=colores, edgecolor="white")

    for i, valor in enumerate(conteo.values):
        ax.text(valor + max(conteo.values) * 0.01, i, str(valor), va="center", fontsize=9)

    ax.set_title("Solicitudes por Vendedor")
    ax.set_xlabel("Número de solicitudes")
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como


def grafica_vendedor_status(df, guardar_como=None):
    """Barras horizontales apiladas: desempeño de cada vendedor por categoría."""
    if "Nombre del Vendedor" not in df.columns or "Categoria" not in df.columns:
        return None

    pivote = pd.crosstab(df["Nombre del Vendedor"], df["Categoria"])
    orden_cols = [c for c in ORDEN_CATEGORIAS if c in pivote.columns]
    pivote = pivote[orden_cols]
    pivote["Total"] = pivote.sum(axis=1)
    pivote = pivote.sort_values("Total", ascending=True).drop(columns="Total")

    fig, ax = plt.subplots(figsize=(9, max(4, len(pivote) * 0.55) + 0.8))
    izquierda = np.zeros(len(pivote))
    for col in orden_cols:
        valores = pivote[col].values
        ax.barh(pivote.index, valores, left=izquierda,
                 color=COLOR_CATEGORIA.get(col, MG_GRIS_CLARO), label=col, edgecolor="white")
        izquierda += valores

    ax.set_title("Desempeño por Vendedor\n(Financiado / Aprobado / Contrapropuesta / Rechazado)")
    ax.set_xlabel("Número de solicitudes")
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.12), frameon=False, ncol=4)
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como


def grafica_monto_por_vendedor(df, guardar_como=None):
    """Barras horizontales agrupadas: monto colocado por vendedor,
    separando APROBADO (aún sin dispersar) de FINANCIADO (ya dispersado)."""
    if not {"Nombre del Vendedor", "Categoria", "Monto Total a Financiar"}.issubset(df.columns):
        return None

    monto_aprobado = (
        df[df["Categoria"] == "APROBADO"]
        .groupby("Nombre del Vendedor")["Monto Total a Financiar"].sum()
    )
    monto_financiado = (
        df[df["Categoria"] == "FINANCIADO"]
        .groupby("Nombre del Vendedor")["Monto Total a Financiar"].sum()
    )

    vendedores = sorted(
        set(monto_aprobado.index) | set(monto_financiado.index),
        key=lambda v: monto_aprobado.get(v, 0) + monto_financiado.get(v, 0),
    )
    if not vendedores:
        return None

    valores_aprobado = np.array([monto_aprobado.get(v, 0) for v in vendedores])
    valores_financiado = np.array([monto_financiado.get(v, 0) for v in vendedores])
    maximo = max(valores_aprobado.max(), valores_financiado.max(), 1)

    y = np.arange(len(vendedores))
    alto = 0.36

    fig, ax = plt.subplots(figsize=(9, max(4, len(vendedores) * 0.65)))
    ax.barh(y + alto / 2, valores_aprobado, height=alto, color=MG_ROJO,
             edgecolor="white", label="Aprobado (sin dispersar)")
    ax.barh(y - alto / 2, valores_financiado, height=alto, color=MG_ROJO_OSCURO,
             edgecolor="white", label="Financiado (dispersado)")

    for yi, valor in zip(y + alto / 2, valores_aprobado):
        if valor > 0:
            ax.text(valor + maximo * 0.015, yi, f"${valor:,.0f}", va="center", fontsize=8)
    for yi, valor in zip(y - alto / 2, valores_financiado):
        if valor > 0:
            ax.text(valor + maximo * 0.015, yi, f"${valor:,.0f}", va="center", fontsize=8)

    ax.set_yticks(y)
    ax.set_yticklabels(vendedores)
    ax.set_xlim(0, maximo * 1.18)
    _formato_miles(ax, eje="x")

    ax.set_title("Monto Colocado por Vendedor\nAprobado vs Financiado")
    ax.set_xlabel("Monto a financiar ($ MXN)")
    ax.legend(loc="lower right", frameon=False)
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como


def grafica_modelos(df, guardar_como=None):
    """Barras horizontales: modelos de vehículo más solicitados."""
    if "Vehículo" not in df.columns:
        return None
    conteo_completo = df["Vehículo"].dropna().value_counts()
    if conteo_completo.empty:
        return None

    TOP_N = 10
    recortado = len(conteo_completo) > TOP_N
    conteo = conteo_completo.head(TOP_N).sort_values(ascending=True)

    fig, ax = plt.subplots(figsize=(8, max(4, len(conteo) * 0.4)))
    colores = list(reversed(_gradiente(len(conteo))))
    ax.barh(conteo.index, conteo.values, color=colores, edgecolor="white")

    for i, valor in enumerate(conteo.values):
        ax.text(valor + max(conteo.values) * 0.02, i, str(valor), va="center", fontsize=9)

    titulo = "Modelos MÁS Solicitados"
    if recortado:
        titulo += f" (Top {TOP_N})"
    ax.set_title(titulo)
    ax.set_xlabel("Número de solicitudes")
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como



def grafica_gap_por_categoria(df, guardar_como=None):
    """Barras: % de solicitudes que llevan GAP, por categoría de status."""
    if "Categoria" not in df.columns or "¿Tiene GAP?" not in df.columns:
        return None

    pct_gap = (
        (df["¿Tiene GAP?"] == "SI").groupby(df["Categoria"]).mean().mul(100)
    )
    orden_presente = [c for c in ORDEN_CATEGORIAS if c in pct_gap.index]
    pct_gap = pct_gap.reindex(orden_presente)
    if pct_gap.empty:
        return None

    colores = [COLOR_CATEGORIA.get(c, MG_GRIS_CLARO) for c in pct_gap.index]

    fig, ax = plt.subplots(figsize=(7, 5))
    barras = ax.bar(pct_gap.index, pct_gap.values, color=colores, edgecolor="white")

    for barra, valor in zip(barras, pct_gap.values):
        ax.text(barra.get_x() + barra.get_width() / 2, valor + 2,
                 f"{valor:.0f}%", ha="center", va="bottom", fontsize=9, fontweight="bold")

    ax.set_title("% de Solicitudes con GAP", pad=14)
    ax.set_ylabel("% con GAP")
    ax.set_ylim(0, 120)
    plt.xticks(rotation=10)
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como


def grafica_gap_por_vendedor_total(df, guardar_como=None):
    """Barras horizontales agrupadas: solicitudes con GAP por vendedor,
    comparadas contra el total de solicitudes de cada vendedor (para ver
    de un vistazo qué proporción de las solicitudes de cada quien llevó GAP)."""
    if "Nombre del Vendedor" not in df.columns or "¿Tiene GAP?" not in df.columns:
        print("Las columnas 'Nombre del Vendedor' o '¿Tiene GAP?' no están presentes.")
        return None

    df_gap = df[df["¿Tiene GAP?"] == "SI"].copy()
    if df_gap.empty:
        print("No hay solicitudes con GAP para graficar.")
        return None

    conteo_gap = df_gap["Nombre del Vendedor"].value_counts()
    conteo_total = df["Nombre del Vendedor"].value_counts()

    # Se usa el total de solicitudes (no solo las que tienen GAP) para que
    # aparezcan TODOS los vendedores, incluso los que tuvieron 0 GAP.
    vendedores = conteo_total.sort_values(ascending=True).index.tolist()
    valores_total = np.array([conteo_total.get(v, 0) for v in vendedores])
    valores_gap = np.array([conteo_gap.get(v, 0) for v in vendedores])
    maximo = max(valores_total.max(), valores_gap.max(), 1)

    y = np.arange(len(vendedores))
    alto = 0.36

    fig, ax = plt.subplots(figsize=(9, max(4, len(vendedores) * 0.65)))
    ax.barh(y + alto / 2, valores_total, height=alto, color=MG_GRIS_CLARO,
             edgecolor="white", label="Total de solicitudes")
    ax.barh(y - alto / 2, valores_gap, height=alto, color=MG_ROJO,
             edgecolor="white", label="Con GAP")

    for yi, valor in zip(y + alto / 2, valores_total):
        ax.text(valor + maximo * 0.015, yi, str(valor), va="center", fontsize=8)
    for yi, valor in zip(y - alto / 2, valores_gap):
        ax.text(valor + maximo * 0.015, yi, str(valor), va="center", fontsize=8)

    ax.set_yticks(y)
    ax.set_yticklabels(vendedores)
    ax.set_xlim(0, maximo * 1.18)

    ax.set_title("Solicitudes con GAP por Vendedor\n(vs. Total de Solicitudes)")
    ax.set_xlabel("Número de solicitudes")
    ax.legend(loc="lower right", frameon=False)
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como


def grafica_gap_por_vendedor_y_status(df, guardar_como=None):
    """Barras horizontales apiladas: solicitudes con GAP por vendedor, desglosado por categoría de status."""
    if not {"Nombre del Vendedor", "Categoria", "¿Tiene GAP?"}.issubset(df.columns):
        print("Las columnas 'Nombre del Vendedor', 'Categoria' o '¿Tiene GAP?' no están presentes.")
        return None

    df_gap = df[df["¿Tiene GAP?"] == "SI"].copy()
    if df_gap.empty:
        print("No hay solicitudes con GAP para graficar.")
        return None

    pivote = pd.crosstab(df_gap["Nombre del Vendedor"], df_gap["Categoria"])
    orden_cols = [c for c in ORDEN_CATEGORIAS if c in pivote.columns]
    pivote = pivote[orden_cols]
    pivote["Total"] = pivote.sum(axis=1)
    pivote = pivote.sort_values("Total", ascending=True).drop(columns="Total")

    if pivote.empty:
        print("No hay datos de GAP por vendedor y Estatus para graficar.")
        return None

    fig, ax = plt.subplots(figsize=(9, max(4, len(pivote) * 0.55) + 0.8))
    izquierda = np.zeros(len(pivote))
    for col in orden_cols:
        valores = pivote[col].values
        ax.barh(pivote.index, valores, left=izquierda,
                 color=COLOR_CATEGORIA.get(col, MG_GRIS_CLARO), label=col, edgecolor="white")
        izquierda += valores

    ax.set_title("Solicitudes con GAP por Vendedor")
    ax.set_xlabel("Número de solicitudes con GAP")
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.12), frameon=False, ncol=4)
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como


def grafica_gap_financiado_por_vendedor(df, guardar_como=None):
    """Barras horizontales: solicitudes FINANCIADAS con GAP por vendedor,
    con felicitación a todos los que tengan la máxima colocación (maneja empates)."""
    if not {"Nombre del Vendedor", "Categoria", "¿Tiene GAP?"}.issubset(df.columns):
        print("Las columnas 'Nombre del Vendedor', 'Categoria' o '¿Tiene GAP?' no están presentes.")
        return None

    df_fin_gap = df[(df["Categoria"] == "FINANCIADO") & (df["¿Tiene GAP?"] == "SI")].copy()
    if df_fin_gap.empty:
        print("No hay solicitudes FINANCIADAS con GAP para graficar.")
        return None

    conteo = df_fin_gap["Nombre del Vendedor"].value_counts().sort_values(ascending=True)

    fig, ax = plt.subplots(figsize=(8, max(4, len(conteo) * 0.5)))
    colores = list(reversed(_gradiente(len(conteo))))

    if not conteo.empty:
        max_gap = conteo.max()
        vendedores_top = conteo[conteo == max_gap].index.tolist()

        ax.barh(conteo.index, conteo.values, color=colores, edgecolor="white")
        for i, (vendedor, valor) in enumerate(conteo.items()):
            ax.text(valor + max(conteo.values) * 0.01, i, str(valor), va="center", fontsize=9)
            if vendedor in vendedores_top and max_gap > 0:
                ax.text(valor + max(conteo.values) * 0.05, i,
                        f"¡Felicidades, {vendedor}!", va="center", fontsize=9,
                        color=MG_ROJO_OSCURO, fontweight="bold")

    ax.set_title("Colocación de GAP en Créditos FINANCIADOS por Vendedor")
    ax.set_xlabel("Solicitudes FINANCIADAS con GAP")
    plt.tight_layout()
    _guardar_si_procede(fig, guardar_como)
    plt.show()
    return guardar_como


def generar_todas_las_graficas(df):
    """Genera y muestra en pantalla todas las gráficas (uso interactivo en Colab,
    sin guardarlas en disco). Se conserva igual que en el script original."""
    print("=" * 72)
    print(" GRÁFICAS")
    print("=" * 72)
    grafica_status(df)
    grafica_dona_categoria(df)
    grafica_vendedores(df)
    grafica_vendedor_status(df)
    grafica_monto_por_vendedor(df)
    grafica_modelos(df)
    grafica_gap_por_categoria(df)
    grafica_gap_por_vendedor_total(df)
    grafica_gap_por_vendedor_y_status(df)
    grafica_gap_financiado_por_vendedor(df)


def generar_graficas_para_pdf(df):
    """Genera todas las gráficas guardándolas como PNG en CARPETA_GRAFICAS,
    listas para incrustarse en el reporte narrativo. Devuelve un diccionario
    {clave: ruta_png} solo con las gráficas que sí se pudieron generar
    (si falta una columna o no hay datos, esa clave simplemente no aparece)."""
    print("=" * 72)
    print(" GENERANDO GRÁFICAS PARA EL REPORTE")
    print("=" * 72)
    especificaciones = [
        ("status",               grafica_status,                    "g01_status.png"),
        ("dona_categoria",       grafica_dona_categoria,             "g02_dona_categoria.png"),
        ("vendedores",           grafica_vendedores,                 "g03_vendedores.png"),
        ("vendedor_status",      grafica_vendedor_status,            "g04_vendedor_status.png"),
        ("monto_por_vendedor",   grafica_monto_por_vendedor,         "g05_monto_vendedor.png"),
        ("modelos",              grafica_modelos,                    "g06_modelos.png"),
        ("gap_por_categoria",    grafica_gap_por_categoria,          "g08_gap_categoria.png"),
        ("gap_por_vendedor",     grafica_gap_por_vendedor_total,     "g09_gap_vendedor.png"),
        ("gap_vendedor_status",  grafica_gap_por_vendedor_y_status,  "g10_gap_vendedor_status.png"),
        ("gap_financiado_vend",  grafica_gap_financiado_por_vendedor, "g11_gap_financiado_vendedor.png"),
    ]
    rutas = {}
    for clave, funcion, nombre_archivo in especificaciones:
        ruta = os.path.join(CARPETA_GRAFICAS, nombre_archivo)
        resultado = funcion(df, guardar_como=ruta)
        plt.close("all")
        if resultado:
            rutas[clave] = resultado
    print(f"\n{len(rutas)} gráficas generadas correctamente.\n")
    return rutas


# =======================================================================
# 8) REPORTE NARRATIVO EN PDF (ReportLab)
#    Resumen ejecutivo redactado + tarjetas KPI + tablas con estilo +
#    gráficas incrustadas, con explicación de cada una. Mismo espíritu
#    que "Reporte de Expedientes Faltantes", adaptado a la bitácora.
# =======================================================================
def _quienes_maximo(serie):
    """Devuelve (lista_de_nombres, valor_maximo) para una Series indexada por
    vendedor. Si hay empate en el máximo, regresa a TODOS los empatados.
    Si la serie está vacía o el máximo es 0/():  regresa ([], 0)."""
    if serie is None or serie.empty:
        return [], 0
    maximo = serie.max()
    if pd.isna(maximo) or maximo <= 0:
        return [], 0
    nombres = serie[serie == maximo].index.tolist()
    return nombres, maximo


def _nombres_y(nombres):
    """Une una lista de nombres en texto natural: 'A', 'A y B', 'A, B y C'."""
    nombres = [str(n) for n in nombres]
    if not nombres:
        return ""
    if len(nombres) == 1:
        return nombres[0]
    return ", ".join(nombres[:-1]) + " y " + nombres[-1]


def imagen_ajustada(ruta, ancho_cm, alto_max_cm=None):
    """Crea un flowable Image respetando la proporción real del PNG, para
    que las gráficas horizontales (con alturas variables según el número
    de vendedores o modelos) siempre se vean bien en el PDF."""
    ancho_px, alto_px = ImageReader(ruta).getSize()
    alto_cm = ancho_cm * (alto_px / ancho_px)
    if alto_max_cm and alto_cm > alto_max_cm:
        alto_cm = alto_max_cm
        ancho_cm = alto_cm * (ancho_px / alto_px)
    return Image(ruta, width=ancho_cm * cm, height=alto_cm * cm, hAlign="CENTER")


def generar_reporte_pdf_verbal(df, resumen, tabla_vendedor, tabla_categoria, nombre_archivo=None):
    """
    Arma el reporte narrativo completo: portada con KPIs, resumen ejecutivo
    redactado, reporte detallado por sección (con tablas y gráficas) y
    conclusiones. Recibe los resultados ya calculados por
    resumen_general(), analisis_por_vendedor() y analisis_financiero_por_categoria()
    para no repetir esos cálculos ni duplicar la salida de consola.
    """
    if nombre_archivo is None:
        fecha_archivo = datetime.datetime.now().strftime("%Y%m%d_%H%M")
        nombre_archivo = f"Reporte_Bitacora_{fecha_archivo}.pdf"

    print("=" * 72)
    print(" GENERANDO REPORTE PDF NARRATIVO")
    print("=" * 72)

    rutas_graficas = generar_graficas_para_pdf(df)

    # -------------------------------------------------------------
    # Estilos
    # -------------------------------------------------------------
    styles = getSampleStyleSheet()
    estilo_kicker_portada = ParagraphStyle(
        "KickerPortada", parent=styles["Normal"], fontName=FUENTE_BOLD, fontSize=9.5,
        textColor=rl_colors.HexColor(MG_ROJO), alignment=TA_LEFT, spaceAfter=6, leading=12)
    estilo_titulo_portada = ParagraphStyle(
        "TituloPortada", parent=styles["Title"], fontName=FUENTE_BOLD, fontSize=25,
        textColor=rl_colors.HexColor(INBURSA_AZUL), alignment=TA_LEFT,
        spaceAfter=4, leading=29)
    estilo_subtitulo_portada = ParagraphStyle(
        "SubtituloPortada", parent=styles["Normal"], fontName=FUENTE_REGULAR, fontSize=12,
        textColor=rl_colors.HexColor(GRIS_TEXTO_SEC), alignment=TA_LEFT, spaceAfter=4)
    estilo_meta_portada = ParagraphStyle(
        "MetaPortada", parent=styles["Normal"], fontName=FUENTE_REGULAR, fontSize=9.5,
        textColor=rl_colors.HexColor(GRIS_TEXTO_SEC), alignment=TA_LEFT, leading=13)
    estilo_h1 = ParagraphStyle(
        "H1MG", parent=styles["Heading1"], fontName=FUENTE_BOLD, fontSize=15.5,
        textColor=rl_colors.HexColor(INBURSA_AZUL), spaceBefore=16, spaceAfter=8)
    estilo_h2 = ParagraphStyle(
        "H2MG", parent=styles["Heading2"], fontName=FUENTE_BOLD, fontSize=12.5,
        textColor=rl_colors.HexColor(MG_ROJO_OSCURO), spaceBefore=10, spaceAfter=6)
    estilo_cuerpo = ParagraphStyle(
        "CuerpoMG", parent=styles["Normal"], fontName=FUENTE_REGULAR, fontSize=10,
        textColor=rl_colors.HexColor(MG_GRIS_OSCURO), leading=15, alignment=TA_JUSTIFY, spaceAfter=6)
    estilo_nota = ParagraphStyle(
        "NotaMG", parent=styles["Normal"], fontSize=8.5,
        textColor=rl_colors.HexColor(GRIS_TEXTO_SEC), leading=11, alignment=TA_LEFT,
        spaceAfter=4, fontName=FUENTE_ITALICA)
    estilo_kpi_valor = ParagraphStyle(
        "KPIValor", parent=styles["Normal"], fontSize=20,
        textColor=rl_colors.HexColor(MG_GRIS_OSCURO), alignment=TA_CENTER,
        fontName=FUENTE_BOLD, leading=23)
    estilo_kpi_label = ParagraphStyle(
        "KPILabel", parent=styles["Normal"], fontName=FUENTE_BOLD, fontSize=7.8,
        textColor=rl_colors.HexColor(GRIS_TEXTO_SEC), alignment=TA_CENTER, leading=9.5)
    estilo_encabezado_tabla = ParagraphStyle(
        "EncabezadoTabla", parent=styles["Normal"], fontSize=8.3, leading=10,
        textColor=rl_colors.white, fontName=FUENTE_BOLD, alignment=TA_CENTER)

    FECHA_REPORTE = datetime.date.today().strftime("%d/%m/%Y")

    def encabezado_pie_pagina(canvas_obj, doc):
        """Encabezado y pie 'corporativo moderno': fondo blanco, una franja
        de marca delgada (azul Inbursa) en el borde superior, un pequeño
        tick rojo MG como acento y una regla fina en vez de los bloques de
        color sólido de la versión anterior."""
        canvas_obj.saveState()
        ancho, alto = letter

        canvas_obj.setFillColor(rl_colors.HexColor(INBURSA_AZUL))
        canvas_obj.rect(0, alto - 0.14 * cm, ancho, 0.14 * cm, fill=1, stroke=0)
        canvas_obj.setFillColor(rl_colors.HexColor(MG_ROJO))
        canvas_obj.rect(1.5 * cm, alto - 1.05 * cm, 0.24 * cm, 0.24 * cm, fill=1, stroke=0)

        canvas_obj.setFillColor(rl_colors.HexColor(INBURSA_AZUL))
        canvas_obj.setFont(FUENTE_BOLD, 10.5)
        canvas_obj.drawString(1.95 * cm, alto - 1.0 * cm, NOMBRE_EMPRESA)
        canvas_obj.setFillColor(rl_colors.HexColor(GRIS_TEXTO_SEC))
        canvas_obj.setFont(FUENTE_REGULAR, 8)
        canvas_obj.drawString(1.95 * cm, alto - 1.32 * cm, "Reporte de Bitácora de Solicitudes")

        canvas_obj.setFillColor(rl_colors.HexColor(GRIS_TEXTO_SEC))
        canvas_obj.setFont(FUENTE_REGULAR, 8.5)
        canvas_obj.drawRightString(ancho - 1.5 * cm, alto - 1.05 * cm, FECHA_REPORTE)

        canvas_obj.setStrokeColor(rl_colors.HexColor(GRIS_LINEA))
        canvas_obj.setLineWidth(0.8)
        canvas_obj.line(1.5 * cm, alto - 1.55 * cm, ancho - 1.5 * cm, alto - 1.55 * cm)

        canvas_obj.setStrokeColor(rl_colors.HexColor(GRIS_LINEA))
        canvas_obj.setLineWidth(0.8)
        canvas_obj.line(1.5 * cm, 1.05 * cm, ancho - 1.5 * cm, 1.05 * cm)

        canvas_obj.setFillColor(rl_colors.HexColor(MG_ROJO))
        canvas_obj.rect(1.5 * cm, 0.66 * cm, 0.16 * cm, 0.16 * cm, fill=1, stroke=0)
        canvas_obj.setFillColor(rl_colors.HexColor(GRIS_TEXTO_SEC))
        canvas_obj.setFont(FUENTE_REGULAR, 8)
        canvas_obj.drawString(1.85 * cm, 0.65 * cm, NOMBRE_ANALISTA)
        canvas_obj.drawCentredString(ancho / 2, 0.65 * cm, f"Página {doc.page}")
        canvas_obj.drawRightString(ancho - 1.5 * cm, 0.65 * cm, NOMBRE_EMPRESA)
        canvas_obj.restoreState()

    def tabla_estilo_mg(data, col_widths=None, alinear_derecha_desde=1):
        """Tabla 'corporativa moderna': encabezado azul Inbursa, sin líneas
        verticales (solo reglas horizontales finas), zebrado casi blanco y
        un filete rojo MG bajo el encabezado como único acento fuerte."""
        encabezado = [Paragraph(str(c), estilo_encabezado_tabla) for c in data[0]]
        data = [encabezado] + data[1:]
        tabla = Table(data, colWidths=col_widths, repeatRows=1)
        n_filas = len(data)
        estilo = [
            ("BACKGROUND", (0, 0), (-1, 0), rl_colors.HexColor(INBURSA_AZUL)),
            ("TEXTCOLOR", (0, 0), (-1, 0), rl_colors.white),
            ("FONTNAME", (0, 0), (-1, 0), FUENTE_BOLD),
            ("FONTNAME", (0, 1), (-1, -1), FUENTE_REGULAR),
            ("FONTSIZE", (0, 1), (-1, -1), 8.5),
            ("TEXTCOLOR", (0, 1), (-1, -1), rl_colors.HexColor(MG_GRIS_OSCURO)),
            ("ALIGN", (alinear_derecha_desde, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LINEBELOW", (0, 0), (-1, 0), 1.6, rl_colors.HexColor(MG_ROJO)),
            ("LINEBELOW", (0, 1), (-1, max(n_filas - 2, 1)), 0.5, rl_colors.HexColor(GRIS_LINEA)),
            ("BOX", (0, 0), (-1, -1), 0.75, rl_colors.HexColor(GRIS_LINEA)),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [rl_colors.white, rl_colors.HexColor(GRIS_ZEBRA)]),
            ("TOPPADDING", (0, 0), (-1, 0), 7),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 7),
            ("TOPPADDING", (0, 1), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]
        tabla.setStyle(TableStyle(estilo))
        return tabla

    def tarjeta_kpi(valor, etiqueta, color_acento):
        """Tarjeta KPI 'plana' corporativa: fondo blanco, barra de acento
        delgada arriba y el número protagonizando en el color de acento."""
        estilo_valor_acento = estilo_kpi_valor.clone("KPIValorAcento", textColor=rl_colors.HexColor(color_acento))
        t = Table(
            [[""], [Paragraph(str(valor), estilo_valor_acento)], [Paragraph(etiqueta, estilo_kpi_label)]],
            colWidths=[4.0 * cm], rowHeights=[0.11 * cm, None, None]
        )
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), rl_colors.HexColor(color_acento)),
            ("BACKGROUND", (0, 1), (-1, -1), rl_colors.white),
            ("BOX", (0, 0), (-1, -1), 0.75, rl_colors.HexColor(GRIS_LINEA)),
            ("TOPPADDING", (0, 1), (-1, 1), 10),
            ("BOTTOMPADDING", (0, 1), (-1, 1), 1),
            ("TOPPADDING", (0, 2), (-1, 2), 0),
            ("BOTTOMPADDING", (0, 2), (-1, 2), 10),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ]))
        return t

    # -------------------------------------------------------------
    # Datos clave ya disponibles en `resumen` (de resumen_general),
    # más algunos cálculos adicionales para la narrativa
    # -------------------------------------------------------------
    total = resumen.get("total", len(df))
    financiados = resumen.get("financiados", 0)
    aprobados = resumen.get("aprobados", 0)
    rechazados = resumen.get("rechazados", 0)
    en_tramite = resumen.get("en_tramite", 0)
    tiene_categoria = "financiados" in resumen

    def pct(n):
        return (n / total * 100) if total else 0

    n_vendedores = int(tabla_vendedor.shape[0]) if tabla_vendedor is not None else 0

    top_solicitudes_nombres, top_solicitudes_val = ([], 0)
    top_financiado_nombres, top_financiado_val = ([], 0)
    top_monto_nombres, top_monto_val = ([], 0)
    top_gap_nombres, top_gap_val = ([], 0)
    top_gap_fin_nombres, top_gap_fin_val = ([], 0)

    if tabla_vendedor is not None and not tabla_vendedor.empty:
        top_solicitudes_nombres, top_solicitudes_val = _quienes_maximo(tabla_vendedor["Total"])
        if "FINANCIADO" in tabla_vendedor.columns:
            top_financiado_nombres, top_financiado_val = _quienes_maximo(tabla_vendedor["FINANCIADO"])
        if "Monto Financiado ($)" in tabla_vendedor.columns:
            top_monto_nombres, top_monto_val = _quienes_maximo(tabla_vendedor["Monto Financiado ($)"])
        if "GAP Total" in tabla_vendedor.columns:
            top_gap_nombres, top_gap_val = _quienes_maximo(tabla_vendedor["GAP Total"])
        if "GAP Financiado" in tabla_vendedor.columns:
            top_gap_fin_nombres, top_gap_fin_val = _quienes_maximo(tabla_vendedor["GAP Financiado"])

    modelo_top = None
    modelo_top_val = 0
    if "Vehículo" in df.columns and df["Vehículo"].dropna().shape[0] > 0:
        conteo_modelos = df["Vehículo"].dropna().value_counts()
        if not conteo_modelos.empty:
            modelo_top = conteo_modelos.index[0]
            modelo_top_val = int(conteo_modelos.iloc[0])

    # -------------------------------------------------------------
    # Construcción del documento
    # -------------------------------------------------------------
    elementos = []

    # --- Portada ---
    elementos.append(Spacer(1, 0.2 * cm))
    elementos.append(Paragraph("REPORTE MENSUAL&nbsp;&nbsp;·&nbsp;&nbsp;BITÁCORA DE SOLICITUDES", estilo_kicker_portada))
    elementos.append(Paragraph("Reporte de Análisis", estilo_titulo_portada))
    elementos.append(Paragraph(f"{NOMBRE_EMPRESA} · {SUBTITULO_EMPRESA}", estilo_subtitulo_portada))
    elementos.append(Spacer(1, 0.12 * cm))
    elementos.append(HRFlowable(width="100%", thickness=1, color=rl_colors.HexColor(GRIS_LINEA),
                                 spaceBefore=6, spaceAfter=10, hAlign="LEFT"))
    elementos.append(Paragraph(f"Elaborado por <b>{NOMBRE_ANALISTA}</b> el <b>{FECHA_REPORTE}</b>", estilo_meta_portada))
    elementos.append(Spacer(1, 0.45 * cm))

    intro_portada = Table(
        [[Paragraph(
            f"Este reporte resume el comportamiento de las {total} solicitudes de crédito automotriz "
            f"registradas en la bitácora, desde su ingreso hasta su cierre como <b>FINANCIADA</b> "
            f"(crédito ya dispersado), <b>APROBADA</b> (aprobada, aún sin dispersar), <b>RECHAZADA</b> "
            f"o en <b>CONTRAPROPUESTA</b>/negociación. Incluye el desempeño por vendedor, la colocación "
            f"del seguro GAP y los modelos de vehículo con mayor demanda.",
            estilo_cuerpo
        )]],
        colWidths=[18 * cm]
    )
    intro_portada.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), rl_colors.HexColor(AZUL_PALIDO)),
        ("LINEBEFORE", (0, 0), (0, 0), 3, rl_colors.HexColor(INBURSA_AZUL)),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
    ]))
    elementos.append(intro_portada)
    elementos.append(Spacer(1, 0.45 * cm))

    _kpi_gap = ""  # columna vacía angosta entre tarjetas, para que se vean separadas
    fila_kpis = [
        tarjeta_kpi(total, "Total de\nSolicitudes", MG_ROJO_OSCURO), _kpi_gap,
        tarjeta_kpi(financiados, "Financiadas", MG_ROJO_MEDIO), _kpi_gap,
        tarjeta_kpi(aprobados, "Aprobadas", MG_ROJO), _kpi_gap,
        tarjeta_kpi(n_vendedores, "Vendedores\nInvolucrados", INBURSA_AZUL),
    ]
    anchos_kpis = [4.0 * cm, 0.35 * cm, 4.0 * cm, 0.35 * cm, 4.0 * cm, 0.35 * cm, 4.0 * cm]
    tabla_kpis = Table([fila_kpis], colWidths=anchos_kpis)
    tabla_kpis.setStyle(TableStyle([("ALIGN", (0, 0), (-1, -1), "CENTER"), ("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
    elementos.append(tabla_kpis)
    elementos.append(Spacer(1, 0.5 * cm))

    # --- Resumen Ejecutivo ---
    elementos.append(Paragraph("Resumen Ejecutivo", estilo_h1))
    elementos.append(HRFlowable(width="100%", thickness=1, color=rl_colors.HexColor(MG_ROJO), spaceAfter=8))

    elementos.append(Paragraph("Panorama general", estilo_h2))
    if tiene_categoria:
        elementos.append(Paragraph(
            f"De las {total} solicitudes registradas en el periodo, {financiados} ({pct(financiados):.1f}%) "
            f"llegaron a <b>FINANCIADAS</b> (crédito ya dispersado), {aprobados} ({pct(aprobados):.1f}%) están "
            f"<b>APROBADAS</b> pendientes de dispersar, {rechazados} ({pct(rechazados):.1f}%) fueron "
            f"<b>RECHAZADAS</b> y {en_tramite} ({pct(en_tramite):.1f}%) permanecen en "
            f"<b>CONTRAPROPUESTA</b> o negociación.",
            estilo_cuerpo
        ))
        if "desglose_status" in resumen:
            filas_status = [[s, int(c), f"{c/total*100:.1f}%"] for s, c in resumen["desglose_status"].items()]
            elementos.append(tabla_estilo_mg(
                [["Status", "Solicitudes", "% del Total"]] + filas_status,
                col_widths=[7 * cm, 4 * cm, 4 * cm]
            ))
    else:
        elementos.append(Paragraph(
            f"Se registraron {total} solicitudes en el periodo. No fue posible clasificarlas por Estatus "
            f"porque la columna 'ESTATUS' no está presente en el archivo fuente.",
            estilo_cuerpo
        ))
    elementos.append(Spacer(1, 0.3 * cm))

    elementos.append(Paragraph("Panorama financiero", estilo_h2))
    partes_financiero = []
    if "monto_total" in resumen:
        partes_financiero.append(
            f"El monto total a financiar de todas las solicitudes asciende a <b>${resumen['monto_total']:,.2f}</b>."
        )
    if "monto_financiado" in resumen:
        partes_financiero.append(
            f"De ese total, ${resumen['monto_financiado']:,.2f} ya corresponden a crédito "
            f"<b>FINANCIADO</b> (dispersado)"
            + (f", con un ticket promedio de ${resumen['ticket_financiado']:,.2f} por crédito"
               if "ticket_financiado" in resumen else "") + "."
        )
    if "monto_aprobado" in resumen:
        partes_financiero.append(
            f"${resumen['monto_aprobado']:,.2f} están <b>APROBADOS</b> y en espera de dispersarse"
            + (f", con un ticket promedio de ${resumen['ticket_aprobado']:,.2f}"
               if "ticket_aprobado" in resumen else "") + "."
        )
    if "pct_enganche" in resumen:
        partes_financiero.append(f"El enganche promedio solicitado equivale al {resumen['pct_enganche']:.1f}% del precio de venta.")
    if "plazo_promedio" in resumen:
        partes_financiero.append(f"El plazo promedio solicitado es de {resumen['plazo_promedio']:.0f} meses.")
    if "tasa_promedio" in resumen:
        partes_financiero.append(f"La tasa de interés anual promedio es de {resumen['tasa_promedio']:.2f}%.")
    if "edad_promedio" in resumen:
        partes_financiero.append(f"La edad promedio de los clientes es de {resumen['edad_promedio']:.0f} años.")
    if partes_financiero:
        elementos.append(Paragraph(" ".join(partes_financiero), estilo_cuerpo))
    else:
        elementos.append(Paragraph(
            "No se encontraron columnas de monto, enganche, plazo o tasa en el archivo fuente para "
            "construir el panorama financiero.", estilo_nota
        ))
    elementos.append(Spacer(1, 0.6 * cm))

    elementos.append(Paragraph("Seguro GAP", estilo_h2))
    if "pct_gap" in resumen:
        texto_gap = (
            f"{resumen.get('n_gap', 0)} solicitudes ({resumen['pct_gap']:.1f}% del total) incluyen seguro GAP. "
        )
        if tiene_categoria and financiados:
            df_fin_gap_n = int((df.loc[df["Categoria"] == "FINANCIADO", "¿Tiene GAP?"] == "SI").sum()) if "¿Tiene GAP?" in df.columns else 0
            pct_gap_fin = (df_fin_gap_n / financiados * 100) if financiados else 0
            texto_gap += (
                f"Dentro de los créditos ya <b>FINANCIADOS</b>, {df_fin_gap_n} de {financiados} "
                f"({pct_gap_fin:.1f}%) llevan GAP colocado."
            )
            if "Monto GAP" in df.columns:
                monto_gap_fin = df.loc[(df["Categoria"] == "FINANCIADO") & (df["¿Tiene GAP?"] == "SI"), "Monto GAP"].sum()
                if monto_gap_fin:
                    texto_gap += f" El monto total colocado en GAP sobre financiados es de ${monto_gap_fin:,.2f}."
        elementos.append(Paragraph(texto_gap, estilo_cuerpo))
    else:
        elementos.append(Paragraph(
            "No se encontró la columna '¿Tiene GAP?' en el archivo fuente, por lo que no fue posible "
            "analizar la colocación de este seguro.", estilo_nota
        ))
    elementos.append(Spacer(1, 0.3 * cm))

    elementos.append(Paragraph("Vendedores destacados", estilo_h2))
    if tabla_vendedor is not None and not tabla_vendedor.empty:
        texto_vend = f"Se identificaron {n_vendedores} vendedores con solicitudes registradas. "
        if top_solicitudes_nombres:
            texto_vend += (
                f"<b>{_nombres_y(top_solicitudes_nombres)}</b> "
                f"{'concentran' if len(top_solicitudes_nombres) > 1 else 'concentra'} el mayor número de "
                f"solicitudes generadas, con {int(top_solicitudes_val)}. "
            )
        if top_financiado_nombres:
            texto_vend += (
                f"En créditos <b>FINANCIADOS</b>, {_nombres_y(top_financiado_nombres)} "
                f"{'lideran' if len(top_financiado_nombres) > 1 else 'lidera'} con {int(top_financiado_val)}. "
            )
        if top_monto_nombres:
            texto_vend += (
                f"El mayor monto colocado en créditos financiados corresponde a "
                f"{_nombres_y(top_monto_nombres)}, con ${top_monto_val:,.2f}. "
            )
        if top_gap_fin_nombres:
            texto_vend += (
                f"En colocación de GAP sobre créditos financiados, "
                f"{_nombres_y(top_gap_fin_nombres)} {'destacan' if len(top_gap_fin_nombres) > 1 else 'destaca'} "
                f"con {int(top_gap_fin_val)}."
            )
        elementos.append(Paragraph(texto_vend, estilo_cuerpo))
    else:
        elementos.append(Paragraph(
            "No se encontró la columna 'Nombre del Vendedor' en el archivo fuente.", estilo_nota
        ))
    elementos.append(Spacer(1, 0.3 * cm))

    if modelo_top:
        elementos.append(Paragraph("Modelo más solicitado", estilo_h2))
        elementos.append(Paragraph(
            f"El vehículo más solicitado en el periodo es <b>{modelo_top}</b>, con {modelo_top_val} solicitudes.",
            estilo_cuerpo
        ))
        elementos.append(Spacer(1, 0.2 * cm))

    # --- Focos de atención (comparativo RECHAZADO vs FINANCIADO) ---
    notas_atencion = []
    if tabla_categoria is not None and "RECHAZADO" in tabla_categoria.index:
        rech = tabla_categoria.loc["RECHAZADO"]
        referencia = "FINANCIADO" if "FINANCIADO" in tabla_categoria.index else (
            "APROBADO" if "APROBADO" in tabla_categoria.index else None)
        if referencia:
            comp = tabla_categoria.loc[referencia]
            if "% Enganche prom." in tabla_categoria.columns and pd.notna(rech.get("% Enganche prom.")) and pd.notna(comp.get("% Enganche prom.")):
                if rech["% Enganche prom."] < comp["% Enganche prom."] - 3:
                    notas_atencion.append(
                        f"Las solicitudes RECHAZADAS piden en promedio un enganche menor "
                        f"({rech['% Enganche prom.']:.1f}%) que las {referencia} ({comp['% Enganche prom.']:.1f}%), "
                        f"lo que sugiere que un enganche insuficiente podría estar asociado al rechazo."
                    )
            if "Monto Total a Financiar" in tabla_categoria.columns and pd.notna(rech.get("Monto Total a Financiar")) and pd.notna(comp.get("Monto Total a Financiar")):
                if rech["Monto Total a Financiar"] > comp["Monto Total a Financiar"] * 1.15:
                    notas_atencion.append(
                        f"El monto promedio a financiar en solicitudes RECHAZADAS (${rech['Monto Total a Financiar']:,.2f}) "
                        f"es notablemente mayor al de las {referencia} (${comp['Monto Total a Financiar']:,.2f})."
                    )
            if "% con GAP" in tabla_categoria.columns and pd.notna(rech.get("% con GAP")) and pd.notna(comp.get("% con GAP")):
                if rech["% con GAP"] < comp["% con GAP"] - 5:
                    notas_atencion.append(
                        f"Las solicitudes RECHAZADAS llevan GAP con menor frecuencia ({rech['% con GAP']:.1f}%) "
                        f"que las {referencia} ({comp['% con GAP']:.1f}%)."
                    )
    if notas_atencion:
        elementos.append(Paragraph("Focos de atención", estilo_h2))
        for nota in notas_atencion:
            elementos.append(Paragraph("•  " + nota, estilo_cuerpo))
        elementos.append(Spacer(1, 0.2 * cm))

    if resumen.get("incompletas"):
        elementos.append(Paragraph(
            f"<b>Nota de calidad de datos:</b> {resumen['incompletas']} solicitudes tienen datos incompletos "
            f"(marca, vehículo o monto sin capturar), lo cual puede afectar la precisión de algunos análisis.",
            estilo_nota
        ))

    elementos.append(PageBreak())
    # === FIN RESUMEN EJECUTIVO — continúa el Reporte Detallado abajo ===

    # ===============================================================
    # REPORTE DETALLADO
    # ===============================================================
    elementos.append(Paragraph("Reporte Detallado", estilo_h1))
    elementos.append(HRFlowable(width="100%", thickness=1, color=rl_colors.HexColor(MG_ROJO), spaceAfter=8))

    # --- 1. Distribución de solicitudes por status ---
    if "status" in rutas_graficas or "dona_categoria" in rutas_graficas:
        elementos.append(Paragraph("1. Distribución de Solicitudes por Estatus", estilo_h2))
        elementos.append(Paragraph(
            "La siguiente gráfica muestra cuántas solicitudes hay en cada Estatus capturado en la "
            "bitácora, y la gráfica en DONA agrupa esos mismos Estatus en las cuatro categorías de seguimiento "
            "(Financiado, Aprobado, Contrapropuesta y Rechazado), señalando qué vendedores "
            "aportan a cada una.",
            estilo_cuerpo
        ))
        if "status" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["status"], ancho_cm=16, alto_max_cm=9))
            elementos.append(Spacer(1, 0.2 * cm))
        if "dona_categoria" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["dona_categoria"], ancho_cm=12, alto_max_cm=12))
        elementos.append(Spacer(1, 0.4 * cm))

    # --- 2. Desempeño por vendedor ---
    if tabla_vendedor is not None and not tabla_vendedor.empty:
        elementos.append(Paragraph("2. Desempeño por Vendedor", estilo_h2))
        elementos.append(Paragraph(
            f"Se registran {n_vendedores} vendedores con solicitudes en el periodo. La tabla siguiente "
            f"desglosa, para cada uno, el total de solicitudes generadas y en qué categoría cerraron "
            f"(Financiado, Aprobado, Contrapropuesta o Rechazado), junto con su % de conversión a "
            f"crédito Financiado.",
            estilo_cuerpo
        ))

        # Etiquetas cortas para encabezado (con salto manual en "Contrapropuesta"
        # para que no se parta a media palabra dentro de la columna angosta)
        ETIQUETA_CORTA_CATEGORIA = {
            "FINANCIADO": "Financiado", "APROBADO": "Aprobado",
            "CONTRAPROPUESTA": "Contra-<br/>propuesta", "RECHAZADO": "Rechazado",
        }
        encabezados_v = ["Vendedor", "Total"]
        claves_v = []
        for c in ORDEN_CATEGORIAS:
            if c in tabla_vendedor.columns:
                encabezados_v.append(ETIQUETA_CORTA_CATEGORIA.get(c, c.capitalize()))
                claves_v.append(c)
        if "% Financiado" in tabla_vendedor.columns:
            encabezados_v.append("%<br/>Financiado")

        filas_v = []
        for vendedor, fila in tabla_vendedor.iterrows():
            f = [vendedor, int(fila.get("Total", 0))]
            for c in claves_v:
                f.append(int(fila.get(c, 0)))
            if "% Financiado" in tabla_vendedor.columns:
                f.append(f"{fila.get('% Financiado', 0):.1f}%")
            filas_v.append(f)

        ancho_disponible_v = 18.3 * cm - 4.2 * cm
        ancho_col_v = ancho_disponible_v / max(len(encabezados_v) - 1, 1)
        anchos_v = [4.2 * cm] + [ancho_col_v] * (len(encabezados_v) - 1)
        elementos.append(tabla_estilo_mg([encabezados_v] + filas_v, col_widths=anchos_v))
        elementos.append(Spacer(1, 0.3 * cm))

        if "vendedores" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["vendedores"], ancho_cm=16, alto_max_cm=13))
            elementos.append(Spacer(1, 0.2 * cm))
        if "vendedor_status" in rutas_graficas:
            elementos.append(Paragraph(
                "La siguiente gráfica apila, por vendedor, cuántas solicitudes cerraron en cada categoría, "
                "para comparar de un vistazo no solo el volumen sino la calidad del cierre de cada uno.",
                estilo_cuerpo
            ))
            elementos.append(imagen_ajustada(rutas_graficas["vendedor_status"], ancho_cm=16, alto_max_cm=13))
        elementos.append(Spacer(1, 0.4 * cm))

    # --- 3. Monto colocado por vendedor ---
    if "monto_por_vendedor" in rutas_graficas:
        elementos.append(Paragraph("3. Monto Colocado por Vendedor", estilo_h2))
        elementos.append(Paragraph(
            "Esta gráfica compara, para cada vendedor, el monto en pesos que tiene en créditos "
            "APROBADOS (aún sin dispersar) contra el que ya tiene en créditos FINANCIADOS "
            "(dispersados), lo que ayuda a distinguir entre volumen de solicitudes y cierre "
            "efectivo de negocio.",
            estilo_cuerpo
        ))
        elementos.append(imagen_ajustada(rutas_graficas["monto_por_vendedor"], ancho_cm=16, alto_max_cm=15))
        elementos.append(Spacer(1, 0.4 * cm))

    # --- 4. Comparativo financiero por categoría ---
    if tabla_categoria is not None and not tabla_categoria.empty:
        elementos.append(Paragraph("4. Comparativo Financiero por Categoría", estilo_h2))
        elementos.append(Paragraph(
            "Esta tabla compara, para cada categoría de cierre, el precio de venta, enganche, monto "
            "a financiar, plazo y tasa promedio. Sirve para detectar focos de atención: por ejemplo, "
            "si las solicitudes RECHAZADAS piden un % de enganche más bajo, un monto más alto, o "
            "llevan menos GAP que las APROBADAS o FINANCIADAS, ese es un patrón a vigilar.",
            estilo_cuerpo
        ))

        columnas_disp = list(tabla_categoria.columns)
        encabezados_cat = ["Categoría"] + columnas_disp
        filas_cat = []
        for cat, fila in tabla_categoria.iterrows():
            f = [cat]
            for col in columnas_disp:
                valor = fila[col]
                if pd.isna(valor):
                    f.append("—")
                elif "%" in col:
                    f.append(f"{valor:.1f}%")
                elif "Monto" in col or "Precio" in col or "Enganche" in col:
                    f.append(f"${valor:,.0f}")
                else:
                    f.append(f"{valor:.1f}")
            filas_cat.append(f)

        ancho_disp = min(2.6 * cm, (18 * cm - 3.2 * cm) / max(len(columnas_disp), 1))
        anchos_cat = [3.2 * cm] + [ancho_disp] * len(columnas_disp)
        elementos.append(tabla_estilo_mg([encabezados_cat] + filas_cat, col_widths=anchos_cat))
        elementos.append(Spacer(1, 0.4 * cm))

    # --- 5. Seguro GAP ---
    tiene_gap_col = "¿Tiene GAP?" in df.columns
    if tiene_gap_col:
        elementos.append(Paragraph("5. Seguro GAP", estilo_h2))
        elementos.append(Paragraph(
            "El seguro GAP cubre la diferencia entre el valor asegurado del vehículo y el saldo "
            "insoluto del crédito en caso de pérdida total, por lo que su colocación es un indicador "
            "de venta cruzada relevante para la operación. A continuación se muestra qué proporción "
            "de solicitudes lo incluye, primero por categoría de cierre y después por vendedor.",
            estilo_cuerpo
        ))
        if "gap_por_categoria" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["gap_por_categoria"], ancho_cm=13, alto_max_cm=10))
            elementos.append(Spacer(1, 0.2 * cm))
        if "gap_por_vendedor" in rutas_graficas:
            elementos.append(imagen_ajustada(rutas_graficas["gap_por_vendedor"], ancho_cm=16, alto_max_cm=13))
            elementos.append(Spacer(1, 0.2 * cm))
        if "gap_vendedor_status" in rutas_graficas:
            elementos.append(Paragraph(
                "Desglose de esas mismas solicitudes con GAP por vendedor, separadas por la categoría "
                "en la que cerraron:",
                estilo_cuerpo
            ))
            elementos.append(imagen_ajustada(rutas_graficas["gap_vendedor_status"], ancho_cm=16, alto_max_cm=13))
            elementos.append(Spacer(1, 0.2 * cm))
        if "gap_financiado_vend" in rutas_graficas:
            elementos.append(Paragraph(
                "Y específicamente, la colocación de GAP dentro de los créditos ya FINANCIADOS "
                "(el indicador más relevante, ya que ese GAP ya está efectivamente vendido):",
                estilo_cuerpo
            ))
            elementos.append(imagen_ajustada(rutas_graficas["gap_financiado_vend"], ancho_cm=16, alto_max_cm=13))
        elementos.append(Spacer(1, 0.4 * cm))

    # --- 6. Modelos de vehículo más solicitados ---
    if "modelos" in rutas_graficas:
        elementos.append(Paragraph("6. Modelos de Vehículo Más Solicitados", estilo_h2))
        texto_modelos = "La siguiente gráfica muestra los modelos de vehículo con mayor número de solicitudes en el periodo."
        if modelo_top:
            texto_modelos += f" <b>{modelo_top}</b> encabeza la lista con {modelo_top_val} solicitudes."
        elementos.append(Paragraph(texto_modelos, estilo_cuerpo))
        elementos.append(imagen_ajustada(rutas_graficas["modelos"], ancho_cm=16, alto_max_cm=13))
        elementos.append(Spacer(1, 0.4 * cm))

    # ===============================================================
    # CONCLUSIONES Y FACTORES IMPORTANTES
    # ===============================================================
    elementos.append(Paragraph("Conclusiones y Factores Importantes", estilo_h1))
    elementos.append(HRFlowable(width="100%", thickness=1, color=rl_colors.HexColor(MG_ROJO), spaceAfter=8))

    conclusiones = []
    if tiene_categoria and total:
        tasa_financiamiento = financiados / total * 100
        conclusiones.append(
            f"<b>Tasa de cierre efectivo:</b> {financiados} de {total} solicitudes ({tasa_financiamiento:.1f}%) "
            f"se convirtieron en crédito FINANCIADO en el periodo. "
            f"{aprobados} solicitudes adicionales ({pct(aprobados):.1f}%) están APROBADAS y representan "
            f"negocio a punto de cerrarse si se les da seguimiento oportuno a su dispersión."
        )
    if top_solicitudes_nombres:
        conclusiones.append(
            f"<b>Carga de trabajo por vendedor:</b> {_nombres_y(top_solicitudes_nombres)} "
            f"{'concentran' if len(top_solicitudes_nombres) > 1 else 'concentra'} el mayor número de "
            f"solicitudes generadas ({int(top_solicitudes_val)}); conviene validar si esto se traduce "
            f"proporcionalmente en créditos financiados o si requiere apoyo adicional para cerrar más negocio."
        )
    if top_financiado_nombres:
        conclusiones.append(
            f"<b>Mejor conversión a financiado:</b> {_nombres_y(top_financiado_nombres)} "
            f"{'lideran' if len(top_financiado_nombres) > 1 else 'lidera'} en créditos efectivamente "
            f"FINANCIADOS ({int(top_financiado_val)}); vale la pena identificar qué está(n) haciendo bien "
            f"para replicarlo con el resto del equipo."
        )
    if top_gap_fin_nombres:
        conclusiones.append(
            f"<b>Venta cruzada de GAP:</b> {_nombres_y(top_gap_fin_nombres)} "
            f"{'destacan' if len(top_gap_fin_nombres) > 1 else 'destaca'} colocando GAP en créditos ya "
            f"financiados ({int(top_gap_fin_val)}); reforzar esta práctica con el resto del equipo "
            f"incrementaría los ingresos por venta cruzada sin necesidad de más solicitudes."
        )
    for nota in notas_atencion:
        conclusiones.append(f"<b>Foco de atención:</b> {nota}")
    if resumen.get("incompletas"):
        conclusiones.append(
            f"<b>Calidad de datos:</b> {resumen['incompletas']} solicitudes tienen datos incompletos "
            f"(marca, vehículo o monto sin capturar); se recomienda completarlos en la fuente para que "
            f"los próximos reportes reflejen el 100% de la información."
        )

    if not conclusiones:
        conclusiones.append(
            "No se generaron conclusiones automáticas adicionales: revisa que el archivo fuente "
            "incluya las columnas ESTATUS, Nombre del Vendedor y Monto Total a Financiar para un "
            "análisis más completo."
        )

    for c in conclusiones:
        elementos.append(Paragraph("•  " + c, estilo_cuerpo))

    # -------------------------------------------------------------
    # Generar el PDF
    # -------------------------------------------------------------
    doc = SimpleDocTemplate(
        nombre_archivo, pagesize=letter,
        topMargin=1.8 * cm, bottomMargin=1.3 * cm, leftMargin=1.5 * cm, rightMargin=1.5 * cm
    )
    doc.build(elementos, onFirstPage=encabezado_pie_pagina, onLaterPages=encabezado_pie_pagina)

    print(f"\nReporte PDF generado: {nombre_archivo}")
    if EN_COLAB:
        files.download(nombre_archivo)
    else:
        print(f"Archivo guardado en: {nombre_archivo}")

    return nombre_archivo


# =======================================================================
# 9) FLUJO PRINCIPAL
# =======================================================================
def main(ruta_local=None):
    df_crudo = cargar_archivo(ruta_local=ruta_local)
    df = limpiar_datos(df_crudo)

    resumen = resumen_general(df)
    tabla_vendedor = analisis_por_vendedor(df)
    tabla_categoria = analisis_financiero_por_categoria(df)

    generar_reporte_pdf_verbal(df, resumen, tabla_vendedor, tabla_categoria)

    print("=" * 72)
    print(" Análisis completo. Se generó un PDF narrativo con resumen ejecutivo,")
    print(" tablas con estilo y todas las gráficas explicadas.")
    print(" Puedes volver a correr esta celda con otro archivo.")
    print("=" * 72)

    return df

if __name__ == "__main__":
    main()